// ═══════════════════════════════════════════════════════════════════
//  ANIMAIS-DATA.JS — Animais, Montarias e Parceiros (Tormenta 20)
//  Consumido por:
//    • animais.js → sub-aba "🐎 Animais & Montarias" (consulta)
//    • viagem.js  → montarias compráveis alimentam o ritmo (deslocMetros)
//
//  Fontes: Tormenta20, Ameaças de Arton, Deuses & Heróis,
//  Jornada Heróica, Deuses de Arton, Revista Tormenta.
// ═══════════════════════════════════════════════════════════════════

// ── ANIMAIS COMPRÁVEIS (preço + descrição) ──────────────────────────
// deslocMetros: deslocamento que a montaria dá ao cavaleiro (iniciante),
// usado pela aba Viagem. Itens/serviços não têm.
window.ANIMAIS_COMPRA = [
  { chave: 'alforje', nome: 'Alforje', preco: 'T$ 30', tipo: 'Item de montaria',
    texto: 'Sacos de couro feitos para serem presos a uma sela. Permitem que um parceiro montaria carregue até 10 espaços de item para você.' },
  { chave: 'cao-de-caca', nome: 'Cão de caça', preco: 'T$ 150', tipo: 'Animal', deslocMetros: 9,
    texto: 'Cachorro valente e leal. Pode ser parceiro perseguidor (para treinados em Adestramento) ou montaria para personagens Pequenos e Minúsculos.' },
  { chave: 'cavalo', nome: 'Cavalo', preco: 'T$ 75', tipo: 'Montaria', deslocMetros: 12,
    texto: 'A montaria mais comum no Reinado. Sem treinamento se assusta facilmente: exige Cavalgar (CD 20) por rodada para permanecer montado em combate (cavalos de guerra dispensam o teste).' },
  { chave: 'cavalo-de-guerra', nome: 'Cavalo de guerra', preco: 'T$ 400', tipo: 'Montaria', deslocMetros: 12,
    texto: 'Cavalo treinado para o combate. Dispensa o teste de Cavalgar para permanecer montado quando a luta começa.' },
  { chave: 'estabulo', nome: 'Estábulo (por dia)', preco: 'T$ 0,1', tipo: 'Serviço',
    texto: 'Abrigo para o animal. Inclui alimentação.' },
  { chave: 'ponei', nome: 'Pônei', preco: 'T$ 5', tipo: 'Montaria', deslocMetros: 12,
    texto: 'A montaria mais comum entre raças Pequenas. Sem treinamento se assusta facilmente: Cavalgar (CD 20) por rodada para permanecer montado em combate (pôneis de guerra dispensam).' },
  { chave: 'ponei-de-guerra', nome: 'Pônei de guerra', preco: 'T$ 30', tipo: 'Montaria', deslocMetros: 12,
    texto: 'Pônei treinado para o combate. Dispensa o teste de Cavalgar para permanecer montado.' },
  { chave: 'trobo', nome: 'Trobo', preco: 'T$ 60', tipo: 'Montaria', deslocMetros: 9,
    texto: 'Enormes aves (pássaros-touros) parecidas com avestruzes com chifres, couro e cascos; sem asas. Muito dóceis, usadas em áreas rurais como animais de carga e tração, mas também como montaria.' },
];

// ── EQUIPAMENTOS DE MONTARIA (preço + espaços) ──────────────────────
window.ANIMAIS_EQUIP = [
  { chave: 'arm-leve', nome: 'Armadura de montaria leve', preco: 'T$ 600', espacos: 2,
    texto: 'Vestida pela montaria. Aumenta um bônus numérico fornecido por ela em +1 (se for fixo) ou em um passo (se for um bônus rolado).' },
  { chave: 'arm-pesada', nome: 'Armadura de montaria pesada', preco: 'T$ 3.000', espacos: 5,
    texto: 'Como a leve, mas aumenta o bônus em +2 ou em dois passos. Contudo, diminui o deslocamento da montaria em –3 m. Montarias voadoras não podem usar armaduras pesadas.' },
  { chave: 'arreios-namalkah', nome: 'Arreios namalkahnianos', preco: 'T$ 50', espacos: 1,
    texto: 'Couro com nós e fivelas que permitem ajustes precisos. Item vestido do animal; aumentam o deslocamento de um veículo de tração animal em +3 m.' },
  { chave: 'caparazao', nome: 'Caparazão', preco: 'T$ 75', espacos: 1,
    texto: 'Cobertura de tecido finamente decorado que adorna e protege o animal. A montaria fornece +1 em Diplomacia e Intimidação (além de seus benefícios usuais).' },
  { chave: 'estribos', nome: 'Estribos', preco: 'T$ 60', espacos: 1,
    texto: 'Apoios para os pés, parte do equipamento básico de um ginete. Vestido pela montaria. Quando você faz uma investida montada, causa +1d8 pontos de dano.' },
  { chave: 'ornamento', nome: 'Ornamento', preco: 'T$ 50', espacos: 1,
    texto: 'Muito usado em desfiles e justas. Uma vez por cena, montado e treinado em Cavalgar, você pode se exibir com a montaria para receber +1d4 em um teste de perícia baseada em Carisma.' },
];

// ── TIPOS DE PARCEIRO (arquétipos com 3 níveis de poder) ────────────
window.PARCEIRO_TIPOS = [
  { nome: 'Adepto', desc: 'Um conjurador que ajuda a lançar magias.',
    ini: 'O custo para lançar suas magias de 1º círculo diminui –1 PM.',
    vet: 'Como acima, e também reduz o custo das suas magias de 2º círculo.',
    mes: 'Como acima, e essa redução passa a ser cumulativa com outras reduções.' },
  { nome: 'Ajudante', desc: 'Um bardo, nobre ou sábio que ajuda com palavras firmes.',
    ini: '+2 em duas perícias.', vet: '+2 em três perícias.', mes: '+4 em três perícias.',
    obs: 'As perícias são definidas pelo parceiro. Não pode fornecer bônus em Luta ou Pontaria.' },
  { nome: 'Assassino', desc: 'Um ladino ou outro tipo furtivo e letal.',
    ini: 'Você pode usar Ataque Furtivo +1d6 (cumulativo se já tiver).',
    vet: 'Além do Ataque Furtivo, fornece bônus por flanquear contra um inimigo por rodada.',
    mes: 'Muda o dano do Ataque Furtivo para +2d6.' },
  { nome: 'Atirador', desc: 'Um arqueiro, besteiro ou combatente à distância.',
    ini: 'Uma vez por rodada, +1d6 em uma rolagem de dano à distância.', vet: 'Muda para +1d10.', mes: 'Muda para +2d8.' },
  { nome: 'Combatente', desc: 'Um bucaneiro, guerreiro, paladino ou animal de caça.',
    ini: '+2 em testes de ataque.', vet: '+3 em testes de ataque.',
    mes: '+4 em testes de ataque e, uma vez por rodada, você pode gastar 5 PM para fazer um ataque extra.' },
  { nome: 'Destruidor', desc: 'Um arcanista ou inventor.',
    ini: 'Uma vez por rodada, como ação livre, gaste 1 PM para causar 2d6 de ácido, eletricidade, fogo ou frio em um alvo em alcance curto.',
    vet: 'Como acima, e você também pode gastar 2 PM para causar 4d6.',
    mes: 'Como acima, e você também pode gastar 4 PM para causar 6d6 em uma área de 6 m de raio em alcance médio.' },
  { nome: 'Fortão', desc: 'Um bárbaro, lutador ou outro que bate primeiro e pensa depois.',
    ini: 'Uma vez por rodada, +1d8 em uma rolagem de dano corpo a corpo.', vet: 'Muda para +1d12.', mes: 'Muda para +3d6.' },
  { nome: 'Guardião', desc: 'Um cavaleiro, cão de guarda ou NPC cuja função é proteger.',
    ini: '+2 na Defesa.', vet: '+3 na Defesa.', mes: '+4 na Defesa e +2 em testes de resistência.' },
  { nome: 'Magivocador', desc: 'Um conjurador especializado em magias ofensivas.',
    ini: 'O dano das suas magias aumenta em +1 dado do mesmo tipo.',
    vet: 'Como acima, e a CD para resistir a suas magias aumenta em +1.',
    mes: 'Como acima, mas dobra os bônus (+2 dados de dano e +2 na CD).' },
  { nome: 'Médico', desc: 'Um clérigo, druida ou herbalista com capacidades curativas.',
    ini: 'Uma vez por rodada, gaste 1 PM para curar 1d8+1 PV de uma criatura adjacente.',
    vet: 'Como acima, e você pode gastar 3 PM para curar 3d8+3 PV ou remover uma condição prejudicial.',
    mes: 'Como acima, e você também pode gastar 5 PM para curar 6d8+6 PV.' },
  { nome: 'Perseguidor', desc: 'Um caçador, animal farejador ou especialista em localizar alvos.',
    ini: '+2 em Percepção e Sobrevivência.', vet: 'Você pode usar Sentidos Aguçados.', mes: 'Você pode usar Percepção às Cegas.' },
  { nome: 'Vigilante', desc: 'Um vigia ou animal de guarda, sempre atento aos arredores.',
    ini: '+2 em Percepção e Iniciativa.', vet: 'Você pode usar Esquiva Sobrenatural.', mes: 'Você pode usar Olhos nas Costas.' },
];

// ── MONTARIAS (bestiário completo) ──────────────────────────────────
// { nome, tamanho, fonte, obs?, ini, vet, mes, nota?, deslocMetros? }
window.MONTARIAS = [

  // ─── Tormenta 20 ───
  { nome: 'Cavalo', tamanho: 'Grande', fonte: 'Tormenta 20',
    ini: 'Seu deslocamento muda para 12 m e você recebe uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas seu deslocamento muda para 15 m e você recebe +2 em ataques corpo a corpo.',
    mes: 'Como acima, mas você recebe uma segunda ação de movimento extra por turno (apenas para se deslocar).',
    obs: 'Estas estatísticas também se aplicam a pôneis (tamanho Médio).' },
  { nome: 'Grifo', tamanho: 'Grande', fonte: 'Tormenta 20',
    ini: 'Uma vez por rodada, +1d8 em uma rolagem de dano corpo a corpo (um grifo iniciante é um filhote e não pode ser usado como montaria).',
    vet: 'Como acima, mas pode ser usado como montaria, mudando seu deslocamento para voo 18 m.',
    mes: 'Como acima, mas você recebe uma ação de movimento extra por turno (apenas para se deslocar).' },
  { nome: 'Lobo-das-Cavernas', tamanho: 'Grande', fonte: 'Tormenta 20',
    ini: 'Seu deslocamento muda para 12 m e você recebe uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas seu deslocamento muda para 15 m e, uma vez por rodada, +1d8 em uma rolagem de dano corpo a corpo.',
    mes: 'Como acima; além disso, uma vez por rodada, ao acertar um ataque corpo a corpo, você pode fazer a manobra derrubar como ação livre.',
    obs: 'Também se aplica a lobos comuns (tamanho Médio).' },

  // ─── Ameaças de Arton ───
  { nome: 'Baleote', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Gaste 1 PM para causar 2d6 de eletricidade em uma linha de 9 m (um baleote iniciante é jovem demais para ser montaria).',
    vet: 'Como acima, mas pode ser montaria, mudando seu deslocamento para voo 12 m.',
    mes: 'Como acima, mas voo 15 m e você também pode gastar 4 PM para causar 6d6 de eletricidade em uma linha de 9 m.' },
  { nome: 'Brontotério', tamanho: 'Enorme', fonte: 'Ameaças de Arton',
    ini: 'Seu deslocamento muda para 12 m e +2 em testes de ataque ao fazer investidas.',
    vet: 'Você pode usar Carga de Cavalaria. Se já possui, o bônus de dano em investida aumenta em +1d8.',
    mes: 'Seu deslocamento não é afetado por gelo ou neve.' },
  { nome: 'Búfalo-de-Guerra', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento muda para 9 m e limite de carga +5 espaços. Uma vez por rodada, em investida montada, +1d8 em rolagem de dano corpo a corpo.',
    vet: 'Como acima, mas deslocamento 12 m e ignora terreno difícil.',
    mes: 'Como acima, mas o bônus de dano muda para +2d8 e você recebe uma ação de movimento extra por turno (apenas para se deslocar).' },
  { nome: 'Bulette', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Você recebe deslocamento de escavar 6 m e, uma vez por rodada, +1d6 em rolagem de dano corpo a corpo.',
    vet: 'Como acima, mas o bônus de dano muda para +1d10.',
    mes: 'Como acima, mas escavar 12 m e o bônus de dano muda para +2d8.' },
  { nome: 'Capivara', tamanho: 'Médio', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 9 m, natação 12 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Você pode usar Aparência Inofensiva (se já possui, a CD para resistir aumenta +2).',
    mes: 'Como acima e, uma vez por rodada, +1d6 em uma rolagem de dano corpo a corpo.' },
  { nome: 'Cão de Caça', tamanho: 'Médio ou Pequeno', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 9 m, você pode usar faro e recebe uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas deslocamento 12 m e +2 na Defesa.',
    mes: 'Como acima; além disso, uma vez por rodada, ao acertar um ataque corpo a corpo, manobra derrubar como ação livre.' },
  { nome: 'Cavalo de Namalkah', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 15 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas deslocamento 18 m e +2 em ataques corpo a corpo.',
    mes: 'Como acima, mas uma segunda ação de movimento extra (apenas deslocar) e, uma vez por rodada, +2d6 em rolagem de dano corpo a corpo.',
    obs: 'Raríssimo fora de Namalkah; mesmo por habilidade, exige uma missão que prove o merecimento do personagem.' },
  { nome: 'Cavalo Glacial', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Você recebe deslocamento de natação 12 m e redução de frio 5.',
    vet: 'Uma vez por rodada, ao atacar corpo a corpo, gaste 1 PM; se acertar, +2d6 de frio.',
    mes: 'Redução de frio muda para 10 e você recebe uma ação de movimento extra (apenas para se deslocar).' },
  { nome: 'Cavalo Esqueleto', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: '+2 em Intimidação e na CD de efeitos de medo.',
    mes: 'Uma segunda ação de movimento extra (apenas deslocar) e o alcance dos seus efeitos de medo aumenta um passo.' },
  { nome: 'Cocatriz Imperador', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e você ignora terreno difícil.',
    vet: 'Uma vez por rodada, ao acertar corpo a corpo, a vítima fica lenta (Fort CD For evita).',
    mes: 'Como acima, mas também voo 12 m (ao voar, deve terminar o movimento sobre o chão ou superfície firme).' },
  { nome: 'Corcel de Comando', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    obs: 'Usa Pilotagem no lugar de Cavalgar.',
    ini: 'Deslocamento 12 m e você ignora a penalidade por terreno difícil.',
    vet: 'Como acima, e pode lançar Campo de Força (só o efeito básico); se aprender a magia, custo –1 PM.',
    mes: 'Como acima, e o alcance das suas habilidades baseadas em som (como Músicas de Bardo) aumenta um passo.' },
  { nome: 'Corcel do Deserto', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e ignora terreno difícil natural.',
    vet: 'Uma vez por rodada, gaste 1 PM para causar 2d6 de impacto em uma criatura adjacente.',
    mes: 'Deslocamento 15 m e +5 em testes para resistir a efeitos de clima, calor e frio.' },
  { nome: 'Corcel de Kally', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e, uma vez por rodada, +1d6 em rolagem de dano corpo a corpo.',
    vet: 'Como acima, mas o bônus de dano muda para +1d8 e você recebe deslocamento de voo 12 m.',
    mes: 'Deslocamento (básico e de voo) 18 m e, uma vez por rodada, gaste 2 PM para 2d8 de fogo num cone de 6 m (Ref CD Car ½).' },
  { nome: 'Dai-Kabuto', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: '+2 em testes de agarrar e derrubar e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas você também recebe deslocamento de voo 6 m.',
    mes: 'Como acima, mas o bônus se aplica a todas as manobras e você recebe +2 na Defesa.' },
  { nome: 'Deinonico', tamanho: 'Médio', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e sua margem de ameaça com armas corpo a corpo aumenta +1.',
    vet: '+5 em Atletismo para saltar e uma ação de movimento adicional por turno (apenas para se deslocar).',
    mes: 'Como acima, mas deslocamento 15 m e o bônus na margem de ameaça aumenta para +2.' },
  { nome: 'Dragão', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    obs: 'Dragões jovens de qualquer tipo.',
    ini: 'Deslocamento voo 12 m e, uma vez por rodada, gaste 1 PM para 2d6 da energia do dragão em alcance médio.',
    vet: 'Como acima, e uma ação de movimento extra (apenas deslocar) e pode gastar 2 PM para 4d6.',
    mes: 'Deslocamento 18 m e você pode gastar 5 PM e uma ação de movimento para usar Sopro (de acordo com o dragão).' },
  { nome: 'Dromedário', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e ignora terreno difícil natural em desertos e superfícies similares.',
    vet: '+2 em Percepção e Sobrevivência (dobrado em desertos).',
    mes: 'Uma ação de movimento extra (apenas deslocar) e +5 em testes para resistir a efeitos de clima.' },
  { nome: 'Elefante / Mamute', tamanho: 'Enorme', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e ignora terreno difícil.',
    vet: 'Uma vez por rodada, saque um item ou pegue um objeto solto em alcance de 4,5 m como ação livre.',
    mes: '+5 em manobras para atropelar e, uma vez por rodada, se vencer o atropelo, pague 1 PM para um ataque contra a criatura.' },
  { nome: 'Galhada (macho)', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e +2 em Sobrevivência.',
    vet: 'Seus ataques corpo a corpo são mágicos e, uma vez por turno, +1d8 em rolagem de dano corpo a corpo (dobrado contra mortos-vivos).',
    mes: 'Como acima, mas o bônus de dano muda para +1d10 e você recebe uma ação de movimento extra por turno (apenas para se deslocar).' },
  { nome: 'Galhada Fêmea', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e você pode gastar uma ação padrão e 1 PM para recuperar 1d8+1 PV.',
    vet: 'Como acima, e gastar ação padrão e 3 PM para recuperar 3d8+3 PV ou remover uma condição de doença, fadiga, paralisia ou veneno.',
    mes: 'Como acima, mas uma ação de movimento extra (apenas deslocar) e pode gastar ação padrão e 5 PM para recuperar 6d8+6 PV.' },
  { nome: 'Gorlogg / Gorlogg Alfa', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e, uma vez por rodada, +1d6 em rolagem de dano corpo a corpo.',
    vet: 'Como acima, mas o bônus de dano corpo a corpo muda para +1d10.',
    mes: 'Deslocamento 15 m e o bônus de dano corpo a corpo muda para +2d8.' },
  { nome: 'Hienodonte', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Você pode usar Oportunismo. Se já possui, o custo para usá-lo diminui –1 PM.',
    mes: 'Ao acertar um ataque corpo a corpo, manobra derrubar como ação livre.' },
  { nome: 'Hippossauro', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e +2 em Diplomacia (macho) ou Furtividade (fêmea).',
    vet: 'Como acima, mas deslocamento 15 m e, uma vez por rodada, +1d8 em rolagem de dano corpo a corpo.',
    mes: 'Como acima, mas o bônus na perícia muda para +4 e você recebe uma ação de movimento extra (apenas para se deslocar).' },
  { nome: 'Leão', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e, uma vez por rodada, +1d6 em rolagens de dano corpo a corpo.',
    vet: 'Como acima, mas em investida o bônus de dano corpo a corpo dobra.',
    mes: 'Deslocamento 15 m e o bônus de dano corpo a corpo muda para +1d10.' },
  { nome: 'Pantera', tamanho: '— (parceiro especial: assassino)', fonte: 'Ameaças de Arton',
    ini: 'Uma vez por rodada, ao causar dano com ataque corpo a corpo, você pode deixar o alvo sangrando.',
    vet: 'A CD dos testes para remover um sangramento que você provoca aumenta +2.',
    mes: 'Os sangramentos que você provoca exigem dois sucessos para serem removidos.' },
  { nome: 'Platan', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento de natação 9 m e uma ação de movimento extra (apenas para se deslocar).',
    vet: 'Uma vez por rodada, como ação livre, gaste 1 PM para 2d6 de impacto em alcance curto.',
    mes: 'Como acima, mas natação 15 m e pode gastar 4 PM para 6d6 de impacto em alcance curto.' },
  { nome: 'Rinoceronte', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e +2 em testes de ataque ao fazer investidas.',
    vet: 'Você pode usar Carga de Cavalaria. Se já possui, o bônus de dano em investida aumenta +1d8.',
    mes: 'Ao fazer uma investida, você ignora 10 pontos de redução de dano do alvo.' },
  { nome: 'Rinoceronte Lanoso', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e redução de frio 5.',
    vet: '+2 na Defesa e uma ação de movimento extra por turno (apenas para se deslocar).',
    mes: 'O bônus na Defesa muda para +4.' },
  { nome: 'Sapo Atroz', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Uma ação de movimento extra (apenas deslocar), natação 9 m e +5 em Atletismo para saltar.',
    vet: '+2 em testes para derrubar e desarmar.',
    mes: 'O bônus em Atletismo sobe para +10 e, uma vez por rodada, gaste 1 PM para desarmar ou derrubar um alvo a até 3 m.' },
  { nome: 'Selako', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento de natação 15 m e, uma vez por rodada, +1d6 em rolagem de dano corpo a corpo.',
    vet: 'Como acima, mas o bônus de dano aumenta para +2d6.',
    mes: 'Natação 18 m e, ao usar o bônus de dano do selako contra uma criatura, ela fica sangrando.' },
  { nome: 'Tatu-Montanha', tamanho: 'Enorme', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento de natação 9 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: '+1 na Defesa e redução de ácido 5.',
    mes: 'O bônus na Defesa muda para +2 e a redução de ácido para 10.' },
  { nome: 'Tigre', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e +2 em Iniciativa.',
    vet: 'Na primeira rodada de combate, +2 em testes de ataque e rolagens de dano com armas.',
    mes: 'Deslocamento 15 m e uma ação de movimento extra por turno (apenas para se deslocar).' },
  { nome: 'Trobo', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 9 m, uma ação de movimento extra (apenas deslocar) e +1 em testes de resistência.',
    vet: 'Como acima, mas deslocamento 12 m e o bônus em resistência muda para +2.',
    mes: 'Como acima, mas o bônus em resistência muda para +5.' },
  { nome: 'Troll', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e, uma vez por rodada, +1d8 em rolagem de dano corpo a corpo.',
    vet: 'O bônus de dano sobe para +1d10 e +2 em testes para agarrar e derrubar.',
    mes: 'O bônus de dano sobe para +2d8 e o bônus para agarrar e derrubar sobe para +5.' },
  { nome: 'Tumarkhân', tamanho: 'Enorme', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e limite de carga +5 espaços.',
    vet: 'Como acima, mas uma ação de movimento extra (apenas deslocar) e, uma vez por rodada, +1d8 em rolagem de dano corpo a corpo.',
    mes: 'Como acima, mas carga +10 espaços e, em teste de Força ou perícia baseada em Força, gaste 2 PM para rolar dois dados e usar o melhor.' },
  { nome: 'Tuntram', tamanho: 'Enorme', fonte: 'Ameaças de Arton',
    ini: '+2 em testes de ataque para derrubar e empurrar.',
    vet: 'Cobertura leve contra ataques à distância e uma ação de movimento extra (apenas deslocar).',
    mes: '+2 em ataque para atropelar; nessa manobra o oponente não tem a opção de sair do caminho (mas resiste com teste oposto). Ao atropelar, gaste 1 PM para um ataque extra.' },
  { nome: 'Unicórnio', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas deslocamento 15 m e, uma vez por cena, remova uma condição negativa ou maldição de uma criatura adjacente.',
    mes: 'Cada dado dos seus efeitos mágicos de cura aumenta um passo (máx. d12).',
    obs: 'Apenas devotos de Allihanna, Lena ou Marah, ou com ao menos dois poderes de Virtude Paladinesca, podem cavalgar um unicórnio.' },
  { nome: 'Urso das Cavernas', tamanho: 'Enorme', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e redução de dano 2.',
    vet: 'Uma vez por rodada, ao acertar corpo a corpo, manobra agarrar como ação livre (não ocupa a mão; um inimigo agarrado por vez).',
    mes: 'A redução de dano muda para 5.' },
  { nome: 'Urso das Neves', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e redução de frio 5.',
    vet: 'Deslocamento de natação 12 m e a redução de frio sobe para 10.',
    mes: 'Como acima, mas a redução de frio sobe para 20.' },
  { nome: 'Urso Negro', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 12 m e, uma vez por rodada, +1d6 em rolagem de dano corpo a corpo.',
    vet: 'Uma vez por rodada, ao acertar corpo a corpo, manobra agarrar como ação livre (não ocupa a mão; um inimigo por vez).',
    mes: 'O bônus de dano corpo a corpo muda para +1d10.' },
  { nome: 'Urso Panda', tamanho: 'Médio', fonte: 'Ameaças de Arton',
    ini: 'Deslocamento 9 m, +2 em Diplomacia e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Você pode usar Rolamento Defensivo. Se já possui, o custo para usá-lo diminui –1 PM.',
    mes: 'Você pode usar Aparência Inofensiva. Se já possui, a CD para resistir aumenta +2.' },
  { nome: 'Warg', tamanho: 'Grande', fonte: 'Ameaças de Arton',
    obs: 'Não causa penalidades em Furtividade por seu tamanho.',
    ini: 'Deslocamento 12 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, e +2 em Furtividade e pode usar Ataque Furtivo +2d6 (cumulativo se já tiver).',
    mes: 'Como acima; além disso, uma vez por rodada, ao acertar corpo a corpo, manobra derrubar como ação livre.' },

  // ─── Deuses & Heróis ───
  { nome: 'Companheiro Dragão', tamanho: 'Grande (especial)', fonte: 'Deuses & Heróis',
    obs: 'Parceiro do Tirano do Terceiro, com duas opções.',
    ini: 'Uma vez por rodada, como ação livre, gaste 1 PM para 2d6 de ácido, eletricidade, fogo ou frio (do dragão) em alcance curto.',
    vet: 'Como acima, mudando seu deslocamento para voo 18 m.',
    mes: 'Como acima, mas uma ação de movimento extra (apenas deslocar); o companheiro vira dragão adulto (Enorme), ganha Aura Aterradora (CD Car) e Metamorfose Dracônica.',
    nota: 'Opção alternativa — Iniciante: voo 12 m e, uma vez por rodada, gaste 1 PM para 2d6 da energia do dragão em alcance médio. Veterano: ação de movimento extra (apenas deslocar) e pode gastar 2 PM para 4d6. Mestre: deslocamento 18 m e gaste 5 PM + ação de movimento para usar Sopro; o companheiro vira dragão adulto (Enorme) com Aura Aterradora e Metamorfose Dracônica.' },
  { nome: 'Gamo Celestial', tamanho: 'Grande', fonte: 'Deuses & Heróis',
    ini: 'Deslocamento 12 m e você ignora terreno difícil.',
    vet: 'Você ganha deslocamento de voo 12 m.',
    mes: 'Gaste ação completa e 10 PM para levar você e o gamo ao Plano Etéreo (efeito básico de Forma Etérea, duração sustentada; acaba se desmontar).' },
  { nome: 'Javali Doherita', tamanho: 'Grande', fonte: 'Deuses & Heróis',
    ini: 'Deslocamento 9 m e, em investida montada, +1d8 de dano.',
    vet: 'Uma ação de movimento extra (apenas deslocar) e o bônus de dano em investida montada sobe para +2d6.',
    mes: 'Deslocamento 12 m e, em investida montada, você ignora 10 pontos de redução de dano do alvo.' },
  { nome: 'Javali Doherita (variante)', tamanho: 'Grande', fonte: 'Revista Tormenta',
    ini: 'Você pode usar Carga de Cavalaria. Se já possui, o bônus de dano dele aumenta +1d8.',
    vet: 'Deslocamento 9 m e o bônus de dano de Carga de Cavalaria aumenta +1d8.',
    mes: 'Deslocamento 12 m e, em investida, ignora 10 pontos de redução de dano do alvo.',
    obs: 'Apenas doheritas da Guilda dos Provedores ou da Guilda dos Guerreiros podem montar estes animais.' },
  { nome: 'Pégaso', tamanho: 'Grande', fonte: 'Deuses & Heróis',
    obs: 'Aceita apenas devotos de deuses que possuem paladinos.',
    ini: '+2 em Intuição e deslocamento 15 m (um pégaso iniciante ainda não voa com cavaleiro).',
    vet: 'Como acima, mas deslocamento voo 15 m e +2 em Vontade.',
    mes: 'Uma ação de movimento extra por turno (apenas para se deslocar) e +2 em testes de ataque.' },
  { nome: 'Pégaso de Khalmyr', tamanho: 'Grande', fonte: 'Deuses & Heróis',
    obs: 'Parceiro mestre; aceita apenas quem julgue digno ou devotos de Khalmyr.',
    ini: '—', vet: '—',
    mes: 'Deslocamento 18 m (voo 36 m) e uma ação de movimento extra por turno (apenas para se deslocar). Pode lançar Círculo da Justiça; se aprender a magia, custo –1 PM.' },

  // ─── Jornada Heróica ───
  { nome: 'Gárgula do Templo Hippionte', tamanho: '', fonte: 'Jornada Heróica',
    ini: 'Deslocamento voo 12 m e uma ação de movimento extra por turno (apenas para se deslocar).',
    vet: 'Como acima, mas voo 15 m e redução de dano 2.',
    mes: 'Como acima, mas a RD muda para 5.' },
  { nome: 'Grifo dos Montes Nublados', tamanho: 'Grande', fonte: 'Jornada Heróica',
    ini: '+1 na Defesa e, uma vez por rodada, +1d6 em rolagem de dano corpo a corpo (filhote; ainda não é montaria).',
    vet: 'Como acima, mas pode ser montaria, mudando seu deslocamento para voo 18 m.',
    mes: 'Como acima, mas +2 na Defesa, o bônus de dano muda para +1d8 e uma ação de movimento extra (apenas deslocar).' },
  { nome: 'Serpe do Bosque dos Centauros', tamanho: '', fonte: 'Jornada Heróica',
    ini: 'Uma vez por rodada, ao causar dano com um ataque, o alvo perde 1d12 PV por veneno (filhote; ainda não é montaria).',
    vet: 'Como acima, mas pode ser montaria, mudando seu deslocamento para voo 18 m.',
    mes: 'Como acima, e uma vez por rodada gaste 5 PM para um ataque corpo a corpo extra.' },

  // ─── Deuses de Arton ───
  { nome: 'Dragonete', tamanho: '— (parceiro arcano)', fonte: 'Deuses de Arton',
    obs: 'Um dragonete parceiro fornece os benefícios a seguir.',
    ini: 'Diminui em –1 PM o custo das suas magias de encantamento e ilusão.',
    vet: 'Aumenta o alcance das suas magias de encantamento e ilusão em um passo (de curto para médio e de médio para longo).',
    mes: 'A redução de custo em magias de encantamento e ilusão se torna cumulativa com outras reduções e você fica sempre sob o efeito básico da magia Visão Mística.' },

];

// ── REGRAS (parceiros, combate montado, variantes) ──────────────────
window.ANIMAIS_REGRAS = [
  { titulo: '🤝 Como funcionam os parceiros',
    texto: `Parceiros não são NPCs completos: não têm turno nem realizam ações. Em vez disso, cada parceiro ajuda um personagem com um bônus, que depende do tipo e do nível de poder (iniciante, veterano ou mestre — classificação abstrata, definida pelo mestre).\nCada parceiro ajuda só um personagem por vez. No início do seu turno você pode gastar uma ação de movimento para passá-lo a outro personagem em alcance curto até o fim da cena (com animais, precisa ser treinado em Adestramento).\nLimite: até o 4º nível, 1 parceiro; do 5º ao 16º, até 2; do 17º em diante, até 3.\nParceiros não podem ser alvos de ações hostis, mas em situações dramáticas o mestre pode decidir que algo acontece com eles.` },
  { titulo: '🐎 Montarias e combate montado',
    texto: `Montar ou desmontar é uma ação de movimento (e você precisa desmontar para passar a montaria a um aliado).\nMontado, gaste uma ação de movimento e faça Cavalgar (CD 10) por turno para guiar a montaria: passou, recebe os benefícios; falhou, perde a ação de movimento; falhou por 5+, cai e sofre 1d6. Treinado em Cavalgar, você recebe os bônus automaticamente, sem gastar a ação nem testar.\nAo sofrer dano, faça Cavalgar (CD igual ao dano) ou cai e sofre 1d6 (o poder Ginete dispensa).\nVocê só pode montar uma montaria maior que você; montado, usa o tamanho dela para espaço ocupado e Furtividade.\nO balanço dá –2 em ataques à distância e conta como condição ruim para magias (o poder Ginete anula).\nMontarias compradas são sempre parceiros iniciantes; algumas são raras (achar um grifo à venda é quase impossível).` },
  { titulo: '🎽 Montarias e itens vestidos',
    texto: `A menos que sua descrição diga o contrário, uma montaria pode ser equipada com dois itens vestidos (como sela, alforje, ou os itens de montaria desta lista).` },
  { titulo: '💔 Variante: parceiros vulneráveis',
    texto: `Com esta variante, parceiros podem se ferir e morrer. Sempre que o personagem sofre dano, role um dado por parceiro: num resultado "1", o parceiro fica ferido (sem efeito em jogo). Se rolar outro "1" para um parceiro já ferido, ele morre. O dado depende do poder: d4 (iniciante), d6 (veterano), d8 (mestre).\nRecomendada apenas para parceiros circunstanciais, não os recebidos por habilidades de classe.` },
];
