// ════════════════════════════════════════════════════════════════════
//  COMPLICACOES-DATA.JS — as Complicações do Heróis de Arton (Cap. 4)
//  Localização: /grifos-alados/js/complicacoes-data.js
//
//  As COMPLICAÇÕES GERAIS (p. 282–284, 32) que QUALQUER personagem pode
//  escolher, E as DE CLASSE (p. 284–287, 22 em 14 classes, campo `classe`).
//  Escolhe-se UMA só, na criação — e por ela vem um poder geral extra.
//  Lidas do PDF (Heróis de Arton) palavra por palavra; os hífens de
//  quebra de linha da justificação foram removidos. O † marca as
//  COMPORTAMENTAIS: se violadas, você perde todos os PM até o dia seguinte.
//  (Complicação de classe só vale se metade dos seus níveis forem nela.)
//
//  Consumido pelo seletor do cartão ⚠ Complicações (js/ficha.js), que
//  agrupa por Gerais + uma seção por classe e insere a escolhida na caixa.
//  Carregado nas duas páginas.
// ════════════════════════════════════════════════════════════════════
(function () {
  'use strict';
  window.GA_COMPLICACOES = [
    { id: 'amaldicoado', nome: 'Amaldiçoado', comportamental: false,
      texto: 'Você foi amaldiçoado por uma entidade poderosa, como um lich, um nobre feérico, um Lorde da Tormenta ou mesmo um deus. No início de cada cena envolvendo qualquer tipo de risco ou perigo, role 1d6. Em um resultado 1, você não consegue usar seus pontos de mana nessa cena.' },
    { id: 'apetitoso', nome: 'Apetitoso', comportamental: false,
      texto: 'Por algum motivo, feras salivam ao farejá-lo. Animais e monstros recebem +5 em testes de ataque e rolagens de dano contra você.' },
    { id: 'assombrado', nome: 'Assombrado', comportamental: false,
      texto: 'Você é assombrado por um ser desagradável, como o fantasma de um ancestral, uma fada travessa ou um diabrete zombeteiro. Ele conta no seu limite de parceiros, mas não fornece nenhum benefício. Além disso, no início de cada cena envolvendo qualquer tipo de risco ou perigo, role um dado. Em um resultado ímpar, você fica alquebrado até o fim da cena.' },
    { id: 'cabeca-quente', nome: 'Cabeça Quente', comportamental: false,
      texto: 'Sempre que você sofre dano, seu próximo turno deve ser dedicado a atacar a fonte do dano. Se não puder atacá-la — por exemplo, se a fonte do dano for um inimigo fora do seu alcance ou algo que por definição não possa ser atacado, como um raio proveniente de uma tempestade — você deve gastar sua próxima ação de movimento esbravejando contra o ar.' },
    { id: 'caolho', nome: 'Caolho', comportamental: false,
      texto: 'Você não tem um dos olhos. Você sofre –2 em Iniciativa, Percepção, Pontaria e Reflexos e fica automaticamente flanqueado por dois ou mais oponentes em corpo a corpo.' },
    { id: 'chato', nome: 'Chato', comportamental: false,
      texto: 'Sempre que você sai de uma aldeia, uma festa acontece. Você sofre –5 em Diplomacia e a atitude inicial de NPCs em relação a você é uma categoria pior.' },
    { id: 'combalido', nome: 'Combalido', comportamental: false,
      texto: 'Por alguma razão, natural ou sobrenatural, sua saúde é frágil. Você sofre –5 em Fortitude e recebe –1 PV por nível de personagem.' },
    { id: 'covarde', nome: 'Covarde', comportamental: false,
      texto: 'Seu lema é "aquele que foge hoje vive para lutar amanhã". Claro, se puder evitar a luta de amanhã também, melhor ainda! Você sofre –5 em testes de resistência contra efeitos de medo e, no início de cada cena envolvendo qualquer tipo de risco ou perigo, deve rolar um dado. Em um resultado ímpar, você fica abalado (mesmo que seja imune a isso).' },
    { id: 'cria-de-nimb', nome: 'Cria de Nimb', comportamental: false,
      texto: 'Você tem um parafuso a menos (talvez literalmente, se for um golem). Você sofre –5 em testes de perícias baseadas em Carisma. Além disso, no início de cada cena de ação, role 1d6. Com um resultado 1, você fica confuso (mesmo que seja imune a essa condição). Você não pode escolher esta complicação se for devoto de Nimb ou se, por algum outro motivo, seguir suas Obrigações & Restrições.' },
    { id: 'criado-na-cidade', nome: 'Criado na Cidade', comportamental: false,
      texto: 'Você não se dá bem no mato. Você sofre –5 em Sobrevivência e, quando descansa nos ermos, sua recuperação é uma categoria pior (se já era ruim, você recupera apenas 1 PV e 1 PM, independentemente do seu nível).' },
    { id: 'crise-de-fe', nome: 'Crise de Fé', comportamental: true,
      texto: 'Você segue um dos deuses do Panteão, mas no fundo se pergunta se isso é o certo a fazer. Você sofre –2 em Vontade e segue as Obrigações & Restrições de um deus, mas não recebe nenhum poder concedido por isso nem conta como devoto dessa divindade para cumprir pré-requisitos. Você não pode ser devoto de outro deus.' },
    { id: 'desprotegido', nome: 'Desprotegido', comportamental: false,
      texto: 'Você nunca aprendeu a se defender. Você sofre –2 na Defesa e em testes de resistência.' },
    { id: 'distraido', nome: 'Distraído', comportamental: false,
      texto: 'Você é muito desligado e... Hein? Do que estávamos falando? Você sofre –5 em Iniciativa e Percepção.' },
    { id: 'emotivo', nome: 'Emotivo', comportamental: false,
      texto: 'Fadado a sofrer, você não se beneficia de efeitos que forneçam bônus numéricos (em atributos, testes, Defesa etc.) usados por outros personagens.' },
    { id: 'expurgo-de-wynna', nome: 'Expurgo de Wynna', comportamental: false,
      texto: 'Algo em você não agrada à Deusa da Magia. Você sofre –5 em testes de resistência contra efeitos mágicos.' },
    { id: 'fracote', nome: 'Fracote', comportamental: false,
      texto: 'Você cresceu dentro dos muros de um palácio ou enfurnado na torre de um mago e nunca praticou atividades físicas. Você está permanentemente fraco (mesmo que seja imune a essa condição).' },
    { id: 'hedonista', nome: 'Hedonista', comportamental: false,
      texto: 'Você está acostumado a viver no luxo e não aceita nada abaixo disso. Em condições luxuosas, sua recuperação de PV e PM é igual ao seu nível. Em condições confortáveis, sua recuperação é igual à metade do seu nível. Em condições normais ou ruins, você recupera apenas 1 PV e 1 PM, independentemente do seu nível.' },
    { id: 'impio', nome: 'Ímpio', comportamental: true,
      texto: 'Você odeia os deuses — e eles sabem disso. Você sofre –5 em testes de resistência contra magias divinas e não pode se beneficiar de efeitos dessas magias.' },
    { id: 'impulsivo', nome: 'Impulsivo', comportamental: false,
      texto: 'Você age primeiro e pensa depois (ou nunca). Você sofre –5 em Furtividade e Investigação, e não pode fazer as ações atrasar e preparar.' },
    { id: 'inculto', nome: 'Inculto', comportamental: false,
      texto: 'Você não teve acesso à educação. Você é analfabeto e recebe duas perícias treinadas a menos (isso pode reduzir as perícias que você pode escolher a zero, mas não afeta as perícias fixas de sua classe).' },
    { id: 'indolente', nome: 'Indolente', comportamental: false,
      texto: 'Você é apático e preguiçoso. Você sofre –5 em Reflexos e –3m em seu deslocamento.' },
    { id: 'ingenuo', nome: 'Ingênuo', comportamental: false,
      texto: 'Não há maldade em seu coração. Você sofre –5 em Enganação, Intuição, Investigação e Ladinagem.' },
    { id: 'maneta', nome: 'Maneta', comportamental: false,
      texto: 'Você não tem uma das mãos. Você só pode empunhar um item (e, obviamente, não pode usar armas de duas mãos).' },
    { id: 'marcado-pelo-passado', nome: 'Marcado pelo Passado', comportamental: false,
      texto: 'Um evento em seu passado o deixou taciturno e sombrio. Você sofre –5 em Diplomacia e recebe –1 PM por nível de personagem.' },
    { id: 'matugo', nome: 'Matugo', comportamental: false,
      texto: 'Você não se dá bem em cidades. Você fica alquebrado em ambientes urbanos e, quando descansa nesses ambientes, sua recuperação é uma categoria pior (se já era ruim, você recupera apenas 1 PV e 1 PM, independentemente do seu nível).' },
    { id: 'miope', nome: 'Míope', comportamental: false,
      texto: 'Você tem dificuldade de enxergar objetos distantes. Como alternativa, acha covardia atacar de longe e nunca treinou com armas de ataque à distância. Você sofre –5 em Percepção e Pontaria, e fica desprevenido contra efeitos que se originem além de alcance curto.' },
    { id: 'mouco', nome: 'Mouco', comportamental: false,
      texto: 'Sua audição é ruim. Você sofre –2 em Iniciativa, Intuição, Percepção e Reflexos.' },
    { id: 'paladar-infantil', nome: 'Paladar Infantil', comportamental: false,
      texto: 'Você é chato para comer. Não se beneficia de itens da categoria alimentação, nem de poções. Além disso, sofre –2 em testes de perícias baseadas em Carisma durante situações sociais baseadas em refeições, como um banquete no palácio ou uma noite na taverna.' },
    { id: 'paranoico', nome: 'Paranoico', comportamental: false,
      texto: 'Você não confia em ninguém, nem em seus aliados. Você precisa passar em um teste de Vontade (CD 20 + seu nível) para aceitar qualquer ajuda — até mesmo cura! Se falhar no teste, recusa a ajuda e, se for ajudado mesmo assim (contra sua vontade), fica alquebrado até o fim da cena. Além disso, você não dorme direito: sua condição de descanso é sempre uma categoria pior do que seria pelas circunstâncias (se já era ruim, você recupera apenas 1 PV e 1 PM, independentemente do seu nível).' },
    { id: 'temeroso', nome: 'Temeroso', comportamental: false,
      texto: 'Você tem medo de se machucar. Como alternativa, treinou apenas com armas de ataque à distância e não sabe o que fazer quando as coisas ficam mais "pessoais". Você sofre –5 em Luta e, enquanto estiver adjacente a um inimigo, fica abalado.' },
    { id: 'tolo', nome: 'Tolo', comportamental: false,
      texto: 'É fácil enganá-lo e manipulá-lo. Você sofre –5 em Intuição e Vontade.' },
    { id: 'vagaroso', nome: 'Vagaroso', comportamental: false,
      texto: '"Devagar e sempre vence a corrida" é o que você diz. E, se não vencer, pelo menos você não se cansou. Você está permanentemente sob efeito da condição lento (todas as suas formas de deslocamento são reduzidas à metade e você não pode correr ou fazer investidas).' },

    // ── COMPLICAÇÕES DE CLASSE (Heróis de Arton, p. 284–287) ──────────
    //  Só podem ser escolhidas por personagens da classe listada (e, se você
    //  for multiclasse, só valem se pelo menos metade dos seus níveis forem
    //  nessa classe — Heróis de Arton, p. 282). O `classe` diz de quem é.
    { id: 'arcanista-de-rotina', nome: 'Arcanista de Rotina', classe: 'Arcanista', comportamental: false,
      texto: 'Você não está acostumado a lançar magias sob pressão. Se estiver em alcance curto de qualquer ameaça, é considerado sob condição ruim para lançar magias. Se já estiver sob efeito de uma condição ruim ou terrível para conjurar, a CD do teste aumenta em +2.' },
    { id: 'foco-exigente', nome: 'Foco Exigente', classe: 'Arcanista', comportamental: false,
      texto: 'Seu foco o pune quando você falha. Sempre que uma criatura passa em um teste de resistência contra uma magia sua, você perde 1 PV por PM gasto na magia. Pré-requisito: Bruxo.' },
    { id: 'linhagem-prepotente', nome: 'Linhagem Prepotente', classe: 'Arcanista', comportamental: false,
      texto: 'Sua magia inata rejeita auxílio de cacarecos. Você não pode usar catalisadores e itens esotéricos mundanos. Você ainda pode usar itens esotéricos mágicos, já que esses são verdadeiramente imbuídos de magia — como você! Pré-requisito: Feiticeiro.' },
    { id: 'mente-cansada', nome: 'Mente Cansada', classe: 'Arcanista', comportamental: false,
      texto: 'Quanto mais magias você aprende, mais difícil fica lembrar de todas! Para cada círculo de magia que você pode lançar, o total de magias que pode memorizar diminui em 1. Pré-requisito: Mago.' },
    { id: 'de-peito-aberto', nome: 'De Peito Aberto', classe: 'Bárbaro', comportamental: true,
      texto: 'Você tem tatuagens tribais que quer exibir, confia na sua resistência natural ou só acha seu corpo lindo. Seja qual for o motivo, você não pode vestir armaduras e seu limite de itens vestidos diminui em dois.' },
    { id: 'totem-gigante', nome: 'Totem Gigante', classe: 'Bárbaro', comportamental: true,
      texto: 'Você interpreta a orientação de levar o totem de sua tribo consigo muito literalmente. Você carrega uma grande coluna de madeira esculpida que jamais pode abandonar. A coluna ocupa 10 espaços e impõe penalidade de armadura –5.' },
    { id: 'estrelismo', nome: 'Estrelismo', classe: 'Bardo', comportamental: false,
      texto: 'Você é lindo, talentoso e… extremamente egocêntrico. Você sofre –5 em testes de Diplomacia e Intuição. Além disso, sempre que falha em um teste de Atuação, fica alquebrado até o fim da cena.' },
    { id: 'falastrao', nome: 'Falastrão', classe: 'Bardo', comportamental: true,
      texto: 'Você está sempre dando suas palestrinhas. Você não consegue ficar quieto e deve ser sempre o primeiro a falar, por mais inconveniente que isso possa ser. Você sofre –5 em testes de Furtividade e Nobreza e pode se envolver em diversos problemas, especialmente se estiver diante de certas autoridades ou tentando passar discretamente por alguém.' },
    { id: 'coragem-liquida', nome: 'Coragem Líquida', classe: 'Bucaneiro', comportamental: false,
      texto: 'No início do seu turno, em cenas envolvendo qualquer risco ou perigo, role 1d4. Em um resultado 1, você precisa gastar uma ação de movimento para tomar um gole de bebida. Se não puder, fica pasmo pela rodada (mesmo se for imune a isso). Hic!' },
    { id: 'esbanjador', nome: 'Esbanjador', classe: 'Bucaneiro', comportamental: false,
      texto: 'Você tem certas necessidades, que alguns chamam de "luxo" — mas, para você, são o motivo de viver! Para subir de nível, além de acumular XP suficiente, você deve "torrar" tibares em festas e frivolidades, em um valor igual a 20% da diferença do dinheiro inicial do nível que vai alcançar para o nível atual (por exemplo, T$ 200 para subir para o 5º nível).' },
    { id: 'limitado-a-criatura', nome: 'Limitado a (Criatura)', classe: 'Caçador', comportamental: false,
      texto: 'Você se especializou em lutar contra um inimigo específico — e só. Escolha um tipo de criatura do poder Inimigo de (Criatura). O custo base para usar Marca da Presa contra criaturas de outros tipos muda para 3 PM.' },
    { id: 'superprotetor', nome: 'Superprotetor', classe: 'Cavaleiro', comportamental: false,
      texto: 'Você se preocupa com o bem-estar do seu grupo e faz questão de ficar perto de seus companheiros — mesmo que isso não seja a melhor estratégia! Durante qualquer cena envolvendo qualquer tipo de risco ou perigo, você sempre deve terminar seu turno adjacente a um aliado. Se não fizer isso, fica alquebrado e sofre –2 em seus testes por 1 rodada.' },
    { id: 'divindade-exigente', nome: 'Divindade Exigente', classe: 'Clérigo', comportamental: false,
      texto: 'Você serve a sua divindade com afinco, mas às vezes ela quer sua atenção exclusiva. Sempre que lançar uma magia divina, role 1d6. Em um resultado 1, você fica frustrado (essa condição é cumulativa).' },
    { id: 'preparacao-liturgica', nome: 'Preparação Litúrgica', classe: 'Clérigo', comportamental: false,
      texto: 'Você só pode lançar magias preparadas; suas outras magias não podem ser lançadas, mesmo que você tenha pontos de mana para isso. Para preparar magias, você precisa gastar uma hora de seu dia orando, meditando, entoando mantras ou fazendo qualquer outro tipo de ritual litúrgico. Ao fazer isso, você escolhe metade das magias que conhece (por exemplo, se conhece 5 magias, escolhe 2) e só pode lançar as magias escolhidas. Caso não possa se preparar, não pode trocar as magias escolhidas no dia anterior.' },
    { id: 'tosco', nome: 'Tosco', classe: 'Druida', comportamental: true,
      texto: 'Você não se dá bem com objetos civilizados. Você não pode usar itens superiores.' },
    { id: 'precavido', nome: 'Precavido', classe: 'Guerreiro', comportamental: false,
      texto: 'Enquanto não conhece as capacidades do inimigo, você prefere lutar de maneira cautelosa. Tanta preocupação causa –2 em testes de ataque e resistência. A partir da segunda rodada de combate, você pode se livrar dessa penalidade até o fim da cena gastando uma ação de movimento e passando em um teste de Guerra (CD 15 + ND do inimigo mais poderoso na cena).' },
    { id: 'trabalhador-ocupado', nome: 'Trabalhador Ocupado', classe: 'Inventor', comportamental: false,
      texto: 'Você está tão ocupado trabalhando para os outros que não tem tempo de fazer seus próprios projetos! Você não recebe a habilidade Protótipo e, quando recebe a habilidade Fabricar Item Superior, não recebe um item gratuito.' },
    { id: 'honra-de-ladrao', nome: 'Honra de Ladrão', classe: 'Ladino', comportamental: true,
      texto: 'Você pode ser um bandido e salafrário, mas tem seus princípios. Você sempre cumpre suas promessas e nunca rouba ou tira vantagem de pessoas com menos recursos que você e seu grupo. O mestre tem a palavra final sobre o que é "tirar vantagem" de alguém.' },
    { id: 'firula', nome: 'Firula', classe: 'Lutador', comportamental: true,
      texto: 'Na primeira rodada de cada combate, você deve gastar uma ação padrão apresentando-se, fazendo uma coreografia ou informando seu peso, altura e cartel.' },
    { id: 'filantropo', nome: 'Filantropo', classe: 'Nobre', comportamental: false,
      texto: 'Você doa parte de sua riqueza para fazer o bem. Você não recebe a habilidade Espólio e, quando usa sua habilidade Riqueza, recebe apenas metade do valor normal.' },
    { id: 'mimado', nome: 'Mimado', classe: 'Nobre', comportamental: false,
      texto: 'Bajulado desde criança, você fica desconcertado sempre que percebe que não é tão bom quanto lhe diziam. Na primeira vez em cada cena que falha em um teste de perícia, você perde 1 PM por patamar. Se já estiver sem PM, você fica frustrado por 1 rodada.' },
    { id: 'certinho', nome: 'Certinho', classe: 'Paladino', comportamental: false,
      texto: 'Você faz tudo do jeito correto e fica desconfortável quando um de seus companheiros não age dessa forma. Sempre que um aliado fizer algo que violaria seu Código do Herói, isso conta como uma violação sua — a menos que você não note, o que exige dele um teste de Enganação ou Furtividade contra a sua Percepção ou Intuição (o que for maior).' },
  ];

  //  ── COMPLICAÇÕES DE IDADE ("O Peso da Idade", Heróis de Arton, p. 290) ──
  //  Personagens adultos ou mais velhos escolhem uma por faixa etária:
  //  adulto 1 (opcional), maduro 2, velho 3, ancião 4. Contam como
  //  complicações normais e os efeitos SE ACUMULAM. São 19.
  window.GA_COMPLICACOES_IDADE = [
    { id: 'abatido', nome: 'Abatido',
      texto: 'Seu vigor se foi. Você recebe –2 PV por nível.' },
    { id: 'catarata', nome: 'Catarata',
      texto: 'Seus olhos já não são os mesmos. Você sofre –5 em Percepção e Pontaria.' },
    { id: 'dedos-tremulos', nome: 'Dedos Trêmulos',
      texto: 'Você sofre –2 em Luta e Pontaria. Além disso, quando usa um item que esteja empunhando, role 1d4. Em um resultado 1, você derruba esse item.' },
    { id: 'definhamento', nome: 'Definhamento',
      texto: 'A idade roubou seu peso, deixando-o um fiapo do que era antes. Você sofre –5 em Fortitude e em testes de manobras de combate.' },
    { id: 'desatento', nome: 'Desatento',
      texto: 'Você já não é mais tão atento quanto outrora. Na primeira rodada de qualquer cena de ação, role um dado. Em um resultado ímpar, você fica surpreendido (mesmo que um efeito possa evitar isso).' },
    { id: 'devagar-jovem', nome: '"Devagar, Jovem!"',
      texto: 'Você já não anda no mesmo ritmo que antes. Seu deslocamento diminui em –3m e você não pode correr ou fazer investidas.' },
    { id: 'gota', nome: 'Gota',
      texto: 'Sempre que faz um teste de Destreza ou de perícias baseadas nesse atributo você perde 1d6 pontos de vida. Você só pode recuperar esses PV com descanso.' },
    { id: 'juntas-duras', nome: 'Juntas Duras',
      texto: 'Suas articulações doem. Você sofre –5 em testes de Acrobacia e Reflexos.' },
    { id: 'melancolico', nome: 'Melancólico',
      texto: 'Você já não tem mais tanta motivação para realizar grandes façanhas. Você perde 1 PM por nível.' },
    { id: 'memorias-tristes', nome: 'Memórias Tristes',
      texto: 'Você passou por um trauma, como a perda de um ente querido ou a culpa por um erro que cometeu e pelo qual nunca se perdoou. Sempre que rola um resultado 1 natural em qualquer teste, você fica pasmo por 1 rodada e frustrado até o fim do dia (cumulativo).' },
    { id: 'no-meu-tempo', nome: '"No Meu Tempo..."',
      texto: 'Você se prende a visões idealizadas de um passado que nunca existiu e se torna presa fácil para manipulação. Você sofre –5 em Intuição e Vontade.' },
    { id: 'pulmao-ruim', nome: 'Pulmão Ruim',
      texto: 'Quando corre ou prende a respiração, você precisa fazer testes de Fortitude para não ficar fatigado a partir da primeira rodada (normalmente, personagens só precisam fazer esses testes após um número de rodadas igual a sua Constituição +1). Além disso, sempre que faz uma investida, você fica fatigado até o fim da cena.' },
    { id: 'rabugento', nome: 'Rabugento',
      texto: 'Você reclama de tudo. Você sofre –5 em testes de Carisma e de perícias baseadas nesse atributo, exceto Intimidação.' },
    { id: 'recurvado', nome: 'Recurvado',
      texto: 'A idade dobrou suas costas. Você conta como uma categoria de tamanho menor para alcance natural, modificador de manobras e armas que pode empunhar (mas não para espaço ocupado, modificador de Furtividade ou dano de armas naturais).' },
    { id: 'sono-ruim', nome: 'Sono Ruim',
      texto: 'Você acorda várias vezes no meio da noite, o que atrapalha seu descanso. Sua recuperação de PM e PV é sempre uma categoria pior. Se a condição de descanso já é ruim, você recupera apenas 1 PM e 1 PV, independentemente do seu nível. Se já recupera apenas 1 PM e 1 PV, não recupera nada!' },
    { id: 'teimoso', nome: 'Teimoso',
      texto: 'Sempre que falha em um teste de atributo ou de perícia que possa tentar novamente, você é obrigado a tentar pelo menos mais uma vez (mesmo que isso possa prejudicá-lo). Teimoso é quem teima com você!' },
    { id: 'tosse', nome: 'Tosse',
      texto: 'Em cenas de ação, role 1d6 no início de cada rodada. Num resultado 1, você tem uma crise de tosse e fica atordoado por 1 rodada. Em cenas de interpretação, role 1d6 sempre que fizer um teste de perícia baseada em Carisma. Num resultado 1, você tem uma crise de tosse e sofre uma penalidade de –5 nesse teste.' },
    { id: 'turrao', nome: 'Turrão',
      texto: 'Você faz tudo sempre do seu jeito e tem dificuldade de lidar com coisas nas quais não é perito. Você não recebe o bônus de metade do nível em perícias nas quais não é treinado.' },
    { id: 'velha-ferida', nome: 'Velha Ferida',
      texto: 'Você tem um machucado antigo, que nunca cicatrizou direito. Sempre que você sofre um acerto crítico, o multiplicador de dano aumenta em +1 e você fica fraco (mesmo que seja imune, cumulativo).' },
  ];
})();
