// ════════════════════════════════════════════════════════════════════
//  DEVOTOS-DATA.JS — Deuses do Panteão & Poderes Concedidos (T20)
//  Localização: /grifos-alados/js/devotos-data.js
//
//  Fonte: Regras.txt — seções "Poderes Concedidos" e "Deuses".
//  Consumidores:
//    • devotos.js  — sub-aba "🙏 Poderes Concedidos" das Consultas
//    • monstros.js — bloco "Devoto" da ficha, ferramenta de poder
//                    concedido e regras especiais do Guia de NPCs
//
//  Campos de cada DEUS:
//    chave/nome/titulo/icone — identificação e exibição
//    lore       — parágrafo de apresentação do livro
//    crencas    — Crenças & Objetivos (como o devoto age)
//    obrigacoes — Obrigações & Restrições (o que é proibido)
//    simbolo/energia/arma/devotos — características do culto
//    basicos    — chaves dos 4 poderes da lista básica do deus
//
//  Campos de cada PODER:
//    chave/nome — identificação
//    deuses     — chaves dos deuses que concedem o poder
//    magica     — true = habilidade mágica (marcada com "✧" ou "e"
//                 no material original; precisa ficar explícito)
//    texto      — regra completa do poder
//
//  Regra geral: todos os poderes têm como pré-requisito ser devoto
//  de um dos deuses indicados; o atributo-chave é Sabedoria.
// ════════════════════════════════════════════════════════════════════
window.GA_DEVOTOS = {

  regras: {
    atributoChave: 'Sabedoria',
    intro: `Em Arton, você pode trabalhar a serviço dos deuses, cumprindo seus desígnios. Um personagem que serve a uma divindade é chamado devoto e, em troca de seguir certas obrigações, recebe poderes. Ser devoto é uma escolha: você pode ser um cavaleiro normal, sem obrigações, ou um cavaleiro devoto de Khalmyr, com obrigações e poderes.`,
    escolhendo: `Você pode se tornar devoto na construção de seu personagem ou sempre que subir de nível. Porém, só pode ter uma devoção e não pode mudá-la (exceto sob critério do mestre). Se você for clérigo, druida ou paladino, automaticamente será um devoto.
Para ser devoto de um deus, sua raça ou sua classe devem estar listadas na seção "Devotos" do deus em questão. Humanos e clérigos são exceção — podem ser devotos de qualquer divindade.
Ao se tornar devoto, você recebe um poder concedido a sua escolha da lista do deus e passa a seguir as Obrigações & Restrições dele.
Multiclasse: no caso de classes com listas de devoções permitidas, a classe com menos opções determina a que deve ser seguida (isso permite que uma devoção anterior seja mudada). Se não houver devoções compatíveis, a multiclasse não pode ser feita.`,
    violacao: `Se violar as Obrigações & Restrições, o devoto perde todos os seus PM e só pode recuperá-los a partir do próximo dia. Se violá-las de novo na mesma aventura, perde todos os seus PM e não pode recuperá-los até fazer uma penitência (veja a perícia Religião).`,
    poderes: `Todos os poderes concedidos possuem como pré-requisito ser devoto de um dos deuses indicados. O atributo-chave desses poderes é Sabedoria. Poderes marcados com ✨ são habilidades mágicas.`,
    templo: `Todas as criaturas da seção "O Templo" do Guia de NPCs são devotas de seus respectivos deuses e recebem um Poder Concedido de sua divindade à sua escolha. Ignore quaisquer características incompatíveis com as Obrigações & Restrições do devoto (por exemplo, um devoto de Marah não fará ataques, enquanto um de Megalokk não possuirá perícias de Inteligência ou Carisma).`,
  },

  deuses: [
    {
      chave: 'aharadak', nome: 'Aharadak', titulo: 'Deus da Tormenta', icone: '👁',
      lore: `Outrora um dos terríveis Lordes da Tormenta, esta aberração monstruosa ambicionava o grande poder divino oferecido pelos devotos de Arton. Após anos liderando seu próprio culto profano, Aharadak matou Tauron, o Deus da Força, e ascendeu como o novo e macabro Deus da Tormenta. Apenas os devotos mais depravados ousam cultuar esta divindade de escatologia e sadismo.`,
      crencas: `Reverenciar a Tormenta, apregoar a inevitabilidade de sua chegada ao mundo. Praticar a devassidão e a perversão. Deturpar tudo que é correto, desfigurar tudo que é normal. Abraçar a agonia, crueldade e loucura.`,
      simbolo: 'Um olho macabro de pupila vertical e cercado de espinhos', energia: 'Negativa', arma: 'Corrente de espinhos',
      devotos: 'Quaisquer. A Tormenta aceita tudo e todos.',
      basicos: ['afinidadeComATormenta', 'extaseDaLoucura', 'percepcaoTemporal', 'rejeicaoDivina'],
      obrigacoes: `Quase todos os cultistas de Aharadak são maníacos insanos, compelidos a praticar os atos mais abomináveis. No entanto, talvez devido à natureza alienígena e incompreensível deste deus, alguns devotos conseguem se resguardar — preservam sua humanidade, abstendo-se de cometer crimes ou profanações. Ainda assim, o devoto paga um preço: no início de qualquer cena de ação, role 1d6. Com um resultado ímpar, ele fica fascinado na primeira rodada, perdido em devaneios sobre a futilidade da vida (mesmo que seja imune a esta condição).`,
    },
    {
      chave: 'allihanna', nome: 'Allihanna', titulo: 'Deusa da Natureza', icone: '🌳',
      lore: `A Deusa da Natureza representa a bondade inerente ao mundo natural, a pureza das plantas e animais. Mesmo os animais predadores são considerados puros, inocentes — pois matam apenas para sobreviver, ao contrário dos monstros e seres civilizados. Divindade principal dos druidas, Allihanna também é cultuada por povos bárbaros, que veneram faces variadas desta deusa.`,
      crencas: `Reverenciar os seres da natureza. Proteger a vida selvagem. Promover harmonia entre a natureza e a civilização. Combater monstros, mortos-vivos e outras criaturas que perturbam o equilíbrio natural.`,
      simbolo: 'Para bárbaros e adoradores de animais, o respectivo animal; para outros, uma pequena árvore', energia: 'Positiva', arma: 'Bordão',
      devotos: 'Dahllan, elfos, sílfides, bárbaros, caçadores, druidas.',
      basicos: ['compreenderOsErmos', 'dedoVerde', 'descansoNatural', 'vozDaNatureza'],
      obrigacoes: `Devotos de Allihanna não podem usar armaduras e escudos feitos de metal — apenas armadura acolchoada, de couro, gibão de peles e escudo leve, ou itens feitos de materiais especiais não metálicos. Também não podem descansar em nenhuma comunidade maior que uma aldeia (não perdem seus poderes, mas também não recuperam pontos de vida ou mana). Por isso, sempre preferem o relento a um quarto de estalagem.`,
    },
    {
      chave: 'arsenal', nome: 'Arsenal', titulo: 'Deus da Guerra', icone: '⚒',
      lore: `Outrora um infame clérigo guerreiro, o vilão conhecido apenas como Mestre Arsenal se tornou sumo-sacerdote do violento deus Keenn. Após conquistar a mais poderosa espada mágica de Arton, derrotou seu próprio patrono em combate durante um torneio épico, ascendendo ao Panteão como o novo Deus da Guerra. Com o objetivo de tornar Arton mais forte, Arsenal e seus devotos seguem deflagrando conflitos por todo o Reinado e além.`,
      crencas: `Promover a guerra e o conflito. Vencer a qualquer custo, pela força ou estratégia. Jamais oferecer ou aceitar rendição. Eliminar as próprias fraquezas. Conhecer o inimigo como a si mesmo. Sempre encontrar condições de vitória; quando não existirem, criá-las.`,
      simbolo: 'Um martelo de guerra e uma espada longa cruzados sobre um escudo', energia: 'Qualquer', arma: 'Martelo de guerra',
      devotos: 'Anões, minotauros, bárbaros, cavaleiros, guerreiros, lutadores.',
      basicos: ['conjurarArma', 'coragemTotal', 'feGuerreira', 'sangueDeFerro'],
      obrigacoes: `Um devoto de Arsenal é proibido de ser derrotado em qualquer tipo de combate ou disputa (como um teste oposto para ver quem é mais forte). Caso seu grupo seja derrotado, isso também constitui uma violação das obrigações.`,
    },
    {
      chave: 'azgher', nome: 'Azgher', titulo: 'Deus-Sol', icone: '☀',
      lore: `Venerado pelos povos do Deserto da Perdição, o Deus-Sol é também cultuado por viajantes, mercadores honestos e todos aqueles que combatem as trevas. É um deus generoso; sua jornada diária derrama calor e conforto sobre Arton. Como um olho sempre vigilante nos céus, nada acontece à luz do dia sem que Azgher perceba.`,
      crencas: `Praticar a gratidão pela proteção e generosidade do sol. Promover a honestidade, expor embustes e mentiras. Praticar a caridade e o altruísmo. Proteger os necessitados. Oferecer clemência, perdão e redenção. Combater o mal.`,
      simbolo: 'Um sol dourado', energia: 'Positiva', arma: 'Cimitarra',
      devotos: 'Aggelus, qareen, arcanistas, bárbaros, caçadores, cavaleiros, guerreiros, nobres, paladinos.',
      basicos: ['espadaSolar', 'fulgorSolar', 'habitanteDoDeserto', 'inimigoDeTenebra'],
      obrigacoes: `O devoto de Azgher deve manter o rosto sempre coberto (com uma máscara, capuz ou trapos). Sua face pode ser revelada apenas ao sumo-sacerdote ou em seu funeral. Devotos do Sol também devem doar para a igreja de Azgher 20% de qualquer tesouro obtido — a doação deve ser feita em ouro, seja na forma de moedas ou itens.`,
    },
    {
      chave: 'hyninn', nome: 'Hyninn', titulo: 'Deus da Trapaça', icone: '🦊',
      lore: `Capaz de enganar até mesmo outros deuses, o ardiloso Deus da Trapaça é uma divindade favorita de foras da lei — seus clérigos atuam como conselheiros, ou até líderes, em guildas criminosas ou navios piratas. Também é louvado por regentes e mercadores não muito honestos. Mesmo pessoas honradas eventualmente simpatizam com Hyninn por sua esperteza, despreocupação e ousadia.`,
      crencas: `Praticar a astúcia e a esperteza. Demonstrar que honestidade e sinceridade levam ao fracasso. Desafiar a lei e a ordem. Ser vitorioso sem seguir regras. Fazer aos outros antes que façam a você. Levar vantagem em tudo.`,
      simbolo: 'Uma adaga atravessando uma máscara, ou uma raposa', energia: 'Qualquer', arma: 'Adaga',
      devotos: 'Hynne, goblins, sílfides, bardos, bucaneiros, ladinos, inventores, nobres.',
      basicos: ['apostarComOTrapaceiro', 'farsaDoFingidor', 'formaDeMacaco', 'golpistaDivino'],
      obrigacoes: `Um devoto de Hyninn não recusa participação em um golpe, trapaça ou artimanha (o que muitas vezes inclui missões para roubar... hã, resgatar tesouros), exceto quando prejudica seus próprios aliados. O devoto também deve fazer um ato furtivo, ousado ou proibido por dia (ou por sessão de jogo, o que demorar mais), como oferenda a Hyninn — roubar uma bolsa, enganar um miliciano, invadir o quarto de um nobre... Em termos de jogo, uma ação exigindo um teste de Enganação ou Ladinagem com CD mínima 15 + metade do seu nível.`,
    },
    {
      chave: 'kallyadranoch', nome: 'Kallyadranoch', titulo: 'Deus dos Dragões', icone: '🐲',
      lore: `Como punição imposta por Khalmyr pelo crime de criar a Tormenta, o Deus dos Dragões estava esquecido até poucos anos atrás, conhecido apenas como "o Terceiro". Restaurado em tempos recentes, Kallyadranoch agora governa não apenas os dragões, mas todos que cultuam o poder elemental das grandes feras. Enquanto Wynna representa o lado bondoso da magia arcana, Kally é cultuado por arcanistas malignos.`,
      crencas: `Praticar a soberania. Demonstrar orgulho, superioridade, majestade. Praticar o acúmulo de riquezas. Proteger suas posses e sua dignidade. Ser implacável com seus inimigos. Reverenciar os dragões e suas crias.`,
      simbolo: 'Escamas de cinco cores diferentes', energia: 'Negativa', arma: 'Lança',
      devotos: 'Elfos, medusas, sulfure, arcanistas, cavaleiros, guerreiros, lutadores, nobres.',
      basicos: ['auraDeMedo', 'escamasDraconicas', 'presasPrimordiais', 'servosDoDragao'],
      obrigacoes: `Para subir de nível, além de acumular XP suficiente, o devoto de Kally deve realizar uma oferenda em tesouro, de valor igual a 20% da diferença do dinheiro inicial do nível que vai alcançar para o nível atual (por exemplo, T$ 80 para subir para o 4º nível). Sabe-se, também, de devotos malignos que sacrificam vítimas a Kally (não permitido para personagens jogadores).`,
    },
    {
      chave: 'khalmyr', nome: 'Khalmyr', titulo: 'Deus da Justiça', icone: '⚖',
      lore: `Antigo líder do Panteão, o Deus da Justiça já foi considerado a divindade mais popular no Reinado. Ainda é louvado por aqueles que lutam pela ordem e justiça — as duas maiores ordens de cavaleiros em Arton foram criadas em sua honra: a Ordem da Luz e a Ordem de Khalmyr. É também uma das divindades principais dos anões, junto de Tenebra.`,
      crencas: `Praticar a caridade e o altruísmo. Defender a lei, a ordem e os necessitados. Combater a mentira, o crime e o mal. Oferecer clemência, perdão e redenção. Lutar o bom combate.`,
      simbolo: 'Espada sobreposta a uma balança', energia: 'Positiva', arma: 'Espada longa',
      devotos: 'Aggelus, anões, cavaleiros, guerreiros, nobres, paladinos.',
      basicos: ['coragemTotal', 'domDaVerdade', 'espadaJusticeira', 'repararInjustica'],
      obrigacoes: `Devotos de Khalmyr não podem recusar pedidos de ajuda de pessoas inocentes. Também devem cumprir as ordens de superiores na hierarquia da igreja (devotos do Deus da Justiça de nível maior) e só podem usar itens mágicos permanentes criados por devotos do mesmo deus.`,
    },
    {
      chave: 'lena', nome: 'Lena', titulo: 'Deusa da Vida', icone: '🌙',
      lore: `Mesmo os deuses mais violentos e cruéis são respeitosos com a Deusa Criança, provedora da fertilidade, do sustento, da própria vida. Lena não é venerada apenas por aventureiros necessitados de curas mágicas, mas também por fazendeiros, criadores e cada grávida prestes a dar à luz. Servida quase exclusivamente por mulheres, a Deusa da Vida oferece os mais poderosos milagres de cura presenciados em Arton.`,
      crencas: `Reverenciar e proteger a vida em todas as suas formas. Reverenciar a fertilidade, a fecundidade, a maternidade e a infância. Praticar a caridade e o altruísmo. Oferecer clemência, perdão e redenção. Aliviar a dor e o sofrimento físico, mental ou espiritual.`,
      simbolo: 'Lua crescente prateada', energia: 'Positiva', arma: 'Não há — servos desta deusa não podem lançar a magia Arma Espiritual e similares',
      devotos: 'Dahllan, qareen, nobres, paladinos.',
      basicos: ['ataquePiedoso', 'auraRestauradora', 'curaGentil', 'curandeiraPerfeita'],
      obrigacoes: `Devotos de Lena não podem causar dano letal ou perda de PV a criaturas vivas (fornecer bônus em dano letal também é proibido). Podem causar dano não letal e prejudicar seus inimigos (em termos de jogo, impondo condições), desde que não causem dano letal ou perda de PV. Para um devoto de Lena, é preferível perder a própria vida a tirá-la de outros. Apenas mulheres podem ser devotas de Lena; uma clériga precisa dar à luz pelo menos uma vez antes de receber seus poderes divinos. Paladinos de Lena podem ser homens (os únicos devotos masculinos permitidos) ou mulheres.`,
    },
    {
      chave: 'linwu', nome: 'Lin-Wu', titulo: 'Deus Samurai', icone: '⛩',
      lore: `Mesmo com a quase extinção de seu povo pela Tormenta, o honrado Deus Samurai nunca fraquejou, nunca perdeu sua dignidade. Hoje, o Império de Jade está livre da tempestade e seus habitantes retornam para a grande reconstrução. Conforme especulam seus servos shugenja, devotos de Lin-Wu atuando longe de Tamu-ra recebem poderes diferentes, mais convenientes para suas missões.`,
      crencas: `Promover a honra acima de tudo. Proteger Tamu-ra e o Reinado de Arton. Praticar honestidade, coragem, cortesia e compaixão. Demonstrar integridade e dignidade. Ser leal a seus companheiros. Buscar redenção após cometer desonra.`,
      simbolo: 'Placa de metal com a silhueta de um dragão-serpente celestial', energia: 'Qualquer', arma: 'Katana',
      devotos: 'Anões, cavaleiros, guerreiros, nobres, paladinos.',
      basicos: ['coragemTotal', 'kiaiDivino', 'menteVazia', 'tradicaoDeLinWu'],
      obrigacoes: `Antigas proibições quanto a devotos estrangeiros ou do gênero feminino não mais se aplicam. No entanto, devotos de Lin-Wu ainda devem demonstrar comportamento honrado, jamais recorrendo a mentiras e subterfúgios. Em termos de jogo, são proibidos de tentar qualquer ação que exigiria um teste de Enganação, Furtividade ou Ladinagem.`,
    },
    {
      chave: 'marah', nome: 'Marah', titulo: 'Deusa da Paz', icone: '❤',
      lore: `Neste mundo sempre em guerra, devotos da Deusa da Paz talvez sejam os mais corajosos e perseverantes, buscando inspiração em sua padroeira para proteger Arton sem usar de violência. Marah ensina a suportar qualquer provação e a demonstrar que brutalidade nunca é a única resposta. Seus devotos costumam ser plenos de bom humor e atitude positiva, sempre prontos para uma nova celebração ou romance.`,
      crencas: `Praticar o amor e a gratidão pela vida e pela bondade. Promover a paz, harmonia e felicidade. Aliviar a dor e o sofrimento, trazer conforto aos aflitos. Praticar a caridade e o altruísmo. Oferecer clemência, perdão e redenção.`,
      simbolo: 'Um coração vermelho', energia: 'Positiva', arma: 'Não há — devotos desta deusa não podem lançar a magia Arma Espiritual e similares',
      devotos: 'Aggelus, elfos, hynne, qareen, bardos, nobres, paladinos.',
      basicos: ['auraDePaz', 'domDaEsperanca', 'palavrasDeBondade', 'talentoArtistico'],
      obrigacoes: `Devotos de Marah não podem causar dano, perda de PV e condições a criaturas, exceto enfeitiçado, fascinado e pasmo (fornecer bônus em dano também é proibido). Em combate, só podem recorrer a ações como proteger ou curar — ou fugir, render-se ou aceitar a morte. Um devoto de Marah jamais vai causar violência, nem mesmo para se salvar.`,
    },
    {
      chave: 'megalokk', nome: 'Megalokk', titulo: 'Deus dos Monstros', icone: '🐾',
      lore: `O Deus dos Monstros é uma divindade de selvageria e descontrole — quando bárbaros entram em fúria, diz-se que estão apenas canalizando seu rancor primordial. Enquanto servos de Allihanna promovem harmonia entre a natureza e os povos civilizados, devotos de seu irmão sanguinário buscam apenas o extermínio de seus inimigos. E, para um servo do Deus dos Monstros, quase tudo que se move é um inimigo...`,
      crencas: `Praticar a violência, a soberania do mais forte. Jamais reprimir os próprios instintos e desejos. Jamais ser domado, desafiar qualquer forma de controle. Jamais oferecer perdão ou rendição. Eliminar os fracos. Destruir seus inimigos.`,
      simbolo: 'A garra de um monstro', energia: 'Negativa', arma: 'Maça',
      devotos: 'Goblins, medusas, minotauros, sulfure, trogs, bárbaros, caçadores, druidas, lutadores.',
      basicos: ['olharAmedrontador', 'presasPrimordiais', 'urroDivino', 'vozDosMonstros'],
      obrigacoes: `Devotos de Megalokk devem rejeitar os modos civilizados e se entregar à ferocidade, descontrole e impaciência. O devoto é proibido de usar perícias baseadas em Inteligência ou Carisma (exceto Adestramento e Intimidação) e não pode preparar uma ação, escolher 10 ou 20 em testes e lançar magias sustentadas (pois são ações que exigem foco e paciência).`,
    },
    {
      chave: 'nimb', nome: 'Nimb', titulo: 'Deus do Caos', icone: '🎲',
      lore: `"Khalmyr tem o tabuleiro, mas quem move as peças é Nimb" — provérbio dos tempos em que o Deus da Justiça governava o Panteão. Nada é certo sobre esta entidade do acaso, sorte e azar. Nimb é mais temido do que venerado pelos artonianos, cautelosos quanto às suas constantes mudanças de humor. Muitos desejam que ele lhes sorria, mas poucos escolhem ser seus devotos. Ainda assim, há quem abrace sua loucura libertadora.`,
      crencas: `Reverenciar o caos, a aleatoriedade, a sorte e o azar. Praticar a ousadia e a rebeldia, desafiar regras e leis. Rejeitar o bom senso. Tornar o mundo mais interessante. Ou divertido. Ou terrível. Ou não.`,
      simbolo: 'Um dado de seis faces', energia: 'Qualquer', arma: 'Nenhuma e todas! Ao usar um efeito que dependa de arma preferida, qualquer arma (ou outro objeto!) pode aparecer, de acordo com o mestre',
      devotos: 'Goblins, qareen, sílfides, arcanistas, bárbaros, bardos, bucaneiros, inventores, ladinos.',
      basicos: ['extaseDaLoucura', 'poderOculto', 'sorteDosLoucos', 'transmissaoDaLoucura'],
      obrigacoes: `Por serem incapazes de seguir regras, estes devotos não têm "obrigações" verdadeiras (portanto, nunca perdem PM por descumprirem suas O&R). No entanto, sofrem certas restrições que não podem ignorar: devotos de Nimb são loucos (ou agem como se fossem), não conseguindo convencer ninguém de coisa alguma — sofrem –5 em testes de perícias baseadas em Carisma. Além disso, no início de cada cena de ação, role 1d6: com um resultado 1, o devoto fica confuso (mesmo que seja imune a esta condição).`,
    },
    {
      chave: 'oceano', nome: 'Oceano', titulo: 'Deus dos Mares', icone: '🐚',
      lore: `Nestes tempos de grande tumulto no plano divino, o Deus dos Mares está entre os poucos ainda imutáveis. Sua época de fúria, quando arrasava civilizações inteiras, foi quase esquecida. Hoje o Oceano é sereno, pleno em si mesmo, alienado dos conflitos no Panteão. Recebe preces de marinheiros, piratas e povos marinhos, orando por sua tranquilidade, rogando que suas tempestades sejam breves.`,
      crencas: `Reverenciar os mares, o oceano e os seres que ali habitam. Promover harmonia entre o oceano e o mundo seco. Proteger os seres marinhos, mas também os seres do mundo seco que se aventuram sobre as ondas. Demandar devido respeito ao mar e seu poder.`,
      simbolo: 'Uma concha', energia: 'Qualquer', arma: 'Tridente',
      devotos: 'Dahllan, hynne, minotauros, sereias/tritões, bárbaros, bucaneiros, caçadores, druidas.',
      basicos: ['anfibio', 'arsenalDasProfundezas', 'mestreDosMares', 'soproDoMar'],
      obrigacoes: `As únicas armas permitidas para devotos do Oceano são a azagaia, a lança, o tridente e a rede. Podem usar apenas armaduras leves. O devoto também não pode se manter afastado do oceano por mais de um mês.`,
    },
    {
      chave: 'sszzaas', nome: 'Sszzaas', titulo: 'Deus da Traição', icone: '🐍',
      lore: `O sibilante Deus da Traição não é apenas o mais inteligente entre os deuses, mas também o mais perigoso. Chegou a ser expulso do Panteão por tentar reunir os Rubis da Virtude, mas sua astúcia não conhecia limites; conseguiu tramar um novo plano para ser aceito de volta. Hoje os sszzaazitas voltam a se espalhar sobre Arton, agindo em nome do Grande Corruptor. Apenas os mais ousados e astutos acreditam ser prudente devotar-se a ele.`,
      crencas: `Praticar a mentira e a trapaça. Buscar sempre a solução mais inteligente. Demonstrar que lealdade e confiança são fraquezas, devem ser eliminadas. Promover competição, rivalidade, desconfiança. Usar os recursos do inimigo para alcançar seus objetivos. Levar outros a se sacrificarem em seu lugar.`,
      simbolo: 'Uma naja vertendo veneno pelas presas', energia: 'Negativa', arma: 'Adaga',
      devotos: 'Medusas, arcanistas, bardos, bucaneiros, inventores, ladinos, nobres.',
      basicos: ['astuciaDaSerpente', 'familiarOfidico', 'presasVenenosas', 'sangueOfidico'],
      obrigacoes: `O devoto deve fazer um ato de traição, intriga ou corrupção por dia (ou por sessão de jogo, o que demorar mais) como oferenda a Sszzaas. Pouco importa se o alvo é aliado ou inimigo. Sugerir a alguém que foi traído pelo cônjuge, influenciar um guarda a aceitar suborno, instruir um mercador a roubar nos preços, incriminar alguém por um crime que não cometeu... Em termos de jogo, uma ação exigindo um teste de Enganação com CD mínima 15 + metade do seu nível.`,
    },
    {
      chave: 'tannatoh', nome: 'Tanna-Toh', titulo: 'Deusa do Conhecimento', icone: '📜',
      lore: `Em uma sociedade medieval típica, apenas membros do clero ou da nobreza teriam acesso a boa educação. Não é assim no Reinado de Arton, graças ao empenho da igreja de Tanna-Toh. Devotos da Deusa do Conhecimento atuam como professores, catequistas e pesquisadores, tomando a missão sagrada de levar educação e cultura para todos. Esta deusa é inimiga de povos bárbaros que escolhem permanecer ignorantes e selvagens.`,
      crencas: `Reverenciar a mente racional, o conhecimento, a civilização, a verdade. Proteger o progresso, o avanço dos povos civilizados. Promover o ensino e a prática das artes e das ciências. Solucionar todos os mistérios, revelar todas as mentiras. Buscar novo conhecimento. Não tolerar a ignorância.`,
      simbolo: 'Pergaminho e pena', energia: 'Qualquer', arma: 'Bordão',
      devotos: 'Golens, kliren, arcanistas, bardos, inventores, nobres, paladinos.',
      basicos: ['conhecimentoEnciclopedico', 'menteAnalitica', 'pesquisaAbencoada', 'vozDaCivilizacao'],
      obrigacoes: `Devotos de Tanna-Toh jamais podem recusar uma missão que envolva a busca por um novo conhecimento ou informação — investigar rumores sobre um livro perdido, procurar uma aldeia lendária, pesquisar os hábitos de uma criatura desconhecida... Além disso, o devoto sempre deve dizer a verdade e nunca pode se recusar a responder uma pergunta direta, pouco importando as consequências. É proibido para ele esconder qualquer conhecimento.`,
    },
    {
      chave: 'tenebra', nome: 'Tenebra', titulo: 'Deusa das Trevas', icone: '🌑',
      lore: `Assim como seu inimigo Azgher vigia e protege Arton durante o dia, Tenebra é atenta sob as estrelas; nada acontece na noite sem seu conhecimento. A sedutora e misteriosa Deusa das Trevas é mãe de tudo que anda e rasteja no escuro, dos nobres anões aos sinistros mortos-vivos e trogloditas. Com a destruição de Ragnar, antigo Deus da Morte, cada vez mais cultos necromantes oferecem sacrifícios à Mãe Noite.`,
      crencas: `Reverenciar a noite, a escuridão, a lua e as estrelas. Proteger segredos e mistérios, proteger tudo que é oculto e invisível. Reverenciar a não vida e os mortos-vivos, propagar a prática da necromancia. Rejeitar o sol e a luz.`,
      simbolo: 'Estrela negra de cinco pontas', energia: 'Negativa', arma: 'Adaga',
      devotos: 'Anões, medusas, qareen, osteon, sulfure, trogs, arcanistas, bardos, ladinos.',
      basicos: ['cariciaSombria', 'mantoDaPenumbra', 'visaoNasTrevas', 'zumbificar'],
      obrigacoes: `Tenebra proíbe que seus devotos sejam tocados por Azgher, o odiado rival. O devoto deve se cobrir inteiramente durante o dia, sem expor ao sol nenhum pedaço de pele.`,
    },
    {
      chave: 'thwor', nome: 'Thwor', titulo: 'Deus dos Goblinoides', icone: '✊',
      lore: `A Flecha de Fogo foi disparada, rompendo o coração das trevas. Ao enfrentar e derrotar o próprio Ragnar, antigo Deus da Morte, o imperador bugbear Thwor Khoshkothruk ascendeu ao Panteão como o Deus dos Goblinoides. Agora protegidos e governados por uma poderosa divindade, os povos duyshidakk erguem sua própria civilização no continente de Lamnor, e o Reinado de Arton deverá lidar com o futuro que surgir disso.`,
      crencas: `Reverenciar a lealdade, a força e a coragem. Promover a união entre goblins, hobgoblins, bugbears, orcs, ogros e outros povos humanoides. Reverenciar o caos, a mutação, a vida sempre em movimento. Proteger a cultura e o modo de vida goblinoide. Destruir os elfos.`,
      simbolo: 'Um grande punho fechado', energia: 'Qualquer', arma: 'Machado de guerra',
      devotos: 'Qualquer duyshidakk (aceito como membro do povo goblinoide).',
      basicos: ['almejarOImpossivel', 'furiaDivina', 'olharAmedrontador', 'tropasDuyshidakk'],
      obrigacoes: `Não importando sua raça, o devoto de Thwor deve ser duyshidakk — ou seja, aceito como membro do povo goblinoide. Também deve se esforçar para que o "Mundo Como Deve Ser" tome o continente. Deve sempre procurar fazer alianças com goblinoides e só lutar contra eles em último caso.`,
    },
    {
      chave: 'thyatis', nome: 'Thyatis', titulo: 'Deus da Ressurreição e Profecia', icone: '🕊',
      lore: `O generoso Deus da Ressurreição e Profecia representa o perdão, a tolerância, as segundas chances. Seu dom maior é a prevenção ou correção dos erros — através de predições que evitam esses erros ou reversão das mortes que tenham causado. Para Thyatis, ninguém deve ser castigado por errar e todos merecem a chance de aprender com suas falhas. Dizem que seus clérigos são contemplados com poderosos dons de profecia e ressurreição, e seus paladinos nunca morrem!`,
      crencas: `Proteger a vida e aqueles necessitados de novas chances. Renegar a morte e a mentira. Ajudar os perdidos a encontrar seus caminhos e alcançar seus destinos. Oferecer clemência, perdão e redenção.`,
      simbolo: 'Uma ave fênix', energia: 'Positiva', arma: 'Espada longa',
      devotos: 'Aggelus, cavaleiros, guerreiros, inventores, lutadores, paladinos.',
      basicos: ['ataquePiedoso', 'domDaImortalidade', 'domDaProfecia', 'domDaRessurreicao'],
      obrigacoes: `Devotos de Thyatis são proibidos de matar criaturas inteligentes (Int –3 ou maior). Podem atacar e causar dano, mas jamais levar à morte. Por esse motivo, devotos de Thyatis preferem armas e ataques que apenas incapacitam seus oponentes ou causam dano não letal.`,
    },
    {
      chave: 'valkaria', nome: 'Valkaria', titulo: 'Deusa da Ambição', icone: '🗽',
      lore: `A Deusa da Ambição sempre foi a mais ousada entre os seus. Criaria os seres humanos, povo mais impetuoso e beligerante de todos. Acabaria condenada ao cativeiro, até ser resgatada por seus próprios protegidos. Quando Mestre Arsenal derrotou Keenn, o maior objetivo de Valkaria foi enfim alcançado: um humano superou um deus. Esse evento levou os deuses a reconhecerem Valkaria como a nova liderança do Panteão.`,
      crencas: `Praticar o otimismo, a evolução, a rebeldia. Desafiar limites, almejar o impossível. Combater o mal, a opressão e a tirania. Proteger a liberdade. Aceitar o novo e diferente e adaptar-se a ele. Demonstrar ambição, paixão e coragem. Desfrutar e amar a vida.`,
      simbolo: 'A Estátua de Valkaria ou seis faixas entrelaçadas', energia: 'Positiva', arma: 'Mangual',
      devotos: 'Aventureiros; membros de todas as classes podem ser devotos de Valkaria.',
      basicos: ['almejarOImpossivel', 'armasDaAmbicao', 'coragemTotal', 'liberdadeDivina'],
      obrigacoes: `Valkaria odeia o conformismo. Seus devotos são proibidos de fixar moradia em um mesmo lugar, não podendo permanecer mais de 2d10+10 dias na mesma cidade (ou vila, aldeia, povoado...) ou 1d4+2 meses no mesmo reino. Devotos de Valkaria também são proibidos de se casar ou formar qualquer união estável.`,
    },
    {
      chave: 'wynna', nome: 'Wynna', titulo: 'Deusa da Magia', icone: '💍',
      lore: `Depois de abandonados por Glórienn, a antiga Deusa dos Elfos, muitos membros desta raça estão oferecendo sua devoção à bondosa Wynna. Ela é a exuberante Deusa da Magia, louvada por fadas, qareen, gênios e todos aqueles que empregam poder arcano. Generosa e liberal além dos limites, Wynna concede mágica a todos que pedem — pois a magia é mais importante que a vida e nunca deve ser negada a ninguém.`,
      crencas: `Reverenciar a magia arcana e seus praticantes. Promover o ensino da magia. Usar a magia para proteger os necessitados e trazer felicidade ao mundo.`,
      simbolo: 'Um anel metálico', energia: 'Qualquer', arma: 'Adaga',
      devotos: 'Elfos, golens, qareen, sílfides, arcanistas, bardos.',
      basicos: ['bencaoDoMana', 'centelhaMagica', 'escudoMagico', 'teurgistaMistico'],
      obrigacoes: `Assim como a magia jamais deve ser negada para quem a busca, devotos de Wynna devem praticar a bondade e a generosidade de sua deusa, jamais recusando um pedido de ajuda de alguém inocente. Além disso, devotos de Wynna são proibidos de matar seres mágicos (elfos, qareen, sílfides e outros a critério do mestre) e conjuradores arcanos.`,
    },
  ],

  poderes: [
    // ── Lista básica (Tormenta20) ────────────────────────────────────
    { chave: 'afinidadeComATormenta', nome: 'Afinidade com a Tormenta', deuses: ['aharadak'], magica: false,
      texto: `Você recebe +10 em testes de resistência contra efeitos da Tormenta, de suas criaturas e de devotos de Aharadak. Além disso, seu primeiro poder da Tormenta não conta para perda de Carisma.` },
    { chave: 'almejarOImpossivel', nome: 'Almejar o Impossível', deuses: ['thwor', 'valkaria'], magica: false,
      texto: `Quando faz um teste de perícia, um resultado de 19 ou mais no dado sempre é um sucesso, não importando o valor a ser alcançado.` },
    { chave: 'anfibio', nome: 'Anfíbio', deuses: ['oceano'], magica: false,
      texto: `Você pode respirar embaixo d'água e adquire deslocamento de natação igual a seu deslocamento terrestre.` },
    { chave: 'apostarComOTrapaceiro', nome: 'Apostar com o Trapaceiro', deuses: ['hyninn'], magica: true,
      texto: `Quando faz um teste de perícia, você pode gastar 1 PM para apostar com Hyninn. Você e o mestre rolam 1d20, mas o mestre mantém o resultado dele em segredo. Você então escolhe entre usar seu próprio resultado ou o resultado oculto do mestre (neste caso, ele revela o resultado).` },
    { chave: 'armasDaAmbicao', nome: 'Armas da Ambição', deuses: ['valkaria'], magica: false,
      texto: `Você recebe +1 em testes de ataque e na margem de ameaça com armas nas quais é proficiente.` },
    { chave: 'arsenalDasProfundezas', nome: 'Arsenal das Profundezas', deuses: ['oceano'], magica: false,
      texto: `Você recebe +2 nas rolagens de dano com azagaias, lanças e tridentes e seu multiplicador de crítico com essas armas aumenta em +1.` },
    { chave: 'astuciaDaSerpente', nome: 'Astúcia da Serpente', deuses: ['sszzaas'], magica: false,
      texto: `Você recebe +2 em Enganação, Furtividade e Intuição.` },
    { chave: 'ataquePiedoso', nome: 'Ataque Piedoso', deuses: ['lena', 'thyatis'], magica: false,
      texto: `Você pode usar armas corpo a corpo para causar dano não letal sem sofrer a penalidade de –5 no teste de ataque.` },
    { chave: 'auraDeMedo', nome: 'Aura de Medo', deuses: ['kallyadranoch'], magica: true,
      texto: `Você pode gastar 2 PM para gerar uma aura de medo de 9m de raio e duração até o fim da cena. Todos os inimigos que entrem na aura devem fazer um teste de Vontade (CD Car) ou ficam abalados até o fim da cena. Uma criatura que passe no teste de Vontade fica imune a esta habilidade por um dia.` },
    { chave: 'auraDePaz', nome: 'Aura de Paz', deuses: ['marah'], magica: true,
      texto: `Você pode gastar 2 PM para gerar uma aura de paz com alcance curto e duração de uma cena. Qualquer inimigo dentro da aura que tente fazer uma ação hostil contra você deve fazer um teste de Vontade (CD Car). Se falhar, perderá sua ação. Se passar, fica imune a esta habilidade por um dia.` },
    { chave: 'auraRestauradora', nome: 'Aura Restauradora', deuses: ['lena'], magica: false,
      texto: `Efeitos de cura usados por você e seus aliados em alcance curto recuperam +1 PV por dado.` },
    { chave: 'bencaoDoMana', nome: 'Bênção do Mana', deuses: ['wynna'], magica: false,
      texto: `Você recebe +1 PM a cada nível ímpar.` },
    { chave: 'cariciaSombria', nome: 'Carícia Sombria', deuses: ['tenebra'], magica: true,
      texto: `Você pode gastar 1 PM e uma ação padrão para cobrir sua mão com energia negativa e tocar uma criatura em alcance corpo a corpo. A criatura sofre 2d6 pontos de dano de trevas (Fortitude CD Sab reduz à metade) e você recupera PV iguais à metade do dano causado. Você pode aprender Toque Vampírico como uma magia divina. Se fizer isso, o custo dela diminui em –1 PM.` },
    { chave: 'centelhaMagica', nome: 'Centelha Mágica', deuses: ['wynna'], magica: false,
      texto: `Escolha uma magia arcana ou divina de 1º círculo. Você aprende e pode lançar essa magia.` },
    { chave: 'compreenderOsErmos', nome: 'Compreender os Ermos', deuses: ['allihanna'], magica: false,
      texto: `Você recebe +2 em Sobrevivência e pode usar Sabedoria para Adestramento (em vez de Carisma).` },
    { chave: 'conhecimentoEnciclopedico', nome: 'Conhecimento Enciclopédico', deuses: ['tannatoh'], magica: false,
      texto: `Você se torna treinado em duas perícias baseadas em Inteligência a sua escolha.` },
    { chave: 'conjurarArma', nome: 'Conjurar Arma', deuses: ['arsenal'], magica: true,
      texto: `Você pode gastar 1 PM para invocar uma arma corpo a corpo ou de arremesso com a qual seja proficiente. A arma surge em sua mão, fornece +1 em testes de ataque e rolagens de dano, é considerada mágica e dura pela cena. Você não pode criar armas de disparo, mas pode criar 20 munições.` },
    { chave: 'coragemTotal', nome: 'Coragem Total', deuses: ['arsenal', 'khalmyr', 'linwu', 'valkaria'], magica: false,
      texto: `Você é imune a efeitos de medo, mágicos ou não. Este poder não elimina fobias raciais (como o medo de altura dos minotauros).` },
    { chave: 'curaGentil', nome: 'Cura Gentil', deuses: ['lena'], magica: false,
      texto: `Você soma seu Carisma aos PV restaurados por seus efeitos mágicos de cura.` },
    { chave: 'curandeiraPerfeita', nome: 'Curandeira Perfeita', deuses: ['lena'], magica: false,
      texto: `Você sempre pode escolher 10 em testes de Cura. Além disso, não sofre penalidade por usar essa perícia sem uma maleta de medicamentos. Se possuir o item, recebe +2 no teste de Cura (ou +5, se ele for aprimorado).` },
    { chave: 'dedoVerde', nome: 'Dedo Verde', deuses: ['allihanna'], magica: true,
      texto: `Você aprende e pode lançar Controlar Plantas. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'descansoNatural', nome: 'Descanso Natural', deuses: ['allihanna'], magica: false,
      texto: `Para você, dormir ao relento conta como condição de descanso confortável.` },
    { chave: 'domDaEsperanca', nome: 'Dom da Esperança', deuses: ['marah'], magica: false,
      texto: `Você soma sua Sabedoria em seus PV em vez de Constituição, e se torna imune às condições alquebrado, esmorecido e frustrado.` },
    { chave: 'domDaImortalidade', nome: 'Dom da Imortalidade', deuses: ['thyatis'], magica: true,
      texto: `Você é imortal. Sempre que morre, não importando o motivo, volta à vida após 3d6 dias. Apenas paladinos podem escolher este poder. Um personagem pode ter Dom da Imortalidade ou Dom da Ressurreição, mas não ambos.` },
    { chave: 'domDaProfecia', nome: 'Dom da Profecia', deuses: ['thyatis'], magica: true,
      texto: `Você pode lançar Augúrio. Caso aprenda novamente essa magia, seu custo diminui em –1 PM. Você também pode gastar 2 PM para receber +2 em um teste.` },
    { chave: 'domDaRessurreicao', nome: 'Dom da Ressurreição', deuses: ['thyatis'], magica: true,
      texto: `Você pode gastar uma ação completa e todos os PM que possui (mínimo 1 PM) para tocar o corpo de uma criatura morta há menos de um ano e ressuscitá-la. A criatura volta à vida com 1 PV e 0 PM, e perde 1 ponto de Constituição permanentemente. Este poder só pode ser usado uma vez em cada criatura. Apenas clérigos podem escolher este poder. Um personagem pode ter Dom da Imortalidade ou Dom da Ressurreição, mas não ambos.` },
    { chave: 'domDaVerdade', nome: 'Dom da Verdade', deuses: ['khalmyr'], magica: false,
      texto: `Você pode pagar 2 PM para receber +5 em testes de Intuição, e em testes de Percepção contra Enganação e Furtividade, até o fim da cena.` },
    { chave: 'escamasDraconicas', nome: 'Escamas Dracônicas', deuses: ['kallyadranoch'], magica: false,
      texto: `Você recebe +2 na Defesa e em Fortitude.` },
    { chave: 'escudoMagico', nome: 'Escudo Mágico', deuses: ['wynna'], magica: true,
      texto: `Quando lança uma magia, você recebe um bônus na Defesa igual ao círculo da magia lançada até o início do seu próximo turno.` },
    { chave: 'espadaJusticeira', nome: 'Espada Justiceira', deuses: ['khalmyr'], magica: true,
      texto: `Você pode gastar 1 PM para encantar sua espada (ou outra arma corpo a corpo de corte que esteja empunhando). Ela tem seu dano aumentado em um passo até o fim da cena.` },
    { chave: 'espadaSolar', nome: 'Espada Solar', deuses: ['azgher'], magica: true,
      texto: `Você pode gastar 1 PM para fazer uma arma corpo a corpo de corte que esteja empunhando causar +1d6 de dano por fogo até o fim da cena.` },
    { chave: 'extaseDaLoucura', nome: 'Êxtase da Loucura', deuses: ['aharadak', 'nimb'], magica: false,
      texto: `Toda vez que uma ou mais criaturas falham em um teste de Vontade contra uma de suas habilidades mágicas, você recebe 1 PM temporário cumulativo. Você pode ganhar um máximo de PM temporários por cena desta forma igual a sua Sabedoria.` },
    { chave: 'familiarOfidico', nome: 'Familiar Ofídico', deuses: ['sszzaas'], magica: false,
      texto: `Você recebe um familiar cobra (veja a página 38 de Tormenta20) que não conta em seu limite de parceiros.` },
    { chave: 'farsaDoFingidor', nome: 'Farsa do Fingidor', deuses: ['hyninn'], magica: false,
      texto: `Você aprende e pode lançar Criar Ilusão. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'feGuerreira', nome: 'Fé Guerreira', deuses: ['arsenal'], magica: false,
      texto: `Você pode usar Sabedoria para Guerra (em vez de Inteligência). Além disso, em combate, pode gastar 2 PM para substituir um teste de perícia (exceto testes de ataque) por um teste de Guerra.` },
    { chave: 'formaDeMacaco', nome: 'Forma de Macaco', deuses: ['hyninn'], magica: true,
      texto: `Você pode gastar uma ação completa e 2 PM para se transformar em um macaco. Você adquire tamanho Minúsculo (o que fornece +5 em Furtividade e –5 em testes de manobra) e recebe deslocamento de escalar 9m. Seu equipamento desaparece (e você perde seus benefícios) até você voltar ao normal, mas suas outras estatísticas não são alteradas. A transformação dura indefinidamente, mas termina caso você faça um ataque, lance uma magia ou sofra dano.` },
    { chave: 'fulgorSolar', nome: 'Fulgor Solar', deuses: ['azgher'], magica: false,
      texto: `Você recebe redução de frio e trevas 5. Além disso, quando é alvo de um ataque você pode gastar 1 PM para emitir um clarão solar que deixa o atacante ofuscado por uma rodada.` },
    { chave: 'furiaDivina', nome: 'Fúria Divina', deuses: ['thwor'], magica: true,
      texto: `Você pode gastar 2 PM para invocar uma fúria selvagem, tornando-se temível em combate. Até o fim da cena, você recebe +2 em testes de ataque e rolagens de dano corpo a corpo, mas não pode executar nenhuma ação que exija paciência ou concentração (como usar a perícia Furtividade ou lançar magias). Se usar este poder em conjunto com a habilidade Fúria, ela também dura uma cena (e não termina se você não atacar ou for alvo de uma ação hostil).` },
    { chave: 'golpistaDivino', nome: 'Golpista Divino', deuses: ['hyninn'], magica: false,
      texto: `Você recebe +2 em Enganação, Jogatina e Ladinagem.` },
    { chave: 'habitanteDoDeserto', nome: 'Habitante do Deserto', deuses: ['azgher'], magica: true,
      texto: `Você recebe redução de fogo 10 e pode pagar 1 PM para criar água pura e potável suficiente para um odre (ou outro recipiente pequeno).` },
    { chave: 'inimigoDeTenebra', nome: 'Inimigo de Tenebra', deuses: ['azgher'], magica: false,
      texto: `Seus ataques e habilidades causam +1d6 pontos de dano contra mortos-vivos. Quando você usa um efeito que gera luz, o alcance da iluminação dobra.` },
    { chave: 'kiaiDivino', nome: 'Kiai Divino', deuses: ['linwu'], magica: false,
      texto: `Uma vez por rodada, quando faz um ataque corpo a corpo, você pode pagar 3 PM. Se acertar o ataque, causa dano máximo, sem necessidade de rolar dados.` },
    { chave: 'liberdadeDivina', nome: 'Liberdade Divina', deuses: ['valkaria'], magica: true,
      texto: `Você pode gastar 2 PM para receber imunidade a efeitos de movimento por uma rodada.` },
    { chave: 'mantoDaPenumbra', nome: 'Manto da Penumbra', deuses: ['tenebra'], magica: true,
      texto: `Você aprende e pode lançar Escuridão. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'menteAnalitica', nome: 'Mente Analítica', deuses: ['tannatoh'], magica: false,
      texto: `Você recebe +2 em Intuição, Investigação e Vontade.` },
    { chave: 'menteVazia', nome: 'Mente Vazia', deuses: ['linwu'], magica: false,
      texto: `Você recebe +2 em Iniciativa, Percepção e Vontade.` },
    { chave: 'mestreDosMares', nome: 'Mestre dos Mares', deuses: ['oceano'], magica: true,
      texto: `Você pode falar com animais aquáticos (como o efeito da magia Voz Divina) e aprende e pode lançar Acalmar Animal, mas só contra criaturas aquáticas. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'olharAmedrontador', nome: 'Olhar Amedrontador', deuses: ['megalokk', 'thwor'], magica: true,
      texto: `Você aprende e pode lançar Amedrontar. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'palavrasDeBondade', nome: 'Palavras de Bondade', deuses: ['marah'], magica: true,
      texto: `Você aprende e pode lançar Enfeitiçar. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'percepcaoTemporal', nome: 'Percepção Temporal', deuses: ['aharadak'], magica: false,
      texto: `Você pode gastar 3 PM para somar sua Sabedoria (limitado por seu nível e não cumulativo com efeitos que somam este atributo) a seus ataques, Defesa e testes de Reflexos até o fim da cena.` },
    { chave: 'pesquisaAbencoada', nome: 'Pesquisa Abençoada', deuses: ['tannatoh'], magica: false,
      texto: `Se passar uma hora pesquisando seus livros e anotações, você pode rolar novamente um teste de perícia baseada em Inteligência ou Sabedoria que tenha feito desde a última cena. Se tiver acesso a mais livros, você recebe um bônus no teste: +2 para uma coleção particular ou biblioteca pequena e +5 para a biblioteca de um templo ou universidade.` },
    { chave: 'poderOculto', nome: 'Poder Oculto', deuses: ['nimb'], magica: true,
      texto: `Você pode gastar uma ação de movimento e 2 PM para invocar a força, a rapidez ou o vigor dos loucos. Role 1d6 para receber +2 em Força (1 ou 2), Destreza (3 ou 4) ou Constituição (5 ou 6) até o fim da cena. Você pode usar este poder várias vezes, mas bônus no mesmo atributo não são cumulativos.` },
    { chave: 'presasPrimordiais', nome: 'Presas Primordiais', deuses: ['kallyadranoch', 'megalokk'], magica: true,
      texto: `Você pode gastar 1 PM para transformar seus dentes em presas afiadas até o fim da cena. Você recebe uma arma natural de mordida (dano 1d6, crítico x2, perfuração). Uma vez por rodada, quando usa a ação agredir com outra arma, você pode gastar 1 PM para fazer um ataque corpo a corpo extra com a mordida. Se já possuir outro ataque natural de mordida, em vez disso, o dano desse ataque aumenta em dois passos.` },
    { chave: 'presasVenenosas', nome: 'Presas Venenosas', deuses: ['sszzaas'], magica: false,
      texto: `Você pode gastar uma ação de movimento e 1 PM para envenenar uma arma corpo a corpo que esteja empunhando. Em caso de acerto, a arma causa perda de 1d12 pontos de vida. A arma permanece envenenada até atingir uma criatura ou até o fim da cena, o que acontecer primeiro.` },
    { chave: 'rejeicaoDivina', nome: 'Rejeição Divina', deuses: ['aharadak'], magica: false,
      texto: `Você recebe resistência a magia divina +5.` },
    { chave: 'repararInjustica', nome: 'Reparar Injustiça', deuses: ['khalmyr'], magica: false,
      texto: `Uma vez por rodada, quando um oponente em alcance curto acerta um ataque em você ou em um de seus aliados, você pode gastar 2 PM para fazer este oponente repetir o ataque, escolhendo o pior entre os dois resultados.` },
    { chave: 'sangueDeFerro', nome: 'Sangue de Ferro', deuses: ['arsenal'], magica: true,
      texto: `Você pode pagar 3 PM para receber +2 em rolagens de dano e redução de dano 5 até o fim da cena.` },
    { chave: 'sangueOfidico', nome: 'Sangue Ofídico', deuses: ['sszzaas'], magica: false,
      texto: `Você recebe resistência a veneno +5 e a CD para resistir aos seus venenos aumenta em +2.` },
    { chave: 'servosDoDragao', nome: 'Servos do Dragão', deuses: ['kallyadranoch'], magica: true,
      texto: `Você pode gastar uma ação completa e 2 PM para invocar 2d4+1 kobolds capangas em espaços desocupados em alcance curto. Você pode gastar uma ação de movimento para fazer os kobolds andarem (eles têm deslocamento 9m) ou uma ação padrão para fazê-los causar dano a criaturas adjacentes (1d6–1 pontos de dano de perfuração cada). Os kobolds têm For –1, Des 1, Defesa 12, 1 PV e falham automaticamente em qualquer teste de resistência ou oposto. Eles desaparecem quando morrem ou no fim da cena. Os kobolds não agem sem receber uma ordem. Usos criativos para capangas fora de combate ficam a critério do mestre.` },
    { chave: 'soproDoMar', nome: 'Sopro do Mar', deuses: ['oceano'], magica: true,
      texto: `Você pode gastar uma ação padrão e 1 PM para soprar vento marinho em um cone de 6m. Criaturas na área sofrem 2d6 pontos de dano de frio (Reflexos CD Sab reduz à metade). Você pode aprender Sopro das Uivantes como uma magia divina. Se fizer isso, o custo dela diminui em –1 PM.` },
    { chave: 'sorteDosLoucos', nome: 'Sorte dos Loucos', deuses: ['nimb'], magica: false,
      texto: `Você pode pagar 1 PM para rolar novamente um teste recém realizado. Se ainda assim falhar no teste, você perde 1d6 PM.` },
    { chave: 'talentoArtistico', nome: 'Talento Artístico', deuses: ['marah'], magica: false,
      texto: `Você recebe +2 em Acrobacia, Atuação e Diplomacia.` },
    { chave: 'teurgistaMistico', nome: 'Teurgista Místico', deuses: ['wynna'], magica: false,
      texto: `Até uma magia de cada círculo que você aprender poderá ser escolhida entre magias divinas (se você for um conjurador arcano) ou entre magias arcanas (se for um conjurador divino). Pré-requisito: habilidade de classe Magias.` },
    { chave: 'tradicaoDeLinWu', nome: 'Tradição de Lin-Wu', deuses: ['linwu'], magica: false,
      texto: `Você considera a katana uma arma simples e, se for proficiente em armas marciais, recebe +1 na margem de ameaça com ela.` },
    { chave: 'transmissaoDaLoucura', nome: 'Transmissão da Loucura', deuses: ['nimb'], magica: true,
      texto: `Você pode lançar Sussurros Insanos (CD Car). Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'tropasDuyshidakk', nome: 'Tropas Duyshidakk', deuses: ['thwor'], magica: true,
      texto: `Você pode gastar uma ação completa e 2 PM para invocar 1d4+1 goblinoides capangas em espaços desocupados em alcance curto. Você pode gastar uma ação de movimento para fazer os goblinoides andarem (eles têm deslocamento 9m) ou uma ação padrão para fazê-los causar dano a criaturas adjacentes (1d6+1 pontos de dano de corte cada). Os goblinoides têm For 1, Des 1, Defesa 15, 1 PV e falham automaticamente em qualquer teste de resistência ou oposto. Eles desaparecem quando morrem ou no fim da cena. Os goblinoides não agem sem receber uma ordem. Usos criativos para capangas fora de combate ficam a critério do mestre.` },
    { chave: 'urroDivino', nome: 'Urro Divino', deuses: ['megalokk'], magica: false,
      texto: `Quando faz um ataque ou lança uma magia, você pode pagar 1 PM para somar sua Constituição (mínimo +1) à rolagem de dano desse ataque ou magia.` },
    { chave: 'visaoNasTrevas', nome: 'Visão nas Trevas', deuses: ['tenebra'], magica: false,
      texto: `Você enxerga perfeitamente no escuro, incluindo em magias de escuridão.` },
    { chave: 'vozDaCivilizacao', nome: 'Voz da Civilização', deuses: ['tannatoh'], magica: true,
      texto: `Você está sempre sob efeito de Compreensão.` },
    { chave: 'vozDaNatureza', nome: 'Voz da Natureza', deuses: ['allihanna'], magica: true,
      texto: `Você pode falar com animais (como o efeito da magia Voz Divina) e aprende e pode lançar Acalmar Animal, mas só contra animais. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'vozDosMonstros', nome: 'Voz dos Monstros', deuses: ['megalokk'], magica: true,
      texto: `Você conhece os idiomas de todos os monstros inteligentes e pode se comunicar livremente com monstros não inteligentes (Int –4 ou menor), como se estivesse sob efeito da magia Voz Divina.` },
    { chave: 'zumbificar', nome: 'Zumbificar', deuses: ['tenebra'], magica: true,
      texto: `Você pode gastar uma ação completa e 3 PM para reanimar o cadáver de uma criatura Pequena ou Média adjacente por um dia. O cadáver funciona como um parceiro iniciante de um tipo a sua escolha entre combatente, fortão ou guardião. Além disso, quando sofre dano, você pode sacrificar esse parceiro; se fizer isso, você sofre apenas metade do dano, mas o cadáver é destruído.` },

    // ── Lista expandida ──────────────────────────────────────────────
    { chave: 'abracoDaFenix', nome: 'Abraço da Fênix', deuses: ['thyatis'], magica: false,
      texto: `Você se torna imune a fogo. Se fosse sofrer dano mágico de fogo, em vez disso cura PV em quantidade igual à metade desse dano (se já faz isso por outro efeito, cura a quantidade completa).` },
    { chave: 'adagaNoturna', nome: 'Adaga Noturna', deuses: ['tenebra'], magica: true,
      texto: `Você pode gastar 1 PM para fazer uma arma de perfuração que esteja usando causar +1d6 pontos de dano de frio até o fim da cena.` },
    { chave: 'aFerramentaCerta', nome: 'A Ferramenta Certa', deuses: ['hyninn'], magica: true,
      texto: `Você pode gastar 1 PM para fazer uma ferramenta ou um equipamento de aventura de até T$ 400 aparecer na sua mão ou em um espaço adjacente. O item dura até o fim da cena, ou até deixar sua posse.` },
    { chave: 'alimentarSeDoPavor', nome: 'Alimentar-se do Pavor', deuses: ['kallyadranoch', 'megalokk'], magica: false,
      texto: `Quando uma criatura em alcance curto sob efeito de uma condição de medo morre, você recebe pontos de vida temporários iguais ao dobro do seu ND, que duram até o fim da cena.` },
    { chave: 'almaDeMudanca', nome: 'Alma de Mudança', deuses: ['thwor', 'valkaria'], magica: false,
      texto: `No início de cada aventura, você pode trocar uma quantidade de poderes (limitada por sua Sabedoria) por poderes diferentes cujos pré-requisitos cumpra. Você não pode trocar este poder.` },
    { chave: 'andarilhoCarregado', nome: 'Andarilho Carregado', deuses: ['valkaria'], magica: false,
      texto: `Sua mochila de aventureiro não conta no seu limite de itens vestidos e, se estiver vestindo uma dessas mochilas, você pode usar Sabedoria para estabelecer seu limite de carga (em vez de Força). A critério do mestre, este poder pode ser aplicado a outro item equivalente (como uma mochila de carga).` },
    { chave: 'armadilhaDivina', nome: 'Armadilha Divina', deuses: ['hyninn'], magica: true,
      texto: `Você recebe um poder de Armadilha do caçador (Tormenta20, p. 50) a sua escolha. Por ser criada a partir de energia divina, essa armadilha pode ser preparada em locais sem os materiais propícios.` },
    { chave: 'armaduraDeOssos', nome: 'Armadura de Ossos', deuses: ['tenebra'], magica: true,
      texto: `Você pode gastar uma ação de movimento e 2 PM para receber +2 na Defesa e em Intimidação, e redução de corte, frio e trevas 5 até o fim da cena.` },
    { chave: 'armasDaDestruicao', nome: 'Armas da Destruição', deuses: ['arsenal'], magica: false,
      texto: `Você recebe +1 nas rolagens de dano e no multiplicador de crítico com armas nas quais é proficiente.` },
    { chave: 'armasDaSelvageria', nome: 'Armas da Selvageria', deuses: ['megalokk'], magica: false,
      texto: `Para você, armas naturais são armas favoritas de Megalokk. Você recebe +2 em rolagens de dano com elas, pode usar Abençoar Arma (Tormenta20, p. 57) nelas e, quando usa esse poder ou a magia Armamento da Natureza, pode aplicar seus benefícios a todas as suas armas naturais (sem custo adicional).` },
    { chave: 'aventureiroInquieto', nome: 'Aventureiro Inquieto', deuses: ['valkaria'], magica: false,
      texto: `Uma vez por busca (Tormenta20, p. 278), você pode rolar novamente um teste recém-realizado (mas deve aceitar o novo resultado) e, quando recebe uma recompensa ou um castigo aleatório por uma busca (incluindo rolagens na Tabela 8-1; Tormenta20, p. 328), rola dois dados e escolhe entre os dois resultados.` },
    { chave: 'baforadaDraconica', nome: 'Baforada Dracônica', deuses: ['kallyadranoch'], magica: false,
      texto: `Escolha um elemento entre ácido, eletricidade, fogo, frio, luz ou trevas (uma vez feita, essa escolha não pode ser mudada). Uma vez por rodada, você pode gastar PM (limitados por sua Constituição) para desferir um sopro elemental em uma criatura em alcance curto. Para cada PM que você gastar, o alvo sofre 1d10 pontos de dano do tipo escolhido (Reflexos CD Con reduz à metade). Recarga (movimento).` },
    { chave: 'barreiraDeCoral', nome: 'Barreira de Coral', deuses: ['oceano'], magica: true,
      texto: `Você pode gastar uma ação de movimento e 3 PM para cobrir seu corpo de coral. Até o fim da cena, você recebe +5 na Defesa e, sempre que sofrer um ataque corpo a corpo, o atacante sofre dano de perfuração igual a 1d6 + sua Constituição. Para cada patamar acima de iniciante, esse dano aumenta em +1d6.` },
    { chave: 'beloPresente', nome: 'Belo Presente', deuses: ['wynna'], magica: false,
      texto: `Uma vez por cena, você pode pedir a Wynna o conhecimento de uma magia que tenha visto sendo lançada nessa aventura e que seja de um círculo a que você tenha acesso. Gaste uma ação padrão e faça um teste de Religião (CD 15 + custo em PM da magia). Se passar, você pode lançar essa magia até o fim do seu próximo turno (pagando seus custos normais).` },
    { chave: 'bibliotecaDivina', nome: 'Biblioteca Divina', deuses: ['tannatoh'], magica: false,
      texto: `Você recebe uma perícia treinada. A cada patamar de jogo (Tormenta20, p. 35) acima de iniciante, recebe mais uma perícia treinada.` },
    { chave: 'cancioneiroDaEsperanca', nome: 'Cancioneiro da Esperança', deuses: ['marah'], magica: false,
      texto: `Você pode gastar uma ação padrão e 2 PM para entoar uma canção de superação e paz. Criaturas escolhidas (limitadas por seu Carisma) em alcance curto recebem +2 em testes (exceto testes de ataque) e +3m de deslocamento até o fim da cena. Se uma criatura afetada for executar uma ação hostil, perde esses bônus.` },
    { chave: 'cerimonialistaDivino', nome: 'Cerimonialista Divino', deuses: ['linwu'], magica: false,
      texto: `Uma vez por dia, você pode gastar 1 hora para executar uma cerimônia tradicional que afeta até 1 + seu Carisma criaturas por 1 dia. Faça um teste de Religião com um bônus igual ao seu Carisma. Para cada 10 pontos do resultado, cada criatura afetada recebe um dado de auxílio. Quando faz um teste de atributo ou perícia (exceto Enganação, Furtividade e Ladinagem), a criatura pode gastar um deles para receber +1d6 de bônus no teste. Para criaturas que gastarem T$ 25 em oferendas no ritual, esse bônus muda para +1d8.` },
    { chave: 'chamadoMonstruoso', nome: 'Chamado Monstruoso', deuses: ['megalokk'], magica: true,
      texto: `Você aprende e pode lançar Conjurar Monstro e pode lançar e sustentar essa magia sem violar suas Obrigações & Restrições. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'companheiroCeleste', nome: 'Companheiro Celeste', deuses: ['lena', 'marah'], magica: false,
      texto: `Você possui um luminar (veja p. 277) que o acompanha como um parceiro iniciante. Se perder esse luminar, você pode receber outro com uma cerimônia que exige 1 dia e T$ 100 em oferendas.` },
    { chave: 'companheiroSilvestre', nome: 'Companheiro Silvestre', deuses: ['allihanna'], magica: false,
      texto: `Você possui um espírito da natureza que o acompanha como um parceiro perseguidor iniciante. Alternativamente, se você tiver o suplemento Ameaças de Arton, pode receber um bogum iniciante (p. 190). Se perder esse parceiro, você pode receber outro com uma cerimônia que exige 1 dia e T$ 100 em oferendas.` },
    { chave: 'conviccaoAmbiciosa', nome: 'Convicção Ambiciosa', deuses: ['valkaria'], magica: false,
      texto: `Quando luta em desvantagem (um encontro contra o dobro de inimigos que seu grupo, ou com ND maior que o do grupo), você recebe +2 em testes de perícia até o fim da cena. Além disso, se houver um ou mais inimigos de ND igual ou maior que seu nível, você recebe uma ação padrão extra em seu primeiro turno de combate.` },
    { chave: 'corromperEquipamento', nome: 'Corromper Equipamento', deuses: ['aharadak'], magica: false,
      texto: `Você pode gastar 2 PM para cobrir uma arma, um escudo ou um esotérico que esteja empunhando com carapaça quitinosa. Até o fim da cena, o item recebe os benefícios de matéria vermelha (Tormenta20, p. 167), cumulativo com outros materiais especiais. Se usar este poder em uma arma produzida com Armamento Aberrante, seu custo é reduzido em –1 PM.` },
    { chave: 'curarOEspirito', nome: 'Curar o Espírito', deuses: ['lena'], magica: false,
      texto: `Você pode gastar uma ação completa para inspirar esperança em uma criatura que possa tocar. Faça um teste de Carisma (CD 10). Se você passar, a criatura recupera 1d4+1 PM. Você só pode usar este poder uma vez por dia numa mesma criatura.` },
    { chave: 'discursoConciliador', nome: 'Discurso Conciliador', deuses: ['marah'], magica: false,
      texto: `Quando faz um teste de Diplomacia para mudar atitude, você pode rolar dois dados e usar o melhor resultado ou ambos (como se tivesse usado mudar atitude duas vezes). Se passar em ambos, as mudanças de atitude são cumulativas.` },
    { chave: 'domDaFurtividade', nome: 'Dom da Furtividade', deuses: ['hyninn'], magica: false,
      texto: `Você soma sua Sabedoria em Furtividade e, para você, lançar magias é um ato pouco chamativo, o que reduz a penalidade para se esconder após conjurar para –10 (mas você ainda precisa de gestos e palavras).` },
    { chave: 'domDaVontade', nome: 'Dom da Vontade', deuses: ['khalmyr'], magica: false,
      texto: `Você recebe +2 em Vontade e, uma vez por cena, quando passa em um teste de Vontade contra um efeito de um inimigo ou de um perigo apresentado pelo mestre, recebe 1d4 PM temporários.` },
    { chave: 'domDosSegredos', nome: 'Dom dos Segredos', deuses: ['sszzaas'], magica: false,
      texto: `Você pode gastar uma ação padrão e 2 PM para suplicar a Sszzaas por um segredo místico. Faça um teste de Carisma (CD 10, +2 para cada vez que usou este poder no mesmo dia). Se passar, você aprende e pode lançar uma magia de 1º círculo até o fim da cena (atributo-chave Car ou o seu atributo de conjuração, se houver).` },
    { chave: 'egideDosMares', nome: 'Égide dos Mares', deuses: ['oceano'], magica: false,
      texto: `Você possui um espírito das águas que o acompanha como um parceiro guardião iniciante. Alternativamente, se você tiver o suplemento Ameaças de Arton, pode receber um escudeiro iniciante (p. 191). Em ambos os casos, se perder esse parceiro, você pode receber outro com uma cerimônia que exige 1 dia e T$ 100 em oferendas.` },
    { chave: 'espalharACorrupcao', nome: 'Espalhar a Corrupção', deuses: ['aharadak'], magica: false,
      texto: `Quando chega em uma comunidade, você pode gastar um dia e fazer um teste de Religião (CD 20). Se passar, você planta a semente da corrupção no coração das pessoas em uma área equivalente a uma aldeia, um castelo ou um bairro de uma cidade grande. Por uma semana, ou até você partir do lugar, a categoria de atitude dessas pessoas em relação umas às outras piora em um passo, à medida que o senso moral delas se deteriora e seus piores desejos vêm à tona. Isso pode ser útil para gerar conflitos entre elas, embora caiba a você descobrir exatamente como se aproveitar deles.` },
    { chave: 'espiritoAnimal', nome: 'Espírito Animal', deuses: ['allihanna'], magica: true,
      texto: `Você pode gastar uma ação de movimento e 2 PM para conjurar um espírito animal que o envolve e luta com você. Até o fim da cena, você não pode ser flanqueado e recebe 10 PV temporários e uma arma natural (dano 1d6, crítico x2, tipo a sua escolha entre corte, impacto ou perfuração). Uma vez por rodada, quando usa a ação agredir para atacar com outra arma, pode gastar 1 PM para fazer um ataque corpo a corpo extra com essa arma. Quando usa este poder, você pode gastar PM adicionais (custo total limitado por sua Sabedoria). Para cada PM adicional, os PV temporários aumentam em +5.` },
    { chave: 'espiritoDoConhecimento', nome: 'Espírito do Conhecimento', deuses: ['tannatoh'], magica: true,
      texto: `Você pode gastar uma ação padrão e 2 PM para invocar uma manifestação do saber em um espaço desocupado em alcance curto. Ela é um espírito Minúsculo que tem deslocamento de voo 6m, Força nula, Defesa 15, 1 PV, visão no escuro e falha em qualquer teste oposto. No início de seus turnos, ela pode usar a ação movimentar-se uma vez. Você pode perceber tudo que a manifestação for capaz de perceber e pode lançar magias a partir dela (exceto magias de alcance pessoal com alvo você). A manifestação desaparece quando morre ou no fim da cena.` },
    { chave: 'estouroDaTrobada', nome: 'Estouro da Trobada', deuses: ['allihanna'], magica: false,
      texto: `Você pode gastar uma ação completa e 2 PM para convocar uma manada de trobos (ou outro animal da região) em um ponto desocupado a sua escolha em alcance curto com duração sustentada. A manada é Enorme e pode passar pelo espaço de outras criaturas. Você pode gastar uma ação de movimento para mover a manada 12m em linha reta. Criaturas pelas quais ela passar sofrem 3d6 pontos de dano de impacto e ficam caídas (Fort CD Sab reduz à metade e evita a condição).` },
    { chave: 'exaltarHonra', nome: 'Exaltar Honra', deuses: ['linwu'], magica: false,
      texto: `Você pode gastar 2 PM para gerar uma aura de honradez de 9m de raio que dura até o fim da cena. Dentro dessa área, devotos de Lin-Wu e personagens que sigam algum código de conduta (como Código de Honra ou Código do Herói) recebem +5 em Diplomacia e Nobreza, e todas as criaturas na área sofrem –5 em perícias desonradas (Enganação, Furtividade e Ladinagem). Apenas personagens com a habilidade Abençoado ou Devoto Fiel podem escolher este poder.` },
    { chave: 'expurgarADerrota', nome: 'Expurgar a Derrota', deuses: ['arsenal'], magica: false,
      texto: `Se estiver com 0 PM, você pode gastar seus pontos de vida (exceto PV temporários) no lugar de mana, à taxa de 3 PV por 1 PM. Você não pode reduzir seus PV a 0 ou menos dessa forma e não pode usar este poder se estiver sob efeito de ter descumprido suas Obrigações & Restrições. Pontos de vida gastos dessa forma só podem ser recuperados com descanso.` },
    { chave: 'familiarElemental', nome: 'Familiar Elemental', deuses: ['wynna'], magica: false,
      texto: `Você possui um espírito arcano que o acompanha como um familiar com as habilidades de um adepto iniciante. Alternativamente, se você tiver o suplemento Ameaças de Arton, pode receber um familiar elemental iniciante, escolhido entre aquin'ne, t'peel, pakk ou terrier (p. 88). Em ambos os casos, se perder esse parceiro, você pode receber outro com uma cerimônia que exige 1 dia e T$ 100 em oferendas.` },
    { chave: 'ferramentasDaGuerra', nome: 'Ferramentas da Guerra', deuses: ['arsenal'], magica: true,
      texto: `Uma vez por dia, você pode gastar 1 hora e T$ 10 por item para abençoar uma quantidade de itens limitada por sua Sabedoria. Armas abençoadas dessa forma fornecem +2 em rolagens de dano, e armaduras e escudos fornecem RD 2. Se o usuário de um item abençoado for derrotado em combate, o item é destruído. Os efeitos da bênção duram 1 dia.` },
    { chave: 'golpeSemantico', nome: 'Golpe Semântico', deuses: ['tannatoh'], magica: false,
      texto: `Você pode substituir testes de Diplomacia e Intimidação por Conhecimento.` },
    { chave: 'golpeTempestuoso', nome: 'Golpe Tempestuoso', deuses: ['oceano'], magica: false,
      texto: `Quando acerta um ataque corpo a corpo, você pode gastar 2 PM. Se fizer isso, a criatura é empurrada 3m em uma direção a sua escolha e fica desprevenida por 1 rodada.` },
    { chave: 'imolacaoSagrada', nome: 'Imolação Sagrada', deuses: ['azgher', 'thyatis'], magica: true,
      texto: `Você pode gastar uma ação padrão e 1 PM para cobrir seus braços com chamas com duração sustentada. Nesse estado, seus ataques corpo a corpo causam +1d6 pontos de dano de fogo.` },
    { chave: 'jubiloNaDor', nome: 'Júbilo na Dor', deuses: ['aharadak'], magica: false,
      texto: `Quando causa ou sofre dano, você recebe redução de dano 1. Esse efeito é cumulativo e limitado por sua Sabedoria e termina se você passar 1 rodada sem causar ou sofrer dano.` },
    { chave: 'juristaDivino', nome: 'Jurista Divino', deuses: ['linwu', 'khalmyr'], magica: false,
      texto: `Você pode usar Sabedoria para Nobreza (em vez de Inteligência) e pode usar essa perícia no lugar de Diplomacia e Intimidação.` },
    { chave: 'magiaCaotica', nome: 'Magia Caótica', deuses: ['nimb'], magica: false,
      texto: `Quando lança uma magia, você pode gastar +2 PM. Se fizer isso, a CD para resistir a essa magia é calculada com 1d20 + seus modificadores, em vez de 10 + seus modificadores.` },
    { chave: 'magiaPiedosa', nome: 'Magia Piedosa', deuses: ['lena', 'thyatis'], magica: false,
      texto: `Quando lança uma magia que causa dano, você pode fazer com que ela cause dano não letal.` },
    { chave: 'magiaVenenosa', nome: 'Magia Venenosa', deuses: ['sszzaas'], magica: false,
      texto: `Suas magias com resistência Fortitude recebem o seguinte aprimoramento. +1 PM: além do normal, criaturas que falharem perdem 1d12 PV por veneno, ou 1d6 se passarem na resistência.` },
    { chave: 'mantoArdiloso', nome: 'Manto Ardiloso', deuses: ['sszzaas'], magica: true,
      texto: `Você aprende a magia Disfarce Ilusório (CD Car). Na primeira vez que interage com alguém enquanto está sob efeito dessa magia, você recebe +10 no teste de Diplomacia para mudar a atitude dela. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'marRevolto', nome: 'Mar Revolto', deuses: ['oceano'], magica: false,
      texto: `Você pode gastar 1 PM para gerar uma aura de 6m de raio com duração sustentada. No início de seus turnos, criaturas a sua escolha na área devem passar em um teste de Acrobacia (CD Sab, +5 se a criatura estiver dentro da água) para não cair.` },
    { chave: 'mediadorDaTempestade', nome: 'Mediador da Tempestade', deuses: ['aharadak'], magica: false,
      texto: `Você pode se comunicar com lefeu inteligentes (Int –3 ou maior) livremente e recebe +5 em testes de Diplomacia e Intuição com criaturas da Tormenta e devotos de Aharadak.` },
    { chave: 'mestreDeSi', nome: 'Mestre de Si', deuses: ['linwu'], magica: false,
      texto: `Você passa automaticamente no primeiro teste de Vontade contra um efeito de um inimigo que fizer a cada cena.` },
    { chave: 'mordidaDeVibora', nome: 'Mordida de Víbora', deuses: ['sszzaas'], magica: false,
      texto: `Você recebe uma arma natural de mordida (dano 1d6, crítico x2, perfuração). Suas presas são retráteis e podem armazenar até 2 doses de veneno de contato. Uma vez por rodada, quando usa a ação agredir para atacar com outra arma, você pode gastar 1 PM para fazer um ataque corpo a corpo extra com a mordida. Se acertar, pode inocular uma das doses de veneno no alvo.` },
    { chave: 'navegadorSagrado', nome: 'Navegador Sagrado', deuses: ['oceano'], magica: false,
      texto: `Você pode usar Sabedoria para Pilotagem (em vez de Destreza) e, enquanto estiver em uma embarcação aquática, suas magias divinas custam –2 PM.` },
    { chave: 'nimb', nome: 'Nimb', deuses: ['nimb'], magica: true,
      texto: `Você é Nimb. Ou um filho ou filha dele. Ou uma casca de banana na qual ele escorregou certa vez. Você pode gastar uma ação padrão e 2 PM para gerar uma habilidade única. Para isso, role 1d6 para a área/alvo e 1d6 para o efeito:
Área/alvo (1d6): 1 — criaturas em um cone de 6m; 2 — até 1d3 criaturas em alcance médio; 3 — criaturas em um raio de 9m; 4 — criaturas em uma esfera com 6m de raio em alcance curto; 5 — criaturas em 1d3 linhas de 15m; 6 — criaturas escolhidas em alcance curto.
Efeito (1d6): 1 — ficam verdes por 1 dia e sofrem –2 em testes baseados em Carisma; 2 — curam 3d6 PV; 3 — em seu próximo teste, rolam 2 dados e você escolhe o resultado; 4 — perdem 3d6+3 pontos de vida; 5 — recebem 1d4 PM temporários que duram 1 rodada; 6 — podem usar Poder Oculto (Tormenta20, p. 134) até o fim da cena.` },
    { chave: 'oDobroOuNada', nome: 'O Dobro ou Nada', deuses: ['hyninn', 'nimb'], magica: false,
      texto: `Quando usa uma habilidade com custo em PM, você pode pagar o dobro desse custo (após aplicar efeitos que alterem o custo) para aumentar a CD da habilidade em +5. Se pelo menos um alvo passar no teste de resistência, você fica alquebrado. Este poder não pode ser usado em magias, incluindo simuladas.` },
    { chave: 'oFuturoQueVierDisso', nome: 'O Futuro que Vier Disso', deuses: ['thwor'], magica: false,
      texto: `Quando faz um teste, você pode rolar um dado a sua escolha (d4 a d20) e somar o resultado a esse teste. Quando você faz isso, o mestre recebe um dado do mesmo tipo, que pode gastar para aplicar como penalidade em um de seus testes até o fim da próxima sessão. Você não pode usar este poder novamente na mesma sessão até que o mestre use o dado que recebeu.` },
    { chave: 'oSolQueNosAquece', nome: 'O Sol que nos Aquece', deuses: ['allihanna', 'azgher'], magica: true,
      texto: `Você pode gastar uma ação padrão e 2 PM para projetar uma aura de luz solar em um raio de 6m. Nessa área, habilidades mágicas de fogo ou luz e relacionadas a plantas (como Controlar Plantas) custam –1 PM (cumulativo com outras reduções) e criaturas com sensibilidade a luz e mortos-vivos ficam vulneráveis.` },
    { chave: 'palavraDePoder', nome: 'Palavra de Poder', deuses: ['tannatoh'], magica: true,
      texto: `Você aprende e pode lançar Comando. Caso aprenda novamente essa magia, seu custo diminui em –1 PM.` },
    { chave: 'passoSombrio', nome: 'Passo Sombrio', deuses: ['tenebra'], magica: true,
      texto: `Uma vez por rodada, você pode gastar 2 PM para se teleportar para um espaço desocupado em alcance curto. Se tanto você quanto esse espaço estiverem sob escuridão, o custo deste poder diminui em –1 PM. Você não pode usar este poder se estiver imóvel.` },
    { chave: 'perceberFarsas', nome: 'Perceber Farsas', deuses: ['tannatoh'], magica: false,
      texto: `Você recebe +5 em Intuição e se torna imune a efeitos de ilusão.` },
    { chave: 'pilarDeHeredrimm', nome: 'Pilar de Heredrimm', deuses: ['khalmyr'], magica: false,
      texto: `Você pode gastar 2 PM para receber +2 na Defesa e redução de dano 5 até o fim da cena ou até encerrar este poder (uma ação livre). Enquanto esse efeito estiver ativo, seu deslocamento é reduzido à metade.` },
    { chave: 'poderDoVinculo', nome: 'Poder do Vínculo', deuses: ['wynna'], magica: false,
      texto: `Você pode gastar uma ação de movimento e uma quantidade de PM (limitada ao círculo de magias a que tem acesso) para tocar em uma criatura capaz de lançar magias. O custo em PM da próxima magia que ela lançar diminui em um valor igual aos PM que você gastou.` },
    { chave: 'poderSemLimites', nome: 'Poder Sem Limites', deuses: ['kallyadranoch'], magica: false,
      texto: `A CD e os limites de PM de suas habilidades (exceto magias e habilidades que as simulem) aumentam em um valor igual ao seu patamar.` },
    { chave: 'proeminenciaSolar', nome: 'Proeminência Solar', deuses: ['azgher'], magica: false,
      texto: `Suas magias que causam dano de fogo e que têm um teste de resistência recebem o seguinte aprimoramento. +1 PM: criaturas que falhem na resistência ficam em chamas e lentas até apagarem as chamas.` },
    { chave: 'quebrarEncanto', nome: 'Quebrar Encanto', deuses: ['khalmyr'], magica: true,
      texto: `Você recebe +2 em testes de ataque para quebrar. Quando usa essa manobra, você pode gastar 2 PM. Se você acertar o ataque, o item e seu portador sofrem o efeito de Dissipar Magia, usando o resultado do teste de quebrar como teste de Misticismo e CD para resistir.` },
    { chave: 'redirecionarDestino', nome: 'Redirecionar Destino', deuses: ['thyatis'], magica: true,
      texto: `No início de cada dia, role um d20 e anote seu valor. Uma vez por rodada, quando uma criatura em alcance curto faz um teste, você pode gastar 3 PM para substituir o resultado do d20 desse teste pelo último valor anotado para este poder. O resultado do d20 substituído se torna seu novo valor anotado.` },
    { chave: 'remorsoDoBelicista', nome: 'Remorso do Belicista', deuses: ['marah'], magica: false,
      texto: `Uma vez por rodada, quando sofre dano de um inimigo, você pode gastar 1 PM. Se fizer isso, ele sofre uma penalidade cumulativa de –2 em testes de ataque e rolagens de dano até o fim da cena. Mental.` },
    { chave: 'resplendorDivino', nome: 'Resplendor Divino', deuses: ['azgher'], magica: true,
      texto: `Você pode gastar 2 PM para gerar uma aura de luz solar com 9m de raio que dura até o fim da cena. Além de sofrer os efeitos de exposição à luz, criaturas dentro da aura perdem toda camuflagem por escuridão e efeitos semelhantes (como da cobertura de sombras do aprimoramento da magia Escuridão).` },
    { chave: 'saqueCelestial', nome: 'Saque Celestial', deuses: ['linwu'], magica: false,
      texto: `Você pode gastar 1 PM para sacar ou guardar uma arma como uma ação livre. Se sacar sua arma e fizer um ataque corpo a corpo no mesmo turno, você recebe +2 nesse teste de ataque e seu dano aumenta em dois passos (apenas uma vez contra cada criatura por cena).` },
    { chave: 'soOsLoucosSabem', nome: 'Só os Loucos Sabem', deuses: ['nimb'], magica: false,
      texto: `Role duas perícias na Tabela 6-6 (Tormenta20, p. 279). Você se torna treinado nelas (se já for, recebe +3 nessa perícia). No começo de cada dia, você pode gastar 3 PM para rolar novas perícias.` },
    { chave: 'sorvoDeMana', nome: 'Sorvo de Mana', deuses: ['wynna'], magica: false,
      texto: `Sempre que falhar no teste de resistência contra uma magia de um inimigo, você recupera uma quantidade de PM igual ao círculo dela.` },
    { chave: 'temorArcano', nome: 'Temor Arcano', deuses: ['kallyadranoch'], magica: false,
      texto: `Quando um inimigo em alcance médio sob efeito de uma condição de medo falha em um teste de resistência contra uma de suas magias, você recebe 1 PM temporário cumulativo. Você pode ganhar um máximo de PM temporários por cena igual ao seu nível, e eles desaparecem no fim da cena.` },
    { chave: 'terrorProfundo', nome: 'Terror Profundo', deuses: ['kallyadranoch', 'megalokk', 'thwor'], magica: false,
      texto: `Você recebe +2 em Intimidação e na CD de seus efeitos de medo.` },
    { chave: 'toqueDeNaoVida', nome: 'Toque de Não Vida', deuses: ['tenebra'], magica: true,
      texto: `Você pode gastar uma ação de movimento e 2 PM para fornecer a si mesmo ou a uma criatura adjacente 2d12 PV temporários (que são sempre os primeiros a serem perdidos) e, enquanto os PV temporários durarem, camuflagem leve.` },
    { chave: 'transbordarCura', nome: 'Transbordar Cura', deuses: ['lena'], magica: false,
      texto: `Quando você usa um efeito de cura, quaisquer pontos de vida excedentes desse efeito se tornam pontos de vida temporários, até um valor máximo igual ao dobro do nível do alvo.` },
    { chave: 'trilhaDesimpedida', nome: 'Trilha Desimpedida', deuses: ['allihanna'], magica: true,
      texto: `Você aprende e pode lançar a magia Caminhos da Natureza. Se aprender essa magia, o custo dela diminui em –1 PM.` },
    { chave: 'ushultt', nome: 'Ushultt', deuses: ['thwor'], magica: false,
      texto: `Escolha um de seus aliados como seu ushultt. Enquanto estiverem em alcance curto um do outro, vocês recebem +2 em testes de ataque e rolagens de dano (esse bônus aumenta para +3 se o ushultt também for duyshidakk). Você pode trocar seu ushultt uma vez por aventura.` },
    { chave: 'vitoriaAQualquerCusto', nome: 'Vitória a Qualquer Custo', deuses: ['arsenal'], magica: false,
      texto: `Quando faz um teste de ataque, de resistência ou de Guerra, você pode gastar 2 PM para rolar novamente esse teste. Você pode fazer isso várias vezes no mesmo teste, mas cada novo uso aumenta o custo em +1 PM.` },
  ],
};

// ── Índices e utilitários (montados uma vez, usados por todas as abas) ─
(function (G) {
  G.deusPorChave = {};
  G.deuses.forEach(d => { G.deusPorChave[d.chave] = d; });
  G.poderPorChave = {};
  G.poderes.forEach(p => { G.poderPorChave[p.chave] = p; });
  // Poderes de um deus, em ordem alfabética — a mesma ordem em que a
  // sub-aba e os seletores exibem. (Os 4 da lista do livro continuam
  // registrados em deus.basicos, citados no card do culto.)
  G.poderesDoDeus = function (chave) {
    if (!G.deusPorChave[chave]) return [];
    return G.poderes
      .filter(p => p.deuses.indexOf(chave) >= 0)
      .sort((a, b) => a.nome.localeCompare(b.nome, 'pt'));
  };
})(window.GA_DEVOTOS);
