// ════════════════════════════════════════════════════════════════════
//  ORIGENS-DATA.JS — as ORIGENS e seus BENEFÍCIOS (Frente 3, 28/09/2026)
//  Localização: /grifos-alados/js/origens-data.js
//
//  POR QUE ISTO EXISTE. Até agora a ficha só tinha o "Poder Único" de cada
//  origem (grupo `origem` em js/poderes-raca-origem-data.js). Faltava o que
//  a origem DÁ: uma lista de perícias e poderes de onde, pela regra, se
//  escolhe DOIS benefícios (Tormenta20, p. 85: "escolha dois benefícios
//  entre os listados"). Em Seguidor, por exemplo, dá para pegar 2 perícias,
//  OU 2 poderes, OU 1 + 1.
//
//  ESTÁGIO 1 (28/09/2026): as 35 origens do NÚCLEO (Tormenta20 Jogo do Ano,
//  Tabela 1-19, p. 85–95), conferidas uma a uma contra a tabela do livro E
//  contra o Poder Único que já tínhamos (o poder-assinatura de cada origem
//  bate com o campo `tags` do dado antigo).
//
//  Cada origem:
//    id, nome        como o livro imprime
//    livro, pagina   Tormenta20, página IMPRESSA
//    escolher        quantos benefícios se pega (2, salvo exceção)
//    pericias[]      as perícias oferecidas (uma delas conta como 1 benefício)
//    poderes[]       os poderes oferecidos (idem). O poder-assinatura da
//                    origem está aqui, no meio dos gerais.
//    flexiveis[]     "vagas" que o jogador preenche à vontade — "um poder de
//                    combate à sua escolha", "um poder da Tormenta…", etc.
//    nota            só quando o livro foge do padrão (Amnésico)
//
//  As "origens especiais" do Heróis de Arton (benefício ÚNICO fixo) entram
//  numa leva à parte — ver docs/origens-progresso.md.
//
//  Consumido por js/ficha.js (cartão 🌿, seletor de origem).
// ════════════════════════════════════════════════════════════════════
(function () {
  'use strict';

  window.GA_ORIGENS = [
    { id: 'acolito', nome: 'Acólito', livro: 't20', pagina: 85, escolher: 2,
      pericias: ['Cura', 'Religião', 'Vontade'],
      poderes: ['Medicina', 'Membro da Igreja', 'Vontade de Ferro'] },
    { id: 'amigo-dos-animais', nome: 'Amigo dos Animais', livro: 't20', pagina: 85, escolher: 2,
      pericias: ['Adestramento', 'Cavalgar'],
      poderes: ['Amigo Especial'] },
    { id: 'amnesico', nome: 'Amnésico', livro: 't20', pagina: 86, escolher: 3,
      pericias: [], poderes: ['Lembranças Graduais'],
      flexiveis: ['uma perícia à escolha do mestre', 'um poder à escolha do mestre'],
      nota: 'Em vez de escolher dois benefícios, o Amnésico recebe os três: uma perícia e um poder definidos pelo mestre, mais o poder Lembranças Graduais.' },
    { id: 'aristocrata', nome: 'Aristocrata', livro: 't20', pagina: 86, escolher: 2,
      pericias: ['Diplomacia', 'Enganação', 'Nobreza'],
      poderes: ['Comandar', 'Sangue Azul'] },
    { id: 'artesao', nome: 'Artesão', livro: 't20', pagina: 86, escolher: 2,
      pericias: ['Ofício', 'Vontade'],
      poderes: ['Frutos do Trabalho', 'Sortudo'] },
    { id: 'artista', nome: 'Artista', livro: 't20', pagina: 87, escolher: 2,
      pericias: ['Atuação', 'Enganação'],
      poderes: ['Atraente', 'Dom Artístico', 'Sortudo', 'Torcida'] },
    { id: 'assistente-de-laboratorio', nome: 'Assistente de Laboratório', livro: 't20', pagina: 88, escolher: 2,
      pericias: ['Ofício (alquimista)', 'Misticismo'],
      poderes: ['Esse Cheiro...', 'Venefício'],
      flexiveis: ['um poder da Tormenta à sua escolha'] },
    { id: 'batedor', nome: 'Batedor', livro: 't20', pagina: 88, escolher: 2,
      pericias: ['Furtividade', 'Percepção', 'Sobrevivência'],
      poderes: ['À Prova de Tudo', 'Estilo de Disparo', 'Sentidos Aguçados'] },
    { id: 'capanga', nome: 'Capanga', livro: 't20', pagina: 88, escolher: 2,
      pericias: ['Luta', 'Intimidação'],
      poderes: ['Confissão'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'charlatao', nome: 'Charlatão', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Enganação', 'Jogatina'],
      poderes: ['Alpinista Social', 'Aparência Inofensiva', 'Sortudo'] },
    { id: 'circense', nome: 'Circense', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Acrobacia', 'Atuação', 'Reflexos'],
      poderes: ['Acrobático', 'Torcida', 'Truque de Mágica'] },
    { id: 'criminoso', nome: 'Criminoso', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Enganação', 'Furtividade', 'Ladinagem'],
      poderes: ['Punguista', 'Venefício'] },
    { id: 'curandeiro', nome: 'Curandeiro', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Cura', 'Vontade'],
      poderes: ['Medicina', 'Médico de Campo', 'Venefício'] },
    { id: 'eremita', nome: 'Eremita', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Misticismo', 'Religião', 'Sobrevivência'],
      poderes: ['Busca Interior', 'Lobo Solitário'] },
    { id: 'escravo', nome: 'Escravo', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Atletismo', 'Fortitude', 'Furtividade'],
      poderes: ['Desejo de Liberdade', 'Vitalidade'] },
    { id: 'estudioso', nome: 'Estudioso', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Conhecimento', 'Guerra', 'Misticismo'],
      poderes: ['Aparência Inofensiva', 'Palpite Fundamentado'] },
    { id: 'fazendeiro', nome: 'Fazendeiro', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Adestramento', 'Cavalgar', 'Ofício (fazendeiro)', 'Sobrevivência'],
      poderes: ['Água no Feijão', 'Ginete'] },
    { id: 'forasteiro', nome: 'Forasteiro', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Cavalgar', 'Pilotagem', 'Sobrevivência'],
      poderes: ['Cultura Exótica', 'Lobo Solitário'] },
    { id: 'gladiador', nome: 'Gladiador', livro: 't20', pagina: 91, escolher: 2,
      pericias: ['Atuação', 'Luta'],
      poderes: ['Atraente', 'Pão e Circo', 'Torcida'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'guarda', nome: 'Guarda', livro: 't20', pagina: 91, escolher: 2,
      pericias: ['Investigação', 'Luta', 'Percepção'],
      poderes: ['Detetive', 'Investigador'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'herdeiro', nome: 'Herdeiro', livro: 't20', pagina: 91, escolher: 2,
      pericias: ['Misticismo', 'Nobreza', 'Ofício'],
      poderes: ['Comandar', 'Herança'] },
    { id: 'heroi-camponnes', nome: 'Herói Camponês', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Adestramento', 'Ofício'],
      poderes: ['Coração Heroico', 'Sortudo', 'Surto Heroico', 'Torcida'] },
    { id: 'marujo', nome: 'Marujo', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Atletismo', 'Jogatina', 'Pilotagem'],
      poderes: ['Acrobático', 'Passagem de Navio'] },
    { id: 'mateiro', nome: 'Mateiro', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Atletismo', 'Furtividade', 'Sobrevivência'],
      poderes: ['Lobo Solitário', 'Sentidos Aguçados', 'Vendedor de Carcaças'] },
    { id: 'membro-de-guilda', nome: 'Membro de Guilda', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Diplomacia', 'Enganação', 'Misticismo', 'Ofício'],
      poderes: ['Foco em Perícia', 'Rede de Contatos'] },
    { id: 'mercador', nome: 'Mercador', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Diplomacia', 'Intuição', 'Ofício'],
      poderes: ['Negociação', 'Proficiência', 'Sortudo'] },
    { id: 'minerador', nome: 'Minerador', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Atletismo', 'Fortitude', 'Ofício (minerador)'],
      poderes: ['Ataque Poderoso', 'Escavador', 'Sentidos Aguçados'] },
    { id: 'nomade', nome: 'Nômade', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Cavalgar', 'Pilotagem', 'Sobrevivência'],
      poderes: ['Lobo Solitário', 'Mochileiro', 'Sentidos Aguçados'] },
    { id: 'pivete', nome: 'Pivete', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Furtividade', 'Iniciativa', 'Ladinagem'],
      poderes: ['Acrobático', 'Aparência Inofensiva', 'Quebra-Galho'] },
    { id: 'refugiado', nome: 'Refugiado', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Fortitude', 'Reflexos', 'Vontade'],
      poderes: ['Estoico', 'Vontade de Ferro'] },
    { id: 'seguidor', nome: 'Seguidor', livro: 't20', pagina: 94, escolher: 2,
      pericias: ['Adestramento', 'Ofício'],
      poderes: ['Antigo Mestre', 'Proficiência', 'Surto Heroico'] },
    { id: 'selvagem', nome: 'Selvagem', livro: 't20', pagina: 94, escolher: 2,
      pericias: ['Percepção', 'Reflexos', 'Sobrevivência'],
      poderes: ['Lobo Solitário', 'Vida Rústica', 'Vitalidade'] },
    { id: 'soldado', nome: 'Soldado', livro: 't20', pagina: 94, escolher: 2,
      pericias: ['Fortitude', 'Guerra', 'Luta', 'Pontaria'],
      poderes: ['Influência Militar'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'taverneiro', nome: 'Taverneiro', livro: 't20', pagina: 95, escolher: 2,
      pericias: ['Diplomacia', 'Jogatina', 'Ofício (cozinheiro)'],
      poderes: ['Gororoba', 'Proficiência', 'Vitalidade'] },
    { id: 'trabalhador', nome: 'Trabalhador', livro: 't20', pagina: 95, escolher: 2,
      pericias: ['Atletismo', 'Fortitude'],
      poderes: ['Atlético', 'Esforçado'] },

    // ── ORIGENS ESPECIAIS (Heróis de Arton, "Novas origens", p. 46–53) ──
    //  Estrutura DIFERENTE do núcleo: um benefício ÚNICO fixo (não se
    //  escolhe 2) e uma linha de itens. Notas do livro: "Efeitos de origens
    //  contam como habilidades para fins de acúmulo"; e se o benefício
    //  treina uma perícia em que você já é treinado, treina outra de classe.
    { id: 'bacharel', nome: 'Bacharel', livro: 'herois', pagina: 46, tipo: 'especial',
      beneficio: 'Você é treinado em Conhecimento, Diplomacia e Nobreza. Além disso, uma vez por cena pode usar Diplomacia para mudar atitude como uma ação livre.',
      itens: 'Tabardo com o símbolo de Khalmyr, uma coleção de livros a sua escolha.' },
    { id: 'boticario', nome: 'Boticário', livro: 'herois', pagina: 46, tipo: 'especial',
      beneficio: 'Você é treinado em Cura e Ofício (alquimista). Além disso, pode fabricar poções de duas fórmulas de 1º círculo a sua escolha, como se tivesse o poder Alquimista Iniciado (Tormenta20, p. 68).',
      itens: 'Bálsamo restaurador, instrumentos de Ofício (alquimista), maleta de medicamentos.' },
    { id: 'cacador-de-ratos', nome: 'Caçador de Ratos', livro: 'herois', pagina: 46, tipo: 'especial',
      beneficio: 'Você é treinado em Furtividade, Investigação e Sobrevivência, e recebe +2 em testes de perícias contra criaturas de duas categorias de tamanho menor que a sua (mínimo Minúsculas).',
      itens: 'Clava, um gato (um parceiro perseguidor iniciante), T$ 50 (recompensa por sua última caçada).' },
    { id: 'cao-de-briga', nome: 'Cão de Briga', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Na primeira vez a cada cena em que você faz a ação agredir, pode fazer um ataque extra.',
      itens: 'Manoplas ou uma arma marcial.' },
    { id: 'carcereiro', nome: 'Carcereiro', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você recebe +2 em testes contra efeitos mentais, Enganação, Furtividade e Intimidação.',
      itens: 'Algemas, lampião, uma arma de até T$ 500 a sua escolha, que você pode ou não ter obtido de um detento.' },
    { id: 'carpinteiro-de-guilda', nome: 'Carpinteiro de Guilda', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (artesão). Além disso, recebe redução de corte 2 e, em suas mãos, armas de corte ignoram 5 pontos de redução de dano.',
      itens: 'Instrumentos de Ofício (carpinteiro), uma arma de corte a sua escolha.' },
    { id: 'catador-da-catastrofe', nome: 'Catador da Catástrofe', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você é treinado em Fortitude e Percepção. No início de cada aventura, pode fazer um teste de Percepção (CD 15 + metade do seu nível). Se passar, encontra um tesouro correspondente a seu próprio ND, escolhido pelo mestre ou rolado nas colunas Dinheiro e Itens da Tabela 8-1: Tesouro por Nível de Desafio (Tormenta20, p. 328).',
      itens: 'Dois equipamentos de aventura de até T$ 150 cada a sua escolha.' },
    { id: 'chef-hynne', nome: 'Chef Hynne', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (cozinheiro). Quando prepara um prato especial, seu benefício dura mais 1 dia (se for um benefício com um uso diário, ele pode ser usado novamente nesse dia).',
      itens: 'Cutelo (mesmas estatísticas de uma foice), instrumentos de cozinheiro aprimorados.' },
    { id: 'cirurgiao-barbeiro', nome: 'Cirurgião-Barbeiro', livro: 'herois', pagina: 48, tipo: 'especial',
      beneficio: 'Você é treinado em Cura e Ofício (barbeiro). Além disso, pode gastar uma ação completa e 2 PM para remover uma das seguintes condições de uma criatura adjacente: abalado, alquebrado, apavorado, atordoado, cego, confuso, debilitado, enjoado, envenenado, esmorecido, exausto, fascinado, fatigado, fraco, frustrado, lento, ofuscado, paralisado, pasmo e surdo. Contudo, a criatura também perde 1d6 pontos de vida.',
      itens: 'Dente falso (p. 227), instrumentos de barbeiro, maleta de medicamentos.' },
    { id: 'citadino-abastado', nome: 'Citadino Abastado', livro: 'herois', pagina: 48, tipo: 'especial',
      beneficio: 'Você é treinado em Nobreza e em um Ofício a sua escolha. Se estiver em uma cidade grande (a critério do mestre), pode gastar tibares para aprender algum conhecimento local útil. O custo é T$ 10 x seu nível. Se fizer isso, escolha um poder de combate, de destino ou de uma de suas classes cujos pré-requisitos você cumpra (o mestre determina se um poder está disponível na cidade). Até o fim da aventura, ou até usar esta habilidade novamente, você pode usar o poder escolhido por uma cena.',
      itens: 'Uma arma, armadura, ferramenta ou vestuário no valor de até T$ 500.' },
    { id: 'cocheiro', nome: 'Cocheiro', livro: 'herois', pagina: 48, tipo: 'especial',
      beneficio: 'Você é treinado em Adestramento e Pilotagem e, quando está conduzindo um veículo, você e o veículo recebem +2 na Defesa e em testes de resistência.',
      itens: 'Cavalo ou trobo, carroça.' },
    { id: 'construtor', nome: 'Construtor', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Fortitude e Ofício (pedreiro). Além disso, sabe encontrar pontos fracos em construções e estruturas. Pode pagar 2 PM para que você ou um aliado em alcance curto ignore 5 pontos da redução de dano de uma criatura ou objeto em alcance curto por uma cena.',
      itens: 'Instrumentos de pedreiro ou uma ferramenta pesada (mesmas estatísticas de uma maça ou lança, a sua escolha).' },
    { id: 'contrabandista', nome: 'Contrabandista', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Enganação e Ladinagem, e recebe +5 em testes de Ladinagem para ocultar itens em si mesmo ou em veículos. Além disso, sua capacidade de carga aumenta em 2 espaços.',
      itens: 'Uma arma de fogo, ou 10 doses de venenos, com preço total de até T$ 500.' },
    { id: 'coureiro', nome: 'Coureiro', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Fortitude e Ofício (coureiro). Além disso, pode gastar 10 minutos e T$ 10 para trabalhar em uma armadura de couro (incluindo couro batido, gibão de peles e brunea), aumentar a Defesa dela em +1 e reduzir sua penalidade de armadura em -2 por um dia.',
      itens: 'Faca de corte (como uma adaga, mas com dano de corte), instrumentos de coureiro, T$ 100 em itens alquímicos.' },
    { id: 'escriba', nome: 'Escriba', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Conhecimento e Ofício (escriba) e recebe o poder de bardo Lendas e Histórias (Tormenta20, p. 45). Se receber esse poder novamente, em seu lugar recebe um bônus de +5 ao rolar novamente um teste usando seu efeito.',
      itens: 'Instrumentos de escriba, organizador de pergaminhos, uma coleção de livros a sua escolha.' },
    { id: 'espiao', nome: 'Espião', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Enganação e Ladinagem. Além disso, escolha uma de suas perícias (exceto Luta ou Pontaria). Você pode usar Carisma como atributo-chave dessa perícia (em vez do atributo original).',
      itens: 'Estojo de disfarces, gazua, luneta, três doses de cosmético.' },
    { id: 'ferreiro-militar', nome: 'Ferreiro Militar', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (armeiro). Além disso, recebe +2 em rolagens de dano com martelos e marretas de qualquer tipo.',
      itens: 'Instrumentos de armeiro, martelo leve (p. 221).' },
    { id: 'freira', nome: 'Freira', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinada em Cura. Quando faz um teste para ajudar, você pode gastar 1 PM para aumentar o bônus da ajuda em +1d4 e, quando usa um efeito de cura, pode gastar 1 PM para aumentar esse efeito em +1 dado do mesmo tipo.',
      itens: 'Maleta de medicamentos, manto eclesiástico, símbolo sagrado.' },
    { id: 'goradista', nome: 'Goradista', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (cozinheiro) e, quando prepara um prato especial, pode gastar T$ 10 a mais para adicionar cobertura de gorad a ele. Além de seus benefícios normais, um prato especial com cobertura de gorad fornece 2 PM temporários por patamar do comensal.',
      itens: 'Instrumentos de cozinheiro, T$ 36 em ingredientes para produzir gorad quente.' },
    { id: 'insciente', nome: 'Insciente', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Sobrevivência e recebe resistência a magia +5.',
      itens: 'Uma arma simples ou ferramenta a sua escolha de até T$ 100.' },
    { id: 'interrogador', nome: 'Interrogador', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Intimidação e Investigação, e recebe +1 na margem de ameaça contra criaturas feridas (PV abaixo do total), pois aprendeu a bater onde mais dói.',
      itens: 'Um ou mais itens somando T$ 100 que pertenciam a antigas vítim... ahem, interrogados.' },
    { id: 'ladrao-de-tumulos', nome: 'Ladrão de Túmulos', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você é treinado em Ladinagem e Sobrevivência, e recebe +2 na Defesa e em testes de perícia contra mortos-vivos. Além disso, recebe redução de trevas 5 (ou, se for um morto-vivo, recupera +1 PV por dado de dano de trevas).',
      itens: 'Pá (mesmas estatísticas de uma lança), pé de cabra.' },
    { id: 'menestrel', nome: 'Menestrel', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você é treinado em Atuação e recebe um poder de Música de bardo, escolhido entre Balada Fascinante, Canção Assustadora e Melodia Curativa.',
      itens: 'Um instrumento musical de até T$ 35 a sua escolha.' },
    { id: 'mensageiro', nome: 'Mensageiro', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você recebe +3m em seu deslocamento e +2 em testes de resistência.',
      itens: 'Cavalo com sela, mochila de aventureiro, traje de viajante.' },
    { id: 'naufrago', nome: 'Náufrago', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você recebe +5 PV e +2 PM. Além disso, uma vez por cena pode gastar 2 PM para receber um dos seguintes benefícios até o fim da cena: treinamento em uma perícia; proficiência com uma arma, armadura ou escudo; usar uma ferramenta no lugar de outra.',
      itens: 'Arco curto, 20 flechas, uma bola (ou outro objeto simples) com uma cara pintada e nome de gente.' },
    { id: 'padeiro', nome: 'Padeiro', livro: 'herois', pagina: 52, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (cozinheiro). Além disso, sua profissão fortificou seus braços! Você recebe +1 em rolagens de dano com armas de impacto e pode substituir testes de Atletismo por testes de Ofício (cozinheiro).',
      itens: 'Instrumentos de Ofício (cozinheiro), rolo de massa (mesmas estatísticas de uma clava).' },
    { id: 'pedinte', nome: 'Pedinte', livro: 'herois', pagina: 52, tipo: 'especial',
      beneficio: 'Você é muito discreto, recebendo +2 em Enganação e Furtividade. Além disso, aprendeu a aproveitar o máximo de cada recurso e a partilhar do pouco que tinha com seus companheiros em dificuldades. Quando você usa um alimento, preparado alquímico ou poção, pode rolar seu efeito duas vezes e usar o melhor resultado (se o efeito for aleatório), ou pode dividir o item com um aliado adjacente (ele também gasta a ação para consumi-lo e recebe o benefício normal, mas você gasta apenas um item).',
      itens: 'Andrajos, esmolas que guardou (1 bálsamo restaurador e 1 essência de mana).' },
    { id: 'pescador', nome: 'Pescador', livro: 'herois', pagina: 52, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (pescador) e Sobrevivência. Além disso, você sabe aguardar o instante exato de puxar o anzol. Recebe +2 em Iniciativa e, sempre que prepara uma ação (Tormenta20, p. 234), recebe +2 em testes para executá-la.',
      itens: 'Bolsa cheia de minhocas, instrumentos de pescador.' },
    { id: 'servo', nome: 'Servo', livro: 'herois', pagina: 53, tipo: 'especial',
      beneficio: 'Você é treinado em Diplomacia e Ofício (serviçal). Além disso, recebe +2 em testes de Diplomacia e Enganação contra alvos que tenham status ou posição superior à sua (ou que acreditam ter), e pode substituir testes de Nobreza por testes de Ofício (serviçal).',
      itens: 'Balde e vassoura (mesmas estatísticas de um bordão), tabardo de seu patrono.' },
    { id: 'suporte-de-tropas', nome: 'Suporte de Tropas', livro: 'herois', pagina: 53, tipo: 'especial',
      beneficio: 'Sempre que você faz um teste para ajudar, o bônus que fornece aumenta em +2. Além disso, quando flanqueia um inimigo, o bônus que você e seus aliados recebem em testes de ataque aumenta para +4.',
      itens: 'Equipamento de viagem, instrumentos de ofício, maleta de medicamentos.' },

    // ── ORIGENS REGIONAIS (Atlas de Arton, Apêndice, p. 470–479) ──
    //  As 66 origens regionais do Atlas. Estrutura igual às especiais do
    //  Heróis (benefício único fixo + itens), mais o campo `regiao` (o
    //  reino/local, tirado da "Tabela: Origens Regionais", p. 472–473).
    //  Lidas do PDF em modo LEITURA (pdftotext -enc UTF-8, sem -layout/-raw:
    //  o único que sai limpo na coluna dupla). O ✦ marca a habilidade mágica.
    //  Regra da seção (p. 470): escolhida no lugar de uma origem comum se for
    //  nativo da região; se treina uma perícia que já se tem, treina outra de
    //  classe. As páginas são as IMPRESSAS, pelos cabeçalhos de cada folha.
    { id: 'agricultor-sambur', nome: 'Agricultor Sambur', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Repúblicas Livres de Sambúrdia',
      beneficio: 'Você é treinado em Adestramento e Sobrevivência e, uma vez por cena, pode gastar 1 PM para receber +1d6 em um teste de perícia.',
      itens: 'Ferramenta agrícola (mesmas estatísticas de uma lança), T$ 100 (um presente de despedida da sua família).' },
    { id: 'amazona-de-hippion', nome: 'Amazona de Hippion', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Deheon, Namalkah',
      beneficio: 'Você é treinada em Cavalgar e, se não estiver usando armadura pesada, soma seu Carisma nos PM, limitado pelo seu nível (apenas após um dia).',
      itens: 'Arma simples ou marcial, cavalo de guerra.' },
    { id: 'amoque-purpura', nome: 'Amoque Púrpura', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Ermos Púrpuras',
      beneficio: 'Você é treinado em Intimidação e, quando está sob efeito de Fúria, Fúria Divina ou Poder Oculto, recebe +2 em rolagens de dano.',
      itens: 'Arma simples, estandarte da sua tribo.' },
    { id: 'anao-de-armas', nome: 'Anão de Armas', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Doherimm',
      beneficio: 'Você é treinado em Ofício (armeiro) e recebe +2 em rolagens de dano com armas tradicionais anãs (machados, martelos, marretas e picaretas).',
      itens: 'Arma marcial tradicional anã, instrumentos de Ofício (armeiro).' },
    { id: 'andarilho-ubaneri', nome: 'Andarilho Ubaneri', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Ubani',
      beneficio: 'Você recebe um alikunhá, um parceiro iniciante que não conta em seu limite de parceiros (veja o quadro na página 471), e proficiência com escudos. Caso já tenha essa proficiência, o bônus na Defesa que seu escudo fornece aumenta em +1.',
      itens: 'Escudo pesado, lança.' },
    { id: 'aprendiz-de-dragoeiro', nome: 'Aprendiz de Dragoeiro', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Sckharshantallas',
      beneficio: 'Você recebe +2 na Defesa contra criaturas maiores que você e +2 em Reflexos. Além disso, se passar em um teste de Reflexos, seus ataques contra a fonte do efeito causam +1d8 pontos de dano até o final da cena.',
      itens: 'Arma simples ou marcial à sua escolha, troféu de caça, treckod.' },
    { id: 'aprendiz-de-drogadora', nome: 'Aprendiz de Drogadora', livro: 'atlas', pagina: 470, tipo: 'especial', regiao: 'Galrasia',
      beneficio: 'Você é treinada em Cura e Ofício (alquimista). Como usa partes de seu corpo para fabricar preparados alquímicos e poções, você gasta apenas 1/4 do preço dos itens em matérias-primas.',
      itens: 'Bálsamo restaurador x2, poção de curar ferimentos x2, maleta de medicamentos.' },
    { id: 'aristocrata-daizenshi', nome: 'Aristocrata Dai’zenshi', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Tamu-ra',
      beneficio: 'Você é treinado em Nobreza. Além disso, ao completar um descanso, caso não tenha feito nenhum teste de Enganação, Furtividade ou Ladinagem desde seu último descanso, você recebe +1 PM temporário para cada dois níveis.',
      itens: 'Traje da corte, katana superior com uma melhoria (exceto material especial).' },
    { id: 'armeiro-armado', nome: 'Armeiro Armado', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Zakharov',
      beneficio: 'Você é treinado em Ofício (armeiro) e pode fabricar armas com uma melhoria. Se aprender a fabricar armas superiores por outra habilidade, gasta apenas 1/4 do preço das melhorias que aplica em armas.',
      itens: 'Arma marcial, instrumentos de Ofício (armeiro).' },
    { id: 'aspirante-a-heroi', nome: 'Aspirante a Herói', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Deheon',
      beneficio: 'Você recebe +1 em um atributo à sua escolha.',
      itens: 'Essência de mana, mochila de aventureiro.' },
    { id: 'assistente-forense', nome: 'Assistente Forense', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Salistick',
      beneficio: 'Você é treinado em Investigação e pode usar esta perícia para necropsia, identificar itens alquímicos e rastrear (veja as perícias Cura, Ofício e Sobrevivência, em Tormenta20). Além disso, pode identificar criaturas em uma cena de crime ou equivalente mesmo que elas não estejam mais presentes. Isso funciona como um teste de identificar criatura, com uma penalidade de –1 para cada dia decorrido. Se passar, além do normal, você identifica a raça da criatura.',
      itens: 'Lupa (conta como uma ferramenta que fornece +1 em Investigação).' },
    { id: 'bandoleiro-da-fortaleza', nome: 'Bandoleiro da Fortaleza', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Khalifor',
      beneficio: 'Você é treinado em Furtividade e Intimidação, e recebe resistência a medo +5.',
      itens: 'Adaga, gazua, manto camuflado (urbano).' },
    { id: 'barao-arruinado', nome: 'Barão Arruinado', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Feudos de Trebuck',
      beneficio: 'Você é treinado em Nobreza. Sempre que falha em um teste de perícia e a falha acarreta uma consequência negativa (gastar uma ação, perder PV, sofrer um efeito etc.), você recebe +2 em testes da mesma perícia até o final da cena.',
      itens: 'Anel com símbolo da família (T$ 200), títulos de terras expirados (+2 em Diplomacia com nobres e burocratas), traje da corte.' },
    { id: 'catador-da-cidade-velha', nome: 'Catador da Cidade Velha', livro: 'atlas', pagina: 471, tipo: 'especial', regiao: 'Nova Malpetrim',
      beneficio: 'Você é treinado em Fortitude e Percepção e pode gastar 1 PM para receber deslocamento de natação igual ao seu deslocamento básico (se já tiver deslocamento de natação, em vez disso ele aumenta em +3m) por uma cena. Esse deslocamento não permite respirar debaixo d’água automaticamente, mas dobra o limite de tempo em que você pode segurar sua respiração.',
      itens: 'Luneta, luvas de pelica, tranqueiras resgatadas do mar (2 espaços, valor de venda T$ 100).' },
    { id: 'cativo-das-fadas', nome: 'Cativo das Fadas', livro: 'atlas', pagina: 472, tipo: 'especial', regiao: 'Pondsmânia',
      beneficio: 'Você recebe resistência a espíritos e magia +2 e +1 PV por nível de personagem.',
      itens: 'Corda, ração de viagem x10, essência de mana.' },
    { id: 'competidor-do-circuito', nome: 'Competidor do Circuito', livro: 'atlas', pagina: 472, tipo: 'especial', regiao: 'Feudos de Trebuck',
      beneficio: 'Você recebe o poder Torcida. Enquanto está sob efeito desse poder, sempre que reduz um inimigo a 0 PV com um ataque corpo a corpo, você recupera 1 PM.',
      itens: 'Arma marcial, T$ 100 (suas economias para comprar equipamentos de torneio).' },
    { id: 'cosmopolita', nome: 'Cosmopolita', livro: 'atlas', pagina: 472, tipo: 'especial', regiao: 'Valkaria',
      beneficio: 'Escolha um poder geral ou de uma classe na qual você tenha pelo menos dois níveis, e cujos requisitos você cumpra (exceto poderes concedidos ou da Tormenta). Você recebe esse poder. Uma vez por aventura, após concluir um descanso (oito horas de sono), pode trocar esse poder por outro.',
      itens: 'Equipamento de viagem, traje de viajante, um item artístico de origem cultural indefinida (½ espaço, T$ 100).' },
    { id: 'cria-da-favela', nome: 'Cria da Favela', livro: 'atlas', pagina: 472, tipo: 'especial', regiao: 'Valkaria',
      beneficio: 'Você recebe +1 em Constituição e, por piores que sejam as condições de descanso, sua recuperação é sempre pelo menos normal.',
      itens: 'Andrajos de aldeão, corda, vara de madeira.' },
    { id: 'criado-pelas-voracis', nome: 'Criado pelas Voracis', livro: 'atlas', pagina: 472, tipo: 'especial', regiao: 'Galrasia',
      beneficio: 'Você recebe +2 na Defesa e Sobrevivência e +3m em seu deslocamento.',
      itens: 'Arma simples, armadura leve, lança.' },
    { id: 'de-outro-mundo', nome: 'De Outro Mundo', livro: 'atlas', pagina: 472, tipo: 'especial', regiao: 'Éter Divino',
      beneficio: 'Você possui uma habilidade ou tecnologia especial de seu mundo de origem. Para representar esse efeito, escolha uma magia de 1º círculo e um atributo-chave para ela. Se for uma habilidade, você pode lançar essa magia. Se for uma tecnologia, você recebe um item Minúsculo (RD 10, PV iguais à metade dos seus) que ocupa 1 espaço e deve ser empunhado para lançar a magia, mas seu limite de PM para ela aumenta em +2. Por fim, escolha se o efeito será mágico ou mundano (nesse caso, não contará como uma magia, exceto para fins de acúmulo). O mestre tem a palavra final sobre qualquer efeito e combinação.',
      itens: 'Trajes exóticos, um item qualquer de até T$ 100 do seu mundo natal.' },
    { id: 'descendente-colleniano', nome: 'Descendente Colleniano', livro: 'atlas', pagina: 473, tipo: 'especial', regiao: 'Ahlen',
      beneficio: 'Você recebe +2 em Percepção e pode lançar a magia Visão Mística. Caso aprenda essa magia novamente, seu custo diminui em –1 PM. ✦',
      itens: 'Arma simples, estojo de disfarces, ração de viagem x5.' },
    { id: 'desertor-da-supremacia', nome: 'Desertor da Supremacia', livro: 'atlas', pagina: 473, tipo: 'especial', regiao: 'Supremacia Purista',
      beneficio: 'Você é treinado em Guerra e recebe proficiência com espadas bastardas e escudos. Se estiver empunhando uma espada bastarda e um escudo pesado, recebe +2 em testes de ataque.',
      itens: 'Brunea com símbolo purista raspado, escudo pesado, espada bastarda, ração de viagem x10.' },
    { id: 'duplo-feerico', nome: 'Duplo Feérico', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Pondsmânia',
      beneficio: 'Escolha uma habilidade de classe de 1º nível de uma classe que não seja a sua. Você recebe essa habilidade e pode usá-la como se tivesse 1 nível naquela classe (se escolher a habilidade Magias, você aprende uma única magia e recebe +1 ponto de mana, mas não soma o atributo-chave da habilidade em seu total de PM).',
      itens: 'Essência de mana, marca no corpo ou característica física não possuída pela sua versão original.' },
    { id: 'duyshidakk-infiltrado', nome: 'Duyshidakk Infiltrado', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Ruínas de Tyrondir',
      beneficio: 'Você recebe +2 em Furtividade e Vontade e pode usar Sabedoria como atributo-chave de Enganação (em vez de Carisma).',
      itens: 'Arma marcial, peças sobressalentes (T$ 100 para vender ou construir engenhocas).' },
    { id: 'emissario-ubaneri', nome: 'Emissário Ubaneri', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Ubani',
      beneficio: 'Você recebe um alikunhá, um parceiro iniciante que não conta em seu limite de parceiros (veja o quadro na página 471) e pode usar Sabedoria como atributo-chave de Misticismo (em vez de Inteligência).',
      itens: 'Essência de mana, mochila de aventureiro.' },
    { id: 'escudeiro-da-luz', nome: 'Escudeiro da Luz', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Bielefeld',
      beneficio: 'Você é treinado em Nobreza. Além disso, recebe +2 na Defesa e +3 PM.',
      itens: 'Cota de malha ou escudo pesado, enfeite de elmo com o símbolo da Ordem da Luz.' },
    { id: 'escudeiro-solitario', nome: 'Escudeiro Solitário', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Bielefeld',
      beneficio: 'Você é treinado em Enganação e Ladinagem e recebe +10 em testes de Enganação para se disfarçar como cavaleiro da Luz. Além disso, se tiver Código de Honra (ou outro semelhante), atacar pelas costas não faz com que você o viole.',
      itens: 'Cota de malha, escudo pesado, enfeite de elmo.' },
    { id: 'estandarte-vivo', nome: 'Estandarte Vivo', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Ermos Púrpuras',
      beneficio: 'Você recebe +2 em Sobrevivência e um poder de combate ou da Tormenta à sua escolha.',
      itens: 'Arma simples ou marcial, gibão de peles, fragmento do estandarte do seu povo (se vestido, fornece +1 em testes de Vontade).' },
    { id: 'estudante-da-academia', nome: 'Estudante da Academia', livro: 'atlas', pagina: 474, tipo: 'especial', regiao: 'Academia Arcana',
      beneficio: 'Você aprende e pode lançar uma magia arcana de 1º círculo a sua escolha (atributo-chave Inteligência). Além disso, pode fazer testes de Misticismo mesmo sem ser treinado nessa perícia. Se for treinado, recebe +2 em testes dela.',
      itens: 'Coleção de livros (uma qualquer), essência de mana x2.' },
    { id: 'estudante-do-colegio-real', nome: 'Estudante do Colégio Real', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Salistick',
      beneficio: 'Você é treinado em Cura. Além disso, seus efeitos de cura recuperam +2 PV por dado. Você perde esse benefício caso se torne um devoto de qualquer tipo.',
      itens: 'Bálsamo restaurador x3, maleta de medicamentos.' },
    { id: 'explorador-de-ruinas', nome: 'Explorador de Ruínas', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Ruínas de Tyrondir',
      beneficio: 'Você recebe +2 em Ladinagem, Percepção e Reflexos e +3m em seu deslocamento.',
      itens: 'Mochila de aventureiro, tocha, vara de madeira (3m).' },
    { id: 'filhote-da-revoada', nome: 'Filhote da Revoada', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Lamnor',
      beneficio: 'Você é treinado em Acrobacia e Pilotagem. Quando faz um teste de uma dessas perícias, pode gastar 1 PM para rolar um dado adicional e usar o melhor resultado.',
      itens: 'Instrumentos de Ofício (artesão), T$ 100 (que você está juntando para fabricar seu primeiro veículo aéreo).' },
    { id: 'futura-lenda', nome: 'Futura Lenda', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Nova Malpetrim',
      beneficio: 'Escolha um dos poderes de sua classe, normalmente disponíveis a partir do 2º nível. Você recebe esse poder.',
      itens: 'Arma simples ou marcial com nome pomposo (e nenhuma melhoria), essência de mana x2.' },
    { id: 'ginete-de-tumarkhan', nome: 'Ginete de Tumarkhân', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Khubar',
      beneficio: 'Você é treinado em Cavalgar e possui um parceiro tumarkhân iniciante, com quem recebe +2 em testes de Adestramento e Cavalgar. Se receber outra montaria especial (como pelos poderes Montaria ou Montaria Sagrada), você pode usar seu tumarkhân como essa montaria, acumulando o bônus em perícias com os benefícios da montaria especial.',
      itens: 'Bálsamo restaurador, sela.' },
    { id: 'grumete-pirata', nome: 'Grumete Pirata', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Três Mares',
      beneficio: 'Você é treinado em Acrobacia, Atletismo e Reflexos e, se estiver se equilibrando, escalando ou nadando, só cai ou afunda se falhar no teste de perícia por 10 ou mais (em vez de 5 ou mais).',
      itens: 'Adaga, corda, tatuagem de sua antiga tripulação (+1 em Intimidação).' },
    { id: 'guardiao-glacial', nome: 'Guardião Glacial', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Montanhas Uivantes',
      beneficio: 'Você recebe redução de frio 5 e proficiência em arco longo e machado de batalha. Caso já possua proficiência com essas armas, você recebe +2 em rolagens de dano com elas.',
      itens: 'Casaco longo, cavalo glacial.' },
    { id: 'iniciado-dos-caca-monstros', nome: 'Iniciado dos Caça-Monstros', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Montanhas Sanguinárias',
      beneficio: 'Você pode fazer testes para identificar criaturas com uma ação de movimento e, quando acerta um ataque em uma criatura não humanoide, pode gastar 1 PM para causar +1d8 pontos de dano.',
      itens: 'Arma simples ou marcial, gibão de peles.' },
    { id: 'insurgente-tapistano', nome: 'Insurgente Tapistano', livro: 'atlas', pagina: 475, tipo: 'especial', regiao: 'Império de Tauron',
      beneficio: 'Você recebe +1 em Fortitude, Reflexos e Vontade. Além disso, recebe +3 pontos de vida no 1º nível e +1 PV por nível seguinte.',
      itens: 'Amuleto com um símbolo da resistência reconhecível por outros rebeldes, arma simples.' },
    { id: 'irmao-sem-esporas', nome: 'Irmão sem Esporas', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Namalkah',
      beneficio: 'Você possui um irmão cavalo, um cavalo de guerra parceiro iniciante que fornece +1 em testes de ataque e Reflexos. Se receber outra montaria especial (como aquela concedida pelos poderes Montaria ou Montaria Sagrada), você pode usar seu irmão cavalo como essa montaria, acumulando o bônus em perícias com os benefícios da montaria especial.',
      itens: 'Bálsamo restaurador, sela.' },
    { id: 'legionario', nome: 'Legionário', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Império de Tauron',
      beneficio: 'Você é treinado em Guerra e recebe proficiência com gládios (veja Ameaças de Arton) e escudos. Se estiver empunhando um gládio e um escudo pesado, recebe +1 na margem de ameaça e +1 na Defesa.',
      itens: 'Brunea com símbolo de sua legião, escudo pesado, gládio, ração de viagem x10.' },
    { id: 'lenhador-de-tollon', nome: 'Lenhador de Tollon', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Floresta de Tollon',
      beneficio: 'Você é treinado em Ofício (artesão) e recebe +5 em testes de perícias (exceto testes de ataque) relacionados a madeira. Além disso, você recebe proficiência com machadinhas e machados de batalha; caso já possua proficiência com essas armas, recebe +2 em rolagens de dano com elas.',
      itens: 'Item superior de madeira Tollon.' },
    { id: 'liricista-de-lenorienn', nome: 'Liricista de Lenórienn', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Lamnor',
      beneficio: 'Você é treinado em Atuação e recebe +2 nessa perícia. Além disso, pode usar Carisma como atributo-chave de Misticismo (no lugar de Inteligência).',
      itens: 'Alaúde élfico, réplica de uma peça artística élfica (1 espaço, T$ 50).' },
    { id: 'membro-do-principado', nome: 'Membro do Principado', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Repúblicas Livres de Sambúrdia',
      beneficio: 'Você é treinado em Diplomacia e Intuição. Quando chega em uma cidade pela primeira vez em cada aventura, pode fazer um teste de Diplomacia (CD 20). Se passar, recebe 10% de desconto em todos os itens que comprar neste lugar (cumulativo com barganha).',
      itens: 'Carroça, mercadorias sortidas (8 espaços, T$ 400).' },
    { id: 'nitamuraniano', nome: 'Nitamuraniano', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Valkaria',
      beneficio: 'Você recebe proficiência em katana e arco longo. Caso receba proficiência nessas armas novamente, recebe +2 em rolagens de dano com elas. Além disso, quando falha em um teste de perícia originalmente baseada em Sabedoria, você pode gastar 2 PM para refazer esse teste (apenas uma vez por teste).',
      itens: 'Arco longo ou katana, camisa bufante ou traje de seda.' },
    { id: 'nobre-zakharoviano', nome: 'Nobre Zakharoviano', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Zakharov',
      beneficio: 'Você é treinado em Ofício (armeiro) e recebe uma arma superior com uma melhoria (exceto material especial). Se estiver de posse dessa arma, recebe +2 PM por patamar (apenas após um dia).',
      itens: 'Traje da corte.' },
    { id: 'nomade-sar-allan', nome: 'Nômade Sar-Allan', livro: 'atlas', pagina: 476, tipo: 'especial', regiao: 'Halak-Tûr',
      beneficio: 'Você recebe +2 em Fortitude e Sobrevivência e nas rolagens de dano com alfanges, arcos curtos e cimitarras.',
      itens: 'Arma simples ou marcial, corcel do deserto ou dromedário (veja Ameaças de Arton), manto camuflado (deserto).' },
    { id: 'pescador-parrudo', nome: 'Pescador Parrudo', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Khubar',
      beneficio: 'Você recebe +2 em Atletismo, Fortitude e Sobrevivência e +3 PV. Além disso, quando faz um teste de Atletismo para nadar você avança seu deslocamento (em vez de apenas a metade).',
      itens: 'Vara de pesca (pode usar Sobrevivência para sustento), peixes raros salgados para revenda (1 espaço, T$ 50).' },
    { id: 'plebeu-arcano', nome: 'Plebeu Arcano', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Wynlla',
      beneficio: 'Você recebe +2 PM. Além disso, uma vez por rodada, quando falha em um teste de resistência contra um efeito mágico, você pode gastar 1 PM para rolar novamente esse teste.',
      itens: 'Bandoleira de poções, gorro de ervas, poção arcana de 1º círculo.' },
    { id: 'prisioneiro-das-catacumbas', nome: 'Prisioneiro das Catacumbas', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Catacumbas de Leverick',
      beneficio: 'Você é treinado em Percepção e Reflexos e recebe resistência a armadilhas e efeitos de movimento +5.',
      itens: 'Arma marcial encontrada no corpo de alguém que não sobreviveu às Catacumbas.' },
    { id: 'procurado-vivo-ou-morto', nome: 'Procurado: Vivo ou Morto', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Smokestone',
      beneficio: 'Você recebe proficiência com armas de fogo. Além disso, recebe +5 em testes de Intimidação e –5 em testes de Diplomacia contra qualquer um que, a critério do mestre, o reconheça e saiba de sua fama.',
      itens: 'Pistola, balas cruéis (20).' },
    { id: 'profeta-do-akzath', nome: 'Profeta do Akzath', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Lamnor',
      beneficio: 'Você é treinado em Religião e pode lançar magias mesmo sob o efeito de Fúria Divina.',
      itens: 'Arma simples ou marcial, bordão, pergaminho com diagrama do Akzath.' },
    { id: 'querido-filho', nome: 'Querido Filho', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Aslothia',
      beneficio: 'Você redução de frio e trevas 5 e visão no escuro. Se já possuir visão no escuro, em vez disso recebe +2 em Percepção.',
      itens: 'Essência de sombra, manto camuflado (urbano).' },
    { id: 'rebelde-agitador', nome: 'Rebelde Agitador', livro: 'atlas', pagina: 477, tipo: 'especial', regiao: 'Sckharshantallas',
      beneficio: 'Você é treinado em Iniciativa e, uma vez por aventura, pode gastar um dia para convencer pessoas comuns a ajudá-lo. Faça um teste de Diplomacia (CD 10). Se passar, você convence uma pessoa, mais uma para cada 10 pontos acima da CD (duas pessoas com resultado 20, três com resultado 30 e assim por diante). Cada pessoa pode ser usada como um parceiro iniciante de um tipo à sua escolha por uma cena. As pessoas não contam em seu limite de parceiros e ficam com você até serem usadas ou até o fim da aventura.',
      itens: 'Arma simples ou marcial, panfleto revolucionário, T$ 6d12 (impostos que você deixou de pagar).' },
    { id: 'receptador-das-nuvens', nome: 'Receptador das Nuvens', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Vectora',
      beneficio: 'Você possui contatos em Vectora que lhe dão acesso a mercadorias. Se estiver em uma cidade ou outro lugar em que, a critério do mestre, possa acessar seus contatos, você pode gastar 1 dia para obter um aparato mágico: um item de 1 espaço que você (e apenas você) pode empunhar para lançar uma magia de 1º círculo (atributo-chave Inteligência), escolhida ao obter o aparato. Você pode ter até 2 aparatos ao mesmo tempo. Os aparatos não têm valor comercial.',
      itens: 'Mercadorias raras e variadas (2 espaços, T$ 300).' },
    { id: 'recruta-arcano', nome: 'Recruta Arcano', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Wynlla',
      beneficio: 'A CD para resistir a suas magias arcanas aumenta em +1 e elas causam +1 ponto de dano.',
      itens: 'Essência de mana x2, varinha arcana.' },
    { id: 'recruta-da-fenix', nome: 'Recruta da Fênix', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Triunphus',
      beneficio: 'Você recebe +1 PV por nível e redução de fogo 5, e é treinado em Cavalgar.',
      itens: 'Arma marcial, brunea, grifo iniciante.' },
    { id: 'sabio-matematico', nome: 'Sábio Matemático', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Halak-Tûr',
      beneficio: 'Você é treinado em Conhecimento. Além disso, aprende e pode lançar Concentração de Combate e Orientação. Estes efeitos não contam como magias (exceto para fins de acúmulo) e não são mágicos — eles provêm de sua habilidade de calcular resultados a partir de uma mistura de geometria, análise de probabilidades e outros campos da matemática.',
      itens: 'Coleção de livros, luneta.' },
    { id: 'selvagem-sanguinario', nome: 'Selvagem Sanguinário', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Montanhas Sanguinárias',
      beneficio: 'Você é treinado em Sobrevivência e, se não estiver usando armadura pesada, recebe +1 em rolagens de dano com armas e redução de dano 1.',
      itens: 'Arma marcial, gibão de peles.' },
    { id: 'sucateiro-de-batalhas', nome: 'Sucateiro de Batalhas', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Conflagração do Aço',
      beneficio: 'Você é treinado em Guerra e Investigação. Além disso, quando rola na Tabela 8-1: Tesouro por Nível de Desafio (Tormenta20, p. 328), para cada tipo de tesouro (dinheiro ou item) você pode rolar novamente o resultado.',
      itens: 'Arma simples ou marcial, bálsamo restaurador, escudo leve ou pesado, essência de mana, ração de viagem x5, T$ 4d6.' },
    { id: 'tamalu', nome: 'Tamalu', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Khubar',
      beneficio: 'Você é treinado em Diplomacia e Nobreza e recebe uma tatuagem mística à sua escolha.',
      itens: 'Traje da corte.' },
    { id: 'tocado-pela-dama-altiva', nome: 'Tocado pela Dama Altiva', livro: 'atlas', pagina: 478, tipo: 'especial', regiao: 'Moreania',
      beneficio: 'Você é treinado em Adestramento e pode gastar 1 minuto e 1 PM para convocar um animal Minúsculo a sua escolha, como um falcão ou gato, em seu auxílio. A criatura convocada fornece +2 nos seus testes de uma perícia específica, adequada às suas capacidades, e permanece auxiliando-o até o fim da cena, quando então retorna para os ermos. Você pode ter um número de criaturas convocadas simultâneas igual à sua Sabedoria (mínimo de 1). O mestre tem a palavra final sobre quais criaturas estão disponíveis e em quais perícias elas podem prestar auxílio.',
      itens: 'Bordão, ração de viagem x5.' },
    { id: 'tocado-pelo-indomavel', nome: 'Tocado pelo Indomável', livro: 'atlas', pagina: 479, tipo: 'especial', regiao: 'Moreania',
      beneficio: 'Você é treinado em Atletismo e recebe +2 em rolagens de dano com armas naturais e ataques desarmados.',
      itens: 'Trapos surrados, carcaça de couro de algum animal caçado por você (conta como um gibão de peles).' },
    { id: 'tradicionalista-svalano', nome: 'Tradicionalista Svalano', livro: 'atlas', pagina: 479, tipo: 'especial', regiao: 'Svalas',
      beneficio: 'Você pode usar Sabedoria como atributo-chave de Conhecimento e Nobreza e pode fazer testes dessas perícias mesmo sem treinamento. Além disso, recebe +1 em Fortitude e Vontade.',
      itens: 'Arma simples ou marcial, corda, mochila de aventureiro, vara de madeira (3 m).' },
    { id: 'trapaceiro-ahleniense', nome: 'Trapaceiro Ahleniense', livro: 'atlas', pagina: 479, tipo: 'especial', regiao: 'Ahlen',
      beneficio: 'Você recebe +2 em Enganação e Furtividade e pode usar Carisma como atributo-chave de Ladinagem (em vez de Destreza).',
      itens: 'Essência de sombra, gazua, estojo de disfarces.' },
    { id: 'turista-da-academia', nome: 'Turista da Academia', livro: 'atlas', pagina: 479, tipo: 'especial', regiao: 'Academia Arcana',
      beneficio: 'Você recebe resistência a magia +2 e pode ativar pergaminhos de todas as magias arcanas de 1º círculo como se as conhecesse.',
      itens: 'Três pergaminhos de magias arcanas de 1º círculo à sua escolha.' },
    { id: 'um-com-os-kami', nome: 'Um com os Kami', livro: 'atlas', pagina: 479, tipo: 'especial', regiao: 'Tamu-ra',
      beneficio: 'Você pode usar Sabedoria como atributo-chave de Misticismo (em vez de Inteligência). Além disso, é acompanhado por um kami incorpóreo e invisível. Ele é um parceiro especial, que permite que você veja criaturas incorpóreas invisíveis e afete criaturas com seus ataques e habilidades como se fossem mágicos, e não conta em seu limite de parceiros. Além disso, uma vez por rodada você pode gastar 1 PM para executar o equivalente a uma ação de movimento que só pode ser usada para manipular um objeto solto em alcance curto. O kami não pode se afastar além de alcance curto de você. Se for destruído por qualquer efeito, o kami desaparece, retornando no início da próxima cena.',
      itens: 'Bálsamo restaurador, essência de mana.' },
  ];

  window.GA_ORIGENS_LIVROS = { t20: 'Tormenta20', herois: 'Heróis de Arton', atlas: 'Atlas de Arton' };
})();
