// ════════════════════════════════════════════════════════════════════
//  ORIGENS-DATA.JS — as ORIGENS e seus BENEFÍCIOS (Frente 3, 28/09/2026)
//  Localização: /grifos-alados/js/origens-data.js
//
//  POR QUE ISTO EXISTE. Até agora a ficha só tinha o "Poder Único" de cada
//  origem (grupo `origem` em js/poderes-raca-origem-data.js). Faltava o que
//  a origem DÁ: uma lista de perícias e poderes de onde, pela regra, se
//  escolhe DOIS benefícios (Tormenta20, p. 85: "escolha dois benefícios
//  entre os listados"). Em Seguidor, por exemplo, dá para pegar 2 perícias,
//  OU 2 poderes, OU 1 + 1.
//
//  ESTÁGIO 1 (28/09/2026): as 35 origens do NÚCLEO (Tormenta20 Jogo do Ano,
//  Tabela 1-19, p. 85–95), conferidas uma a uma contra a tabela do livro E
//  contra o Poder Único que já tínhamos (o poder-assinatura de cada origem
//  bate com o campo `tags` do dado antigo).
//
//  Cada origem:
//    id, nome        como o livro imprime
//    livro, pagina   Tormenta20, página IMPRESSA
//    escolher        quantos benefícios se pega (2, salvo exceção)
//    pericias[]      as perícias oferecidas (uma delas conta como 1 benefício)
//    poderes[]       os poderes oferecidos (idem). O poder-assinatura da
//                    origem está aqui, no meio dos gerais.
//    flexiveis[]     "vagas" que o jogador preenche à vontade — "um poder de
//                    combate à sua escolha", "um poder da Tormenta…", etc.
//    nota            só quando o livro foge do padrão (Amnésico)
//
//  As "origens especiais" do Heróis de Arton (benefício ÚNICO fixo) entram
//  numa leva à parte — ver docs/origens-progresso.md.
//
//  Consumido por js/ficha.js (cartão 🌿, seletor de origem).
// ════════════════════════════════════════════════════════════════════
(function () {
  'use strict';

  window.GA_ORIGENS = [
    { id: 'acolito', nome: 'Acólito', livro: 't20', pagina: 85, escolher: 2,
      pericias: ['Cura', 'Religião', 'Vontade'],
      poderes: ['Medicina', 'Membro da Igreja', 'Vontade de Ferro'] },
    { id: 'amigo-dos-animais', nome: 'Amigo dos Animais', livro: 't20', pagina: 85, escolher: 2,
      pericias: ['Adestramento', 'Cavalgar'],
      poderes: ['Amigo Especial'] },
    { id: 'amnesico', nome: 'Amnésico', livro: 't20', pagina: 86, escolher: 3,
      pericias: [], poderes: ['Lembranças Graduais'],
      flexiveis: ['uma perícia à escolha do mestre', 'um poder à escolha do mestre'],
      nota: 'Em vez de escolher dois benefícios, o Amnésico recebe os três: uma perícia e um poder definidos pelo mestre, mais o poder Lembranças Graduais.' },
    { id: 'aristocrata', nome: 'Aristocrata', livro: 't20', pagina: 86, escolher: 2,
      pericias: ['Diplomacia', 'Enganação', 'Nobreza'],
      poderes: ['Comandar', 'Sangue Azul'] },
    { id: 'artesao', nome: 'Artesão', livro: 't20', pagina: 86, escolher: 2,
      pericias: ['Ofício', 'Vontade'],
      poderes: ['Frutos do Trabalho', 'Sortudo'] },
    { id: 'artista', nome: 'Artista', livro: 't20', pagina: 87, escolher: 2,
      pericias: ['Atuação', 'Enganação'],
      poderes: ['Atraente', 'Dom Artístico', 'Sortudo', 'Torcida'] },
    { id: 'assistente-de-laboratorio', nome: 'Assistente de Laboratório', livro: 't20', pagina: 88, escolher: 2,
      pericias: ['Ofício (alquimista)', 'Misticismo'],
      poderes: ['Esse Cheiro...', 'Venefício'],
      flexiveis: ['um poder da Tormenta à sua escolha'] },
    { id: 'batedor', nome: 'Batedor', livro: 't20', pagina: 88, escolher: 2,
      pericias: ['Furtividade', 'Percepção', 'Sobrevivência'],
      poderes: ['À Prova de Tudo', 'Estilo de Disparo', 'Sentidos Aguçados'] },
    { id: 'capanga', nome: 'Capanga', livro: 't20', pagina: 88, escolher: 2,
      pericias: ['Luta', 'Intimidação'],
      poderes: ['Confissão'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'charlatao', nome: 'Charlatão', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Enganação', 'Jogatina'],
      poderes: ['Alpinista Social', 'Aparência Inofensiva', 'Sortudo'] },
    { id: 'circense', nome: 'Circense', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Acrobacia', 'Atuação', 'Reflexos'],
      poderes: ['Acrobático', 'Torcida', 'Truque de Mágica'] },
    { id: 'criminoso', nome: 'Criminoso', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Enganação', 'Furtividade', 'Ladinagem'],
      poderes: ['Punguista', 'Venefício'] },
    { id: 'curandeiro', nome: 'Curandeiro', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Cura', 'Vontade'],
      poderes: ['Medicina', 'Médico de Campo', 'Venefício'] },
    { id: 'eremita', nome: 'Eremita', livro: 't20', pagina: 89, escolher: 2,
      pericias: ['Misticismo', 'Religião', 'Sobrevivência'],
      poderes: ['Busca Interior', 'Lobo Solitário'] },
    { id: 'escravo', nome: 'Escravo', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Atletismo', 'Fortitude', 'Furtividade'],
      poderes: ['Desejo de Liberdade', 'Vitalidade'] },
    { id: 'estudioso', nome: 'Estudioso', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Conhecimento', 'Guerra', 'Misticismo'],
      poderes: ['Aparência Inofensiva', 'Palpite Fundamentado'] },
    { id: 'fazendeiro', nome: 'Fazendeiro', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Adestramento', 'Cavalgar', 'Ofício (fazendeiro)', 'Sobrevivência'],
      poderes: ['Água no Feijão', 'Ginete'] },
    { id: 'forasteiro', nome: 'Forasteiro', livro: 't20', pagina: 90, escolher: 2,
      pericias: ['Cavalgar', 'Pilotagem', 'Sobrevivência'],
      poderes: ['Cultura Exótica', 'Lobo Solitário'] },
    { id: 'gladiador', nome: 'Gladiador', livro: 't20', pagina: 91, escolher: 2,
      pericias: ['Atuação', 'Luta'],
      poderes: ['Atraente', 'Pão e Circo', 'Torcida'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'guarda', nome: 'Guarda', livro: 't20', pagina: 91, escolher: 2,
      pericias: ['Investigação', 'Luta', 'Percepção'],
      poderes: ['Detetive', 'Investigador'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'herdeiro', nome: 'Herdeiro', livro: 't20', pagina: 91, escolher: 2,
      pericias: ['Misticismo', 'Nobreza', 'Ofício'],
      poderes: ['Comandar', 'Herança'] },
    { id: 'heroi-camponnes', nome: 'Herói Camponês', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Adestramento', 'Ofício'],
      poderes: ['Coração Heroico', 'Sortudo', 'Surto Heroico', 'Torcida'] },
    { id: 'marujo', nome: 'Marujo', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Atletismo', 'Jogatina', 'Pilotagem'],
      poderes: ['Acrobático', 'Passagem de Navio'] },
    { id: 'mateiro', nome: 'Mateiro', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Atletismo', 'Furtividade', 'Sobrevivência'],
      poderes: ['Lobo Solitário', 'Sentidos Aguçados', 'Vendedor de Carcaças'] },
    { id: 'membro-de-guilda', nome: 'Membro de Guilda', livro: 't20', pagina: 92, escolher: 2,
      pericias: ['Diplomacia', 'Enganação', 'Misticismo', 'Ofício'],
      poderes: ['Foco em Perícia', 'Rede de Contatos'] },
    { id: 'mercador', nome: 'Mercador', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Diplomacia', 'Intuição', 'Ofício'],
      poderes: ['Negociação', 'Proficiência', 'Sortudo'] },
    { id: 'minerador', nome: 'Minerador', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Atletismo', 'Fortitude', 'Ofício (minerador)'],
      poderes: ['Ataque Poderoso', 'Escavador', 'Sentidos Aguçados'] },
    { id: 'nomade', nome: 'Nômade', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Cavalgar', 'Pilotagem', 'Sobrevivência'],
      poderes: ['Lobo Solitário', 'Mochileiro', 'Sentidos Aguçados'] },
    { id: 'pivete', nome: 'Pivete', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Furtividade', 'Iniciativa', 'Ladinagem'],
      poderes: ['Acrobático', 'Aparência Inofensiva', 'Quebra-Galho'] },
    { id: 'refugiado', nome: 'Refugiado', livro: 't20', pagina: 93, escolher: 2,
      pericias: ['Fortitude', 'Reflexos', 'Vontade'],
      poderes: ['Estoico', 'Vontade de Ferro'] },
    { id: 'seguidor', nome: 'Seguidor', livro: 't20', pagina: 94, escolher: 2,
      pericias: ['Adestramento', 'Ofício'],
      poderes: ['Antigo Mestre', 'Proficiência', 'Surto Heroico'] },
    { id: 'selvagem', nome: 'Selvagem', livro: 't20', pagina: 94, escolher: 2,
      pericias: ['Percepção', 'Reflexos', 'Sobrevivência'],
      poderes: ['Lobo Solitário', 'Vida Rústica', 'Vitalidade'] },
    { id: 'soldado', nome: 'Soldado', livro: 't20', pagina: 94, escolher: 2,
      pericias: ['Fortitude', 'Guerra', 'Luta', 'Pontaria'],
      poderes: ['Influência Militar'],
      flexiveis: ['um poder de combate à sua escolha'] },
    { id: 'taverneiro', nome: 'Taverneiro', livro: 't20', pagina: 95, escolher: 2,
      pericias: ['Diplomacia', 'Jogatina', 'Ofício (cozinheiro)'],
      poderes: ['Gororoba', 'Proficiência', 'Vitalidade'] },
    { id: 'trabalhador', nome: 'Trabalhador', livro: 't20', pagina: 95, escolher: 2,
      pericias: ['Atletismo', 'Fortitude'],
      poderes: ['Atlético', 'Esforçado'] },

    // ── ORIGENS ESPECIAIS (Heróis de Arton, "Novas origens", p. 46–53) ──
    //  Estrutura DIFERENTE do núcleo: um benefício ÚNICO fixo (não se
    //  escolhe 2) e uma linha de itens. Notas do livro: "Efeitos de origens
    //  contam como habilidades para fins de acúmulo"; e se o benefício
    //  treina uma perícia em que você já é treinado, treina outra de classe.
    { id: 'bacharel', nome: 'Bacharel', livro: 'herois', pagina: 46, tipo: 'especial',
      beneficio: 'Você é treinado em Conhecimento, Diplomacia e Nobreza. Além disso, uma vez por cena pode usar Diplomacia para mudar atitude como uma ação livre.',
      itens: 'Tabardo com o símbolo de Khalmyr, uma coleção de livros a sua escolha.' },
    { id: 'boticario', nome: 'Boticário', livro: 'herois', pagina: 46, tipo: 'especial',
      beneficio: 'Você é treinado em Cura e Ofício (alquimista). Além disso, pode fabricar poções de duas fórmulas de 1º círculo a sua escolha, como se tivesse o poder Alquimista Iniciado (Tormenta20, p. 68).',
      itens: 'Bálsamo restaurador, instrumentos de Ofício (alquimista), maleta de medicamentos.' },
    { id: 'cacador-de-ratos', nome: 'Caçador de Ratos', livro: 'herois', pagina: 46, tipo: 'especial',
      beneficio: 'Você é treinado em Furtividade, Investigação e Sobrevivência, e recebe +2 em testes de perícias contra criaturas de duas categorias de tamanho menor que a sua (mínimo Minúsculas).',
      itens: 'Clava, um gato (um parceiro perseguidor iniciante), T$ 50 (recompensa por sua última caçada).' },
    { id: 'cao-de-briga', nome: 'Cão de Briga', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Na primeira vez a cada cena em que você faz a ação agredir, pode fazer um ataque extra.',
      itens: 'Manoplas ou uma arma marcial.' },
    { id: 'carcereiro', nome: 'Carcereiro', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você recebe +2 em testes contra efeitos mentais, Enganação, Furtividade e Intimidação.',
      itens: 'Algemas, lampião, uma arma de até T$ 500 a sua escolha, que você pode ou não ter obtido de um detento.' },
    { id: 'carpinteiro-de-guilda', nome: 'Carpinteiro de Guilda', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (artesão). Além disso, recebe redução de corte 2 e, em suas mãos, armas de corte ignoram 5 pontos de redução de dano.',
      itens: 'Instrumentos de Ofício (carpinteiro), uma arma de corte a sua escolha.' },
    { id: 'catador-da-catastrofe', nome: 'Catador da Catástrofe', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você é treinado em Fortitude e Percepção. No início de cada aventura, pode fazer um teste de Percepção (CD 15 + metade do seu nível). Se passar, encontra um tesouro correspondente a seu próprio ND, escolhido pelo mestre ou rolado nas colunas Dinheiro e Itens da Tabela 8-1: Tesouro por Nível de Desafio (Tormenta20, p. 328).',
      itens: 'Dois equipamentos de aventura de até T$ 150 cada a sua escolha.' },
    { id: 'chef-hynne', nome: 'Chef Hynne', livro: 'herois', pagina: 47, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (cozinheiro). Quando prepara um prato especial, seu benefício dura mais 1 dia (se for um benefício com um uso diário, ele pode ser usado novamente nesse dia).',
      itens: 'Cutelo (mesmas estatísticas de uma foice), instrumentos de cozinheiro aprimorados.' },
    { id: 'cirurgiao-barbeiro', nome: 'Cirurgião-Barbeiro', livro: 'herois', pagina: 48, tipo: 'especial',
      beneficio: 'Você é treinado em Cura e Ofício (barbeiro). Além disso, pode gastar uma ação completa e 2 PM para remover uma das seguintes condições de uma criatura adjacente: abalado, alquebrado, apavorado, atordoado, cego, confuso, debilitado, enjoado, envenenado, esmorecido, exausto, fascinado, fatigado, fraco, frustrado, lento, ofuscado, paralisado, pasmo e surdo. Contudo, a criatura também perde 1d6 pontos de vida.',
      itens: 'Dente falso (p. 227), instrumentos de barbeiro, maleta de medicamentos.' },
    { id: 'citadino-abastado', nome: 'Citadino Abastado', livro: 'herois', pagina: 48, tipo: 'especial',
      beneficio: 'Você é treinado em Nobreza e em um Ofício a sua escolha. Se estiver em uma cidade grande (a critério do mestre), pode gastar tibares para aprender algum conhecimento local útil. O custo é T$ 10 x seu nível. Se fizer isso, escolha um poder de combate, de destino ou de uma de suas classes cujos pré-requisitos você cumpra (o mestre determina se um poder está disponível na cidade). Até o fim da aventura, ou até usar esta habilidade novamente, você pode usar o poder escolhido por uma cena.',
      itens: 'Uma arma, armadura, ferramenta ou vestuário no valor de até T$ 500.' },
    { id: 'cocheiro', nome: 'Cocheiro', livro: 'herois', pagina: 48, tipo: 'especial',
      beneficio: 'Você é treinado em Adestramento e Pilotagem e, quando está conduzindo um veículo, você e o veículo recebem +2 na Defesa e em testes de resistência.',
      itens: 'Cavalo ou trobo, carroça.' },
    { id: 'construtor', nome: 'Construtor', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Fortitude e Ofício (pedreiro). Além disso, sabe encontrar pontos fracos em construções e estruturas. Pode pagar 2 PM para que você ou um aliado em alcance curto ignore 5 pontos da redução de dano de uma criatura ou objeto em alcance curto por uma cena.',
      itens: 'Instrumentos de pedreiro ou uma ferramenta pesada (mesmas estatísticas de uma maça ou lança, a sua escolha).' },
    { id: 'contrabandista', nome: 'Contrabandista', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Enganação e Ladinagem, e recebe +5 em testes de Ladinagem para ocultar itens em si mesmo ou em veículos. Além disso, sua capacidade de carga aumenta em 2 espaços.',
      itens: 'Uma arma de fogo, ou 10 doses de venenos, com preço total de até T$ 500.' },
    { id: 'coureiro', nome: 'Coureiro', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Fortitude e Ofício (coureiro). Além disso, pode gastar 10 minutos e T$ 10 para trabalhar em uma armadura de couro (incluindo couro batido, gibão de peles e brunea), aumentar a Defesa dela em +1 e reduzir sua penalidade de armadura em -2 por um dia.',
      itens: 'Faca de corte (como uma adaga, mas com dano de corte), instrumentos de coureiro, T$ 100 em itens alquímicos.' },
    { id: 'escriba', nome: 'Escriba', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Conhecimento e Ofício (escriba) e recebe o poder de bardo Lendas e Histórias (Tormenta20, p. 45). Se receber esse poder novamente, em seu lugar recebe um bônus de +5 ao rolar novamente um teste usando seu efeito.',
      itens: 'Instrumentos de escriba, organizador de pergaminhos, uma coleção de livros a sua escolha.' },
    { id: 'espiao', nome: 'Espião', livro: 'herois', pagina: 49, tipo: 'especial',
      beneficio: 'Você é treinado em Enganação e Ladinagem. Além disso, escolha uma de suas perícias (exceto Luta ou Pontaria). Você pode usar Carisma como atributo-chave dessa perícia (em vez do atributo original).',
      itens: 'Estojo de disfarces, gazua, luneta, três doses de cosmético.' },
    { id: 'ferreiro-militar', nome: 'Ferreiro Militar', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (armeiro). Além disso, recebe +2 em rolagens de dano com martelos e marretas de qualquer tipo.',
      itens: 'Instrumentos de armeiro, martelo leve (p. 221).' },
    { id: 'freira', nome: 'Freira', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinada em Cura. Quando faz um teste para ajudar, você pode gastar 1 PM para aumentar o bônus da ajuda em +1d4 e, quando usa um efeito de cura, pode gastar 1 PM para aumentar esse efeito em +1 dado do mesmo tipo.',
      itens: 'Maleta de medicamentos, manto eclesiástico, símbolo sagrado.' },
    { id: 'goradista', nome: 'Goradista', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (cozinheiro) e, quando prepara um prato especial, pode gastar T$ 10 a mais para adicionar cobertura de gorad a ele. Além de seus benefícios normais, um prato especial com cobertura de gorad fornece 2 PM temporários por patamar do comensal.',
      itens: 'Instrumentos de cozinheiro, T$ 36 em ingredientes para produzir gorad quente.' },
    { id: 'insciente', nome: 'Insciente', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Sobrevivência e recebe resistência a magia +5.',
      itens: 'Uma arma simples ou ferramenta a sua escolha de até T$ 100.' },
    { id: 'interrogador', nome: 'Interrogador', livro: 'herois', pagina: 50, tipo: 'especial',
      beneficio: 'Você é treinado em Intimidação e Investigação, e recebe +1 na margem de ameaça contra criaturas feridas (PV abaixo do total), pois aprendeu a bater onde mais dói.',
      itens: 'Um ou mais itens somando T$ 100 que pertenciam a antigas vítim... ahem, interrogados.' },
    { id: 'ladrao-de-tumulos', nome: 'Ladrão de Túmulos', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você é treinado em Ladinagem e Sobrevivência, e recebe +2 na Defesa e em testes de perícia contra mortos-vivos. Além disso, recebe redução de trevas 5 (ou, se for um morto-vivo, recupera +1 PV por dado de dano de trevas).',
      itens: 'Pá (mesmas estatísticas de uma lança), pé de cabra.' },
    { id: 'menestrel', nome: 'Menestrel', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você é treinado em Atuação e recebe um poder de Música de bardo, escolhido entre Balada Fascinante, Canção Assustadora e Melodia Curativa.',
      itens: 'Um instrumento musical de até T$ 35 a sua escolha.' },
    { id: 'mensageiro', nome: 'Mensageiro', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você recebe +3m em seu deslocamento e +2 em testes de resistência.',
      itens: 'Cavalo com sela, mochila de aventureiro, traje de viajante.' },
    { id: 'naufrago', nome: 'Náufrago', livro: 'herois', pagina: 51, tipo: 'especial',
      beneficio: 'Você recebe +5 PV e +2 PM. Além disso, uma vez por cena pode gastar 2 PM para receber um dos seguintes benefícios até o fim da cena: treinamento em uma perícia; proficiência com uma arma, armadura ou escudo; usar uma ferramenta no lugar de outra.',
      itens: 'Arco curto, 20 flechas, uma bola (ou outro objeto simples) com uma cara pintada e nome de gente.' },
    { id: 'padeiro', nome: 'Padeiro', livro: 'herois', pagina: 52, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (cozinheiro). Além disso, sua profissão fortificou seus braços! Você recebe +1 em rolagens de dano com armas de impacto e pode substituir testes de Atletismo por testes de Ofício (cozinheiro).',
      itens: 'Instrumentos de Ofício (cozinheiro), rolo de massa (mesmas estatísticas de uma clava).' },
    { id: 'pedinte', nome: 'Pedinte', livro: 'herois', pagina: 52, tipo: 'especial',
      beneficio: 'Você é muito discreto, recebendo +2 em Enganação e Furtividade. Além disso, aprendeu a aproveitar o máximo de cada recurso e a partilhar do pouco que tinha com seus companheiros em dificuldades. Quando você usa um alimento, preparado alquímico ou poção, pode rolar seu efeito duas vezes e usar o melhor resultado (se o efeito for aleatório), ou pode dividir o item com um aliado adjacente (ele também gasta a ação para consumi-lo e recebe o benefício normal, mas você gasta apenas um item).',
      itens: 'Andrajos, esmolas que guardou (1 bálsamo restaurador e 1 essência de mana).' },
    { id: 'pescador', nome: 'Pescador', livro: 'herois', pagina: 52, tipo: 'especial',
      beneficio: 'Você é treinado em Ofício (pescador) e Sobrevivência. Além disso, você sabe aguardar o instante exato de puxar o anzol. Recebe +2 em Iniciativa e, sempre que prepara uma ação (Tormenta20, p. 234), recebe +2 em testes para executá-la.',
      itens: 'Bolsa cheia de minhocas, instrumentos de pescador.' },
    { id: 'servo', nome: 'Servo', livro: 'herois', pagina: 53, tipo: 'especial',
      beneficio: 'Você é treinado em Diplomacia e Ofício (serviçal). Além disso, recebe +2 em testes de Diplomacia e Enganação contra alvos que tenham status ou posição superior à sua (ou que acreditam ter), e pode substituir testes de Nobreza por testes de Ofício (serviçal).',
      itens: 'Balde e vassoura (mesmas estatísticas de um bordão), tabardo de seu patrono.' },
    { id: 'suporte-de-tropas', nome: 'Suporte de Tropas', livro: 'herois', pagina: 53, tipo: 'especial',
      beneficio: 'Sempre que você faz um teste para ajudar, o bônus que fornece aumenta em +2. Além disso, quando flanqueia um inimigo, o bônus que você e seus aliados recebem em testes de ataque aumenta para +4.',
      itens: 'Equipamento de viagem, instrumentos de ofício, maleta de medicamentos.' },
  ];

  window.GA_ORIGENS_LIVROS = { t20: 'Tormenta20', herois: 'Heróis de Arton' };
})();
